// =============================================================================
// AI DISCLOSURE (v77) — telling people they're talking to a machine.
//
// The EU AI Act requires that people be informed when they're interacting with
// an AI system, unless it's obvious from the context. This app deliberately
// makes it NOT obvious: the guide has a name, a home town, a job and a
// first-person introduction, because a character is easier to talk to than a
// text box. That design choice is exactly what the rule is about, so the
// disclosure has to be real rather than a line in a policy nobody opens.
//
// Three pieces:
//   AiGate    a one-time screen before the first AI conversation: what it is,
//             what it gets wrong, what leaves your device, and an age check.
//             Declining leaves the whole rest of the app working.
//   AiBadge   a persistent marker on every AI surface. Not a toast that fades —
//             if you look at the screen, you can see it's a machine.
//   ReportAi  a report control on AI output, which app store policy requires for
//             anything that generates user-facing content, and which is the only
//             way we hear about it when the model says something bad.
// =============================================================================

import React, { useState } from "react";
import { AI_MIN_AGE, AI_DISCLOSURE } from "../legal/policies.js";

/** Has this person seen the disclosure and accepted? */
export function aiAccepted(appState) {
  return appState?.aiConsent?.accepted === true;
}

/** Have they actively declined? Used to offer it again rather than nag. */
export function aiDeclined(appState) {
  return appState?.aiConsent?.accepted === false;
}

// ---------------------------------------------------------------------------
export function AiGate({ appState, setAppState, guideName, langName, onDecline, onNavigate }) {
  const [ageOk, setAgeOk] = useState(false);
  const [read, setRead] = useState(false);

  function accept() {
    setAppState((s) => ({
      ...s,
      aiConsent: { accepted: true, at: Date.now(), ageConfirmed: AI_MIN_AGE, version: 1 },
    }));
  }
  function decline() {
    setAppState((s) => ({ ...s, aiConsent: { accepted: false, at: Date.now(), version: 1 } }));
    onDecline?.();
  }

  return (
    <div className="speak-body">
      <div className="intro-card ai-gate">
        <div className="ai-badge ai-badge-lg">AI</div>
        <h2 className="intro-title">{guideName || "Your guide"} is an AI</h2>
        <p className="intro-sub">
          Not a person, not a native speaker checking your work. A language model
          playing a character, so that talking to it feels like talking to
          someone. Before you start, three things worth knowing.
        </p>

        <ul className="intro-points">
          <li>
            <b>It gets things wrong.</b> It can produce {langName} that's
            ungrammatical, regionally out of place, or invented. The lessons,
            example sentences and route phrases are written and checked by hand —
            this isn't. If the two disagree, trust the course.
          </li>
          <li>
            <b>What you say here leaves your device.</b> Your text, the recent
            turns, and a short summary of your practice record — your level and
            the mistakes you repeat — go to our server and to Anthropic, who run
            the model. No name, no email, no identifier. Nothing else in the app
            sends anything anywhere.
          </li>
          <li>
            <b>You don't need it.</b> Decline and lessons, vocabulary, reading,
            grammar, the alphabet course, speaking drills and your progress all
            keep working exactly as they do now.
          </li>
        </ul>

        <label className="ai-check">
          <input type="checkbox" checked={read} onChange={(e) => setRead(e.target.checked)} />
          <span>I understand this is an AI and can be wrong.</span>
        </label>
        <label className="ai-check">
          <input type="checkbox" checked={ageOk} onChange={(e) => setAgeOk(e.target.checked)} />
          <span>I am {AI_MIN_AGE} or older.</span>
        </label>

        <button className="btn-hero" onClick={accept} disabled={!read || !ageOk}>
          Start talking
        </button>
        <button className="btn-quiet" onClick={decline}>No thanks — keep the rest</button>
        <button className="quiet-link" onClick={() => onNavigate?.("legal", { policy: AI_DISCLOSURE.id, back: "speak" })}>
          read the full AI disclosure
        </button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
/** Persistent marker. Present wherever model output is. */
export function AiBadge({ label = "AI", title = "Generated by an AI language model — it can be wrong" }) {
  return <span className="ai-badge" title={title} aria-label={title}>{label}</span>;
}

/** A line of text under an AI surface, for screens where a badge isn't enough. */
export function AiNote({ children }) {
  return <div className="ai-note"><AiBadge />{children}</div>;
}

// ---------------------------------------------------------------------------
/**
 * Report control on AI output.
 *
 * Stored locally and surfaced in Settings rather than silently posted anywhere —
 * this app has no reporting backend, and pretending a report was filed when it
 * wasn't would be worse than saying so. The learner is told exactly what
 * happens, and the stored reports go out with the data export.
 */
export function ReportAi({ text, context, appState, setAppState }) {
  const [done, setDone] = useState(false);

  function report() {
    setAppState((s) => ({
      ...s,
      aiReports: [
        ...(s.aiReports || []).slice(-49),
        { ts: Date.now(), text: String(text || "").slice(0, 500), context: context || null },
      ],
    }));
    setDone(true);
  }

  if (done) {
    return (
      <span className="ai-report ai-report-done">
        Flagged. It's saved with your data — Settings has the list, and it goes out with your export.
      </span>
    );
  }
  return (
    <button className="ai-report" onClick={report} aria-label="Report this AI reply">
      report
    </button>
  );
}
