#!/usr/bin/env node
// =============================================================================
// expand-asia.mjs — Chinese, Japanese, Korean, Bengali, Indonesian and Nigerian
// Pidgin core vocabulary.
//
// Same target: the concepts each pack was measurably missing from the beginner
// essentials. Conventions kept per pack:
//   zh  simplified characters, pinyin WITH tone marks in translit
//   ja  the polite (-masu / desu) register throughout, since that's what a
//       learner should use with anyone they don't know
//   ko  the 해요 polite register for the same reason
//   bn  standard colloquial Bengali
//   id  standard Indonesian, no formal/informal split needed at this level
//   pcm Nigerian Pidgin, written the way it's actually written
// =============================================================================

import { merge } from "./merge.mjs";

const zh = [
  ["坏","huài","hwye","bad","u9","Common",1,[["天气很坏","The weather is bad"]]],
  ["食物","shíwù","shr-woo","food","u5","Food",2,[["食物很好吃","The food is delicious"]]],
  ["知道","zhīdào","jr-dow","to know","u6","Verbs",1,[["我不知道","I don't know"]]],
  ["能","néng","nung","to be able to, can","u6","Verbs",1,[["你能帮我吗？","Can you help me?"]]],
  ["明白","míngbai","ming-bye","to understand","u6","Verbs",2,[["我不明白","I don't understand"]]],
  ["钱","qián","chyen","money","u10","Common",1,[["我没有钱","I don't have money"]]],
  ["时间","shíjiān","shr-jyen","time","u8","Time",1,[["我没有时间","I don't have time"]]],
  ["天","tiān","tyen","day","u8","Time",1,[["今天是好天","Today is a good day"]]],
  ["昨天","zuótiān","dzwor-tyen","yesterday","u8","Time",1,[["昨天很冷","Yesterday was cold"]]],
  ["怎么","zěnme","dzun-muh","how","u9","Connectors",1,[["这个怎么用？","How do you use this?"]]],
  ["男人","nánrén","nan-run","man","u2","People",1,[["那个男人是我哥哥","That man is my brother"]]],
  ["女人","nǚrén","nyu-run","woman","u2","People",1,[["那个女人是医生","That woman is a doctor"]]],
  ["房子","fángzi","fahng-dz","house","u7","Places",1,[["房子很大","The house is big"]]],
  ["路","lù","loo","road","u13","Travel",1,[["这条路很长","This road is long"]]],
  ["工作","gōngzuò","gong-dzwor","work","u2","Common",1,[["我的工作很忙","My work is busy"]]],
  ["价格","jiàgé","jya-guh","price","u10","Common",2,[["价格是多少？","What's the price?"]]],
  ["开","kāi","kye","to open","u6","Verbs",1,[["请开门","Please open the door"]]],
  ["热","rè","ruh","hot","u12","Weather",1,[["今天很热","It's hot today"]]],
  ["冷","lěng","lung","cold","u12","Weather",1,[["水很冷","The water is cold"]]],
  ["更","gèng","gung","more","u9","Connectors",2,[["更好一点","A little better"]]],
  ["很","hěn","hun","very","u9","Connectors",1,[["很好","Very good"]]],
  ["没有","méiyǒu","may-yo","without, not have","u9","Connectors",1,[["没有糖","Without sugar"]]],
  ["都","dōu","doh","all","u9","Connectors",1,[["都很好","All is well"]]],
  ["左","zuǒ","dzwor","left","u13","Travel",1,[["往左转","Turn left"]]],
  ["右","yòu","yo","right","u13","Travel",1,[["在右边","On the right"]]],
  ["近","jìn","jin","near","u13","Travel",1,[["很近","Very near"]]],
  ["远","yuǎn","ywen","far","u13","Travel",1,[["太远了","Too far"]]],
  ["名字","míngzi","ming-dz","name","u2","About You",1,[["你叫什么名字？","What's your name?"]]],
  ["病","bìng","bing","sick, ill","u11","Body",1,[["我病了","I'm ill"]]],
  ["医生","yīshēng","ee-shung","doctor","u11","Body",1,[["我需要医生","I need a doctor"]]],
];

const ja = [
  ["悪い","warui","wah-roo-ee","bad","u10","Common",1,[["天気が悪いです","The weather is bad"]]],
  ["食べ物","tabemono","tah-beh-mo-no","food","u5","Food",1,[["食べ物がおいしいです","The food is delicious"]]],
  ["あります","arimasu","ah-ree-mahs","to have, there is","u6","Verbs",1,[["時間がありません","I don't have time"]]],
  ["ほしいです","hoshii desu","ho-shee dess","to want","u6","Verbs",2,[["水がほしいです","I want water"]]],
  ["作ります","tsukurimasu","tsoo-koo-ree-mahs","to make","u6","Verbs",2,[["お茶を作ります","I'll make tea"]]],
  ["できます","dekimasu","deh-kee-mahs","to be able to, can","u6","Verbs",2,[["手伝えますか","Can you help?"]]],
  ["必要","hitsuyou","hee-tsoo-yoh","need, necessary","u10","Common",2,[["助けが必要です","I need help"]]],
  ["取ります","torimasu","toh-ree-mahs","to take","u6","Verbs",2,[["電車を取ります","I'll take the train"]]],
  ["手伝います","tetsudaimasu","teh-tsoo-dye-mahs","to help","u6","Verbs",2,[["手伝ってください","Please help me"]]],
  ["わかります","wakarimasu","wah-kah-ree-mahs","to understand","u6","Verbs",1,[["わかりません","I don't understand"]]],
  ["お金","okane","oh-kah-neh","money","u10","Common",1,[["お金がありません","I don't have money"]]],
  ["日","hi","hee","day","u8","Time",1,[["いい日ですね","It's a nice day"]]],
  ["昨日","kinou","kee-noh","yesterday","u8","Time",1,[["昨日は寒かったです","Yesterday was cold"]]],
  ["何","nani","nah-nee","what","u10","Common",1,[["これは何ですか","What is this?"]]],
  ["どう","dou","doh","how","u10","Common",1,[["どうやって使いますか","How do you use it?"]]],
  ["男の人","otoko no hito","oh-toh-ko no hee-to","man","u2","People",1,[["あの男の人は兄です","That man is my brother"]]],
  ["女の人","onna no hito","on-nah no hee-to","woman","u2","People",1,[["あの女の人は医者です","That woman is a doctor"]]],
  ["町","machi","mah-chee","town, city","u7","Places",1,[["この町は静かです","This town is quiet"]]],
  ["車","kuruma","koo-roo-mah","car","u11","Travel",1,[["車で行きます","I'll go by car"]]],
  ["道","michi","mee-chee","road, way","u11","Travel",1,[["道が長いです","The road is long"]]],
  ["仕事","shigoto","shee-go-toh","work, job","u2","Common",1,[["仕事が忙しいです","Work is busy"]]],
  ["開けます","akemasu","ah-keh-mahs","to open","u6","Verbs",2,[["ドアを開けてください","Please open the door"]]],
  ["暑い","atsui","ah-tsoo-ee","hot (weather)","u10","Common",1,[["今日は暑いです","It's hot today"]]],
  ["寒い","samui","sah-moo-ee","cold (weather)","u10","Common",1,[["今日は寒いです","It's cold today"]]],
  ["とても","totemo","toh-teh-mo","very","u10","Common",1,[["とてもいいです","Very good"]]],
  ["でも","demo","deh-mo","but","u10","Common",1,[["小さいでもきれいです","Small but pretty"]]],
  ["から","kara","kah-rah","because, from","u10","Common",2,[["雨だから行きません","I won't go because it's raining"]]],
  ["左","hidari","hee-dah-ree","left","u11","Travel",1,[["左に曲がります","Turn left"]]],
  ["右","migi","mee-ghee","right","u11","Travel",1,[["右にあります","It's on the right"]]],
  ["名前","namae","nah-mah-eh","name","u2","About You",1,[["お名前は何ですか","What's your name?"]]],
  ["病気","byouki","byoh-kee","sick, ill","u9","Feelings",1,[["病気です","I'm ill"]]],
  ["医者","isha","ee-shah","doctor","u7","Places",1,[["医者が必要です","I need a doctor"]]],
  ["トイレ","toire","toy-reh","bathroom, toilet","u7","Places",1,[["トイレはどこですか","Where is the toilet?"]]],
];

const ko = [
  ["나쁘다","nappeuda","nah-ppeu-dah","bad","u10","Common",1,[["날씨가 나빠요","The weather is bad"]]],
  ["음식","eumsik","eum-shik","food","u5","Food",1,[["음식이 맛있어요","The food is delicious"]]],
  ["있다","itda","it-tah","to have, there is","u6","Verbs",1,[["시간이 없어요","I don't have time"]]],
  ["원하다","wonhada","won-hah-dah","to want","u6","Verbs",2,[["물을 원해요","I want water"]]],
  ["말하다","malhada","mal-hah-dah","to say, to speak","u6","Verbs",1,[["뭐라고 말했어요?","What did you say?"]]],
  ["만들다","mandeulda","man-deul-dah","to make","u6","Verbs",2,[["차를 만들어요","I make tea"]]],
  ["할 수 있다","hal su itda","hal soo it-tah","to be able to, can","u6","Verbs",2,[["도와줄 수 있어요?","Can you help?"]]],
  ["돕다","dopda","dop-tah","to help","u6","Verbs",2,[["도와주세요","Please help me"]]],
  ["이해하다","ihaehada","ee-heh-hah-dah","to understand","u6","Verbs",2,[["이해 못 했어요","I didn't understand"]]],
  ["돈","don","don","money","u10","Common",1,[["돈이 없어요","I don't have money"]]],
  ["시간","sigan","shee-gan","time","u8","Time",1,[["시간이 있어요?","Do you have time?"]]],
  ["어제","eoje","aw-jeh","yesterday","u8","Time",1,[["어제 추웠어요","Yesterday was cold"]]],
  ["어떻게","eotteoke","aw-ttaw-keh","how","u9","Connectors",1,[["어떻게 가요?","How do I get there?"]]],
  ["남자","namja","nam-jah","man","u2","People",1,[["저 남자는 제 형이에요","That man is my brother"]]],
  ["여자","yeoja","yaw-jah","woman","u2","People",1,[["저 여자는 의사예요","That woman is a doctor"]]],
  ["차","cha","chah","car","u13","Travel",1,[["차로 가요","I'll go by car"]]],
  ["길","gil","gil","road, way","u13","Travel",1,[["이 길은 길어요","This road is long"]]],
  ["일","il","il","work, job","u2","Common",1,[["일이 많아요","I have a lot of work"]]],
  ["가격","gagyeok","kah-gyawk","price","u10","Common",2,[["가격이 얼마예요?","What's the price?"]]],
  ["열다","yeolda","yawl-dah","to open","u6","Verbs",2,[["문을 열어 주세요","Please open the door"]]],
  ["덥다","deopda","dawp-tah","hot (weather)","u12","Weather",1,[["오늘 더워요","It's hot today"]]],
  ["춥다","chupda","choop-tah","cold (weather)","u12","Weather",1,[["오늘 추워요","It's cold today"]]],
  ["더","deo","daw","more","u9","Connectors",1,[["조금 더","A little more"]]],
  ["아주","aju","ah-joo","very","u9","Connectors",1,[["아주 좋아요","Very good"]]],
  ["같이","gachi","kah-chee","with, together","u9","Connectors",1,[["같이 가요","Let's go together"]]],
  ["없이","eopsi","awp-shee","without","u9","Connectors",2,[["설탕 없이","Without sugar"]]],
  ["모두","modu","mo-doo","all, everyone","u9","Connectors",1,[["모두 좋아요","All is well"]]],
  ["왼쪽","oenjjok","wen-jjok","left","u13","Travel",1,[["왼쪽으로 가세요","Go left"]]],
  ["오른쪽","oreunjjok","oh-reun-jjok","right","u13","Travel",1,[["오른쪽에 있어요","It's on the right"]]],
  ["가깝다","gakkapda","kah-kkap-tah","near","u13","Travel",2,[["여기서 가까워요","It's near here"]]],
  ["멀다","meolda","mawl-dah","far","u13","Travel",2,[["너무 멀어요","It's too far"]]],
  ["이름","ireum","ee-reum","name","u2","About You",1,[["이름이 뭐예요?","What's your name?"]]],
  ["아프다","apeuda","ah-peu-dah","sick, in pain","u11","Body",1,[["아파요","I'm ill"]]],
  ["의사","uisa","eui-sah","doctor","u11","Body",1,[["의사가 필요해요","I need a doctor"]]],
  ["화장실","hwajangsil","hwah-jang-shil","bathroom, toilet","u7","Places",1,[["화장실이 어디예요?","Where is the toilet?"]]],
];

const bn = [
  ["তুমি","tumi","TOO-mee","you (familiar)","u2","People",1,[["তুমি কোথায়?","Where are you?"]]],
  ["খারাপ","kharap","KHA-rap","bad","u9","Common",1,[["আবহাওয়া খারাপ","The weather is bad"]]],
  ["থাকা","thaka","THA-ka","to have, to stay","u6","Verbs",2,[["আমার সময় নেই","I don't have time"]]],
  ["বানানো","banano","ba-NA-no","to make","u6","Verbs",2,[["আমি চা বানাই","I make tea"]]],
  ["পারা","para","PA-ra","to be able to, can","u6","Verbs",2,[["আপনি সাহায্য করতে পারেন?","Can you help?"]]],
  ["দরকার","dorkar","DOR-kar","need","u9","Common",2,[["আমার সাহায্য দরকার","I need help"]]],
  ["বোঝা","bojha","BO-jha","to understand","u6","Verbs",2,[["আমি বুঝিনি","I didn't understand"]]],
  ["টাকা","taka","TA-ka","money","u10","Common",1,[["আমার টাকা নেই","I don't have money"]]],
  ["সময়","somoy","SHO-moy","time","u8","Time",1,[["সময় নেই","There's no time"]]],
  ["এখানে","ekhane","EH-kha-ne","here","u10","Common",1,[["আমি এখানে আছি","I'm here"]]],
  ["ওখানে","okhane","OH-kha-ne","there","u10","Common",1,[["ওটা ওখানে","It's there"]]],
  ["কীভাবে","kibhabe","KEE-bha-be","how","u9","Connectors",1,[["এটা কীভাবে কাজ করে?","How does this work?"]]],
  ["পুরুষ","purush","PU-rush","man","u2","People",1,[["ওই পুরুষ আমার ভাই","That man is my brother"]]],
  ["মহিলা","mohila","MO-hi-la","woman","u2","People",1,[["ওই মহিলা ডাক্তার","That woman is a doctor"]]],
  ["শহর","shohor","SHO-hor","city","u7","Places",1,[["শহরটা বড়","The city is big"]]],
  ["রাস্তা","rasta","RAS-ta","road, street","u7","Places",1,[["রাস্তাটা লম্বা","The road is long"]]],
  ["কাজ","kaj","KAJ","work","u2","Common",1,[["আমার কাজ শেষ","My work is done"]]],
  ["কেনা","kena","KE-na","to buy","u6","Verbs",2,[["আমি রুটি কিনি","I buy bread"]]],
  ["দাম","dam","DAM","price","u10","Common",1,[["এটার দাম কত?","What's the price of this?"]]],
  ["খোলা","khola","KHO-la","to open","u6","Verbs",2,[["দরজা খুলুন","Open the door"]]],
  ["গরম","gorom","GO-rom","hot","u9","Common",1,[["আজ গরম","It's hot today"]]],
  ["ঠান্ডা","thanda","THAN-da","cold","u9","Common",1,[["পানি ঠান্ডা","The water is cold"]]],
  ["খুব","khub","KHOOB","very","u9","Connectors",1,[["খুব ভালো","Very good"]]],
  ["সঙ্গে","shonge","SHONG-ge","with","u9","Connectors",1,[["দুধের সঙ্গে চা","Tea with milk"]]],
  ["ছাড়া","chhara","CHHA-ra","without","u9","Connectors",2,[["চিনি ছাড়া","Without sugar"]]],
  ["সব","shob","SHOB","all, everything","u9","Connectors",1,[["সব ঠিক আছে","Everything is fine"]]],
  ["বাঁ","ban","BAN","left","u10","Common",1,[["বাঁ দিকে","On the left"]]],
  ["ডান","dan","DAN","right","u10","Common",1,[["ডান দিকে","On the right"]]],
  ["নাম","nam","NAM","name","u2","About You",1,[["আপনার নাম কী?","What's your name?"]]],
  ["খুশি","khushi","KHU-shee","happy","u9","Common",1,[["আমি খুব খুশি","I'm very happy"]]],
  ["ক্লান্ত","klanto","KLAN-to","tired","u9","Common",2,[["আমি ক্লান্ত","I'm tired"]]],
  ["অসুস্থ","oshustho","O-shus-tho","sick, ill","u9","Common",2,[["আমি অসুস্থ","I'm ill"]]],
  ["ডাক্তার","daktar","DAK-tar","doctor","u7","Places",1,[["আমার ডাক্তার দরকার","I need a doctor"]]],
];

const id = [
  ["kamu","","KAH-moo","you (informal)","u2","People",1,[["Kamu di mana?","Where are you?"]]],
  ["buruk","","BOO-rook","bad","u6","Common",1,[["Cuacanya buruk","The weather is bad"]]],
  ["punya","","POO-nyah","to have","u2","Verbs",1,[["Saya tidak punya waktu","I don't have time"]]],
  ["tahu","","TAH-hoo","to know","u2","Verbs",1,[["Saya tidak tahu","I don't know"]]],
  ["melakukan","","meh-lah-KOO-kan","to do","u2","Verbs",2,[["Apa yang kamu lakukan?","What are you doing?"]]],
  ["membuat","","mem-BOO-at","to make","u5","Verbs",2,[["Saya membuat teh","I make tea"]]],
  ["bisa","","BEE-sah","to be able to, can","u2","Verbs",1,[["Bisa bantu saya?","Can you help me?"]]],
  ["perlu","","PER-loo","to need","u2","Verbs",2,[["Saya perlu bantuan","I need help"]]],
  ["berbicara","","ber-bee-CHA-rah","to speak","u2","Verbs",2,[["Apakah Anda bicara Inggris?","Do you speak English?"]]],
  ["uang","","OO-ang","money","u6","Common",1,[["Saya tidak punya uang","I don't have money"]]],
  ["waktu","","WAK-too","time","u4","Time",1,[["Tidak ada waktu","There's no time"]]],
  ["hari","","HAH-ree","day","u4","Time",1,[["Selamat hari","Have a good day"]]],
  ["kemarin","","kuh-MAH-rin","yesterday","u4","Time",1,[["Kemarin dingin","Yesterday was cold"]]],
  ["di sini","","dee SEE-nee","here","u6","Common",1,[["Saya di sini","I'm here"]]],
  ["di sana","","dee SAH-nah","there","u6","Common",1,[["Apoteknya di sana","The pharmacy is there"]]],
  ["bagaimana","","bah-guy-MAH-nah","how","u6","Common",1,[["Bagaimana caranya?","How do you do it?"]]],
  ["pria","","PREE-ah","man","u3","People",1,[["Pria itu kakak saya","That man is my brother"]]],
  ["wanita","","wah-NEE-tah","woman","u3","People",1,[["Wanita itu dokter","That woman is a doctor"]]],
  ["kota","","KOH-tah","city","u6","Travel",1,[["Kotanya besar","The city is big"]]],
  ["jalan","","JAH-lan","road, street","u6","Travel",1,[["Jalannya panjang","The road is long"]]],
  ["kerja","","KER-jah","work","u2","Common",1,[["Kerja saya selesai","My work is done"]]],
  ["membeli","","mem-BEH-lee","to buy","u5","Verbs",2,[["Saya membeli roti","I buy bread"]]],
  ["harga","","HAR-gah","price","u6","Common",1,[["Berapa harganya?","What's the price?"]]],
  ["membuka","","mem-BOO-kah","to open","u5","Verbs",2,[["Buka pintunya","Open the door"]]],
  ["panas","","PAH-nas","hot","u6","Common",1,[["Hari ini panas","It's hot today"]]],
  ["dingin","","DEE-ngin","cold","u6","Common",1,[["Airnya dingin","The water is cold"]]],
  ["sangat","","SAH-ngat","very","u6","Common",1,[["Sangat bagus","Very good"]]],
  ["dengan","","DUH-ngan","with","u6","Connectors",1,[["Kopi dengan susu","Coffee with milk"]]],
  ["tanpa","","TAN-pah","without","u6","Connectors",2,[["Tanpa gula","Without sugar"]]],
  ["semua","","suh-MOO-ah","all, everything","u6","Connectors",1,[["Semua baik","Everything is fine"]]],
  ["kiri","","KEE-ree","left","u6","Travel",1,[["Belok kiri","Turn left"]]],
  ["kanan","","KAH-nan","right","u6","Travel",1,[["Di sebelah kanan","On the right"]]],
  ["nama","","NAH-mah","name","u2","About You",1,[["Siapa nama Anda?","What's your name?"]]],
  ["senang","","suh-NANG","happy","u2","Common",1,[["Saya senang","I'm happy"]]],
  ["lelah","","luh-LAH","tired","u2","Common",2,[["Saya lelah","I'm tired"]]],
  ["sakit","","SAH-kit","sick, painful","u2","Common",1,[["Saya sakit","I'm ill"]]],
  ["dokter","","DOK-ter","doctor","u6","Common",1,[["Saya perlu dokter","I need a doctor"]]],
  ["kamar kecil","","KAH-mar kuh-CHEEL","bathroom, toilet","u6","Travel",2,[["Di mana kamar kecil?","Where is the toilet?"]]],
];

const pcm = [
  ["yes","","YES","yes","u1","Greetings",1,[["Yes, na me","Yes, it's me"]]],
  ["no","","NO","no","u1","Greetings",1,[["No wahala","No problem"]]],
  ["abeg","","ah-BEG","please","u1","Greetings",1,[["Abeg helep me","Please help me"]]],
  ["big","","BIG","big","u5","Common",1,[["Di house big well well","The house is really big"]]],
  ["small","","SMOL","small","u5","Common",1,[["Small small","Little by little"]]],
  ["drink","","DRINK","to drink","u5","Verbs",1,[["I wan drink water","I want to drink water"]]],
  ["get","","GET","to have","u2","Verbs",1,[["I no get money","I don't have money"]]],
  ["do","","DU","to do","u2","Verbs",1,[["Wetin you dey do?","What are you doing?"]]],
  ["make","","MEK","to make","u5","Verbs",1,[["I go make tea","I'll make tea"]]],
  ["fit","","FIT","to be able to, can","u2","Verbs",1,[["You fit helep me?","Can you help me?"]]],
  ["need","","NID","to need","u2","Verbs",1,[["I need helep","I need help"]]],
  ["helep","","HEH-lep","to help","u2","Verbs",1,[["Helep me abeg","Help me please"]]],
  ["time","","TAIM","time","u4","Time",1,[["I no get time","I don't have time"]]],
  ["day","","DEH","day","u4","Time",1,[["Good day o","Good day"]]],
  ["yesterday","","YES-ta-deh","yesterday","u4","Time",1,[["Yesterday cold","Yesterday was cold"]]],
  ["now now","","NAU-nau","right now","u4","Time",1,[["I dey come now now","I'm coming right now"]]],
  ["here","","HIA","here","u6","Common",1,[["I dey here","I'm here"]]],
  ["there","","DIA","there","u6","Common",1,[["E dey there","It's there"]]],
  ["how","","HAU","how","u6","Common",1,[["How e dey work?","How does it work?"]]],
  ["man","","MAN","man","u3","People",1,[["Dat man na my broda","That man is my brother"]]],
  ["woman","","WU-man","woman","u3","People",1,[["Dat woman na doctor","That woman is a doctor"]]],
  ["padi","","PAH-dee","friend","u3","People",1,[["Na my padi","That's my friend"]]],
  ["town","","TAUN","city, town","u6","Travel",1,[["Di town big","The town is big"]]],
  ["road","","ROD","road","u6","Travel",1,[["Di road long","The road is long"]]],
  ["work","","WOK","work","u2","Common",1,[["My work don finish","My work is done"]]],
  ["price","","PRAIS","price","u6","Common",1,[["Wetin be di price?","What's the price?"]]],
  ["open","","OH-pen","to open","u5","Verbs",1,[["Open di door","Open the door"]]],
  ["hot","","HOT","hot","u5","Common",1,[["Sun dey hot today","It's hot today"]]],
  ["cold","","KOLD","cold","u5","Common",1,[["Di water cold","The water is cold"]]],
  ["well well","","WEL-wel","very, a lot","u5","Common",1,[["I like am well well","I like it a lot"]]],
  ["with","","WIT","with","u6","Connectors",1,[["Tea with milk","Tea with milk"]]],
  ["witout","","wit-AUT","without","u6","Connectors",2,[["Witout sugar","Without sugar"]]],
  ["everybody","","EV-ree-bo-di","everyone, all","u6","Connectors",1,[["Everybody dey fine","Everyone is fine"]]],
  ["left","","LEFT","left","u6","Travel",1,[["Turn left","Turn left"]]],
  ["right","","RAIT","right","u6","Travel",1,[["Na for your right","It's on your right"]]],
  ["name","","NEM","name","u2","About You",1,[["Wetin be your name?","What's your name?"]]],
  ["happy","","HA-pi","happy","u2","Common",1,[["I happy well well","I'm very happy"]]],
  ["tayad","","TAH-yad","tired","u2","Common",1,[["I tayad","I'm tired"]]],
  ["sick","","SIK","sick, ill","u2","Common",1,[["I dey sick","I'm ill"]]],
  ["doctor","","DOK-ta","doctor","u6","Common",1,[["I need doctor","I need a doctor"]]],
  ["toilet","","TOY-let","bathroom, toilet","u6","Travel",1,[["Where di toilet?","Where's the toilet?"]]],
];

merge("zh", zh);
merge("ja", ja);
merge("ko", ko);
merge("bn", bn);
merge("id", id, { translitIsLemma: true });
merge("pcm", pcm, { translitIsLemma: true });
