// =============================================================================
// second-frames.mjs (v101) — a second sentence for every survival word.
//
// THE PROBLEM, from the app's own research audit:
//
//     "A word met in a single frame is known in that frame."
//
// Measured after v100: 3,145 words, and 2,651 of them — 84% — appear in exactly
// one sentence in the entire app. A learner who meets ك ب as "Beber agua" and
// nowhere else has learned a collocation, not a verb.
//
// This closes it for the tier that matters most: the 42 survival concepts every
// language is required to teach, which are also the words the SRS shows most
// often and the input stream reuses most.
//
// WHAT MAKES A SECOND FRAME WORTH HAVING
//
// Not a second sentence. A DIFFERENT one — the word in a different slot:
//
//     Beber   frame 1  "Beber agua"              bare infinitive, then object
//             frame 2  "Bebo té cada mañana"     conjugated, sentence-initial
//
//     baño    frame 1  "¿Dónde está el baño?"    object of a question, final
//             frame 2  "El baño está a la derecha"  subject, initial
//
// A frame that differs by one swapped noun teaches the word in the same slot
// twice, which is the thing this is meant to fix. validate-second-frames.mjs
// enforces that: the two frames must differ in where the word sits, or in what
// kind of sentence it is.
//
// Fields: lemma → [nativeSentence, translit, englishTranslation]
// translit is "" for the Latin-script languages, which carry none.
// =============================================================================

export const SECOND_FRAMES = {
  // ===========================================================================
  // SPANISH
  // ===========================================================================
  es: {
    "Él": ["¿Dónde está él?", "", "Where is he?"],
    "Ella": ["Voy con ella", "", "I'm going with her"],
    "Nosotros": ["¿Nosotros también?", "", "Us too?"],
    "Qué": ["No sé qué decir", "", "I don't know what to say"],
    "Quién": ["¿Con quién vas?", "", "Who are you going with?"],
    "Beber": ["Bebo té cada mañana", "", "I drink tea every morning"],
    "Hablar": ["Mi madre habla tres idiomas", "", "My mother speaks three languages"],
    "Dónde": ["No sé dónde vive", "", "I don't know where he lives"],
    "Cuánto": ["¿Cuánto tiempo tienes?", "", "How much time do you have?"],
    "Ayuda": ["Gracias por tu ayuda", "", "Thanks for your help"],
    "Decir": ["¿Qué quieres decir?", "", "What do you mean?"],
    "Cuándo": ["Dime cuándo llegas", "", "Tell me when you arrive"],
    "Por qué": ["No sé por qué está triste", "", "I don't know why he's sad"],
    "Perdón": ["Pide perdón a tu hermana", "", "Say sorry to your sister"],
    "Entender": ["Quiero entender mejor", "", "I want to understand better"],
    "Mal": ["Hablo mal el francés", "", "I speak French badly"],
    "lo siento": ["Lo siento mucho", "", "I'm very sorry"],
    "malo": ["Es un día malo", "", "It's a bad day"],
    "venir": ["Mañana viene mi hermana", "", "My sister is coming tomorrow"],
    "nombre": ["Escribe tu nombre aquí", "", "Write your name here"],
    "baño": ["El baño está a la derecha", "", "The bathroom is on the right"],
  },

  // ===========================================================================
  // FRENCH
  // ===========================================================================
  fr: {
    "Salut": ["Bon, salut !", "", "Right, bye!"],
    "Vous": ["Je vous écoute", "", "I'm listening to you"],
    "Il": ["Qu'est-ce qu'il fait ?", "", "What is he doing?"],
    "Elle": ["Je pars avec elle", "", "I'm leaving with her"],
    "Nous": ["Chez nous, c'est différent", "", "At our place it's different"],
    "Quoi": ["Je ne sais pas quoi faire", "", "I don't know what to do"],
    "Qui": ["Avec qui tu viens ?", "", "Who are you coming with?"],
    "Boire": ["Je bois du thé le matin", "", "I drink tea in the morning"],
    "Parler": ["Ma mère parle trois langues", "", "My mother speaks three languages"],
    "Où": ["Je ne sais pas où il habite", "", "I don't know where he lives"],
    "Combien": ["Combien de frères as-tu ?", "", "How many brothers do you have?"],
    "Aide": ["Merci pour ton aide", "", "Thanks for your help"],
    "Dire": ["Qu'est-ce que tu veux dire ?", "", "What do you mean?"],
    "Comprendre": ["Je veux comprendre", "", "I want to understand"],
    "Quand": ["Dis-moi quand tu arrives", "", "Tell me when you arrive"],
    "Pourquoi": ["Je ne sais pas pourquoi", "", "I don't know why"],
    "désolé": ["Je suis vraiment désolé", "", "I'm really sorry"],
    "mauvais": ["C'est une mauvaise journée", "", "It's a bad day"],
    "nourriture": ["Il n'y a pas de nourriture", "", "There's no food"],
    "venir": ["Ma sœur vient demain", "", "My sister is coming tomorrow"],
    "vouloir": ["Elle ne veut pas partir", "", "She doesn't want to leave"],
    "besoin": ["Tu as besoin de quelque chose ?", "", "Do you need something?"],
    "nom": ["Écris ton nom ici", "", "Write your name here"],
    "toilettes": ["Les toilettes sont à droite", "", "The toilets are on the right"],
  },

  // ===========================================================================
  // GERMAN
  // ===========================================================================
  de: {
    "Guten Tag": ["Sie sagte nur: Guten Tag.", "", "She only said: good day."],
    "Auf Wiedersehen": ["Auf Wiedersehen, bis nächste Woche!", "", "Goodbye, until next week!"],
    "Servus": ["Servus miteinander!", "", "Hello everyone!"],
    "kommen": ["Kommst du mit?", "", "Are you coming along?"],
    "gut": ["Das Essen ist sehr gut.", "", "The food is very good."],
    "schlecht": ["Ich schlafe schlecht.", "", "I sleep badly."],
    "Name": ["Schreib deinen Namen hier.", "", "Write your name here."],
    "Mutter": ["Ich rufe meine Mutter an.", "", "I'm calling my mother."],
    "Vater": ["Das ist das Haus meines Vaters.", "", "That is my father's house."],
    "eins": ["Eins, zwei, drei.", "", "One, two, three."],
    "zwei": ["Ich habe zwei Schwestern.", "", "I have two sisters."],
    "drei": ["Wir bleiben drei Tage.", "", "We are staying three days."],
    "Wasser": ["Das Wasser ist kalt.", "", "The water is cold."],
    "trinken": ["Ich trinke jeden Morgen Tee.", "", "I drink tea every morning."],
    "haben": ["Hast du Hunger?", "", "Are you hungry?"],
    "gehen": ["Wie geht es dir?", "", "How are you?"],
    "sprechen": ["Meine Mutter spricht drei Sprachen.", "", "My mother speaks three languages."],
    "verstehen": ["Ich möchte dich verstehen.", "", "I want to understand you."],
    "helfen": ["Ich helfe dir gern.", "", "I'm glad to help you."],
    "möchten": ["Möchtest du mitkommen?", "", "Would you like to come along?"],
    "Haus": ["Wir gehen ins Haus.", "", "We're going into the house."],
    "heute": ["Ich arbeite heute nicht.", "", "I'm not working today."],
    "morgen": ["Morgen fahre ich nach Berlin.", "", "Tomorrow I'm going to Berlin."],
    "wenn": ["Ruf mich an, wenn du ankommst.", "", "Call me when you arrive."],
    "nicht": ["Ich verstehe dich nicht.", "", "I don't understand you."],
    "schön": ["Das war sehr schön.", "", "That was very nice."],
    "wollen": ["Was willst du essen?", "", "What do you want to eat?"],
    "sagen": ["Sag mir die Wahrheit.", "", "Tell me the truth."],
    "brauchen": ["Wie viel Zeit brauchst du?", "", "How much time do you need?"],
    "was": ["Ich weiß nicht, was ich sagen soll.", "", "I don't know what to say."],
    "wo": ["Ich weiß nicht, wo er wohnt.", "", "I don't know where he lives."],
    "warum": ["Sag mir, warum du traurig bist.", "", "Tell me why you're sad."],
    "wer": ["Mit wem kommst du?", "", "Who are you coming with?"],
    "Toilette": ["Die Toilette ist rechts.", "", "The toilet is on the right."],
    "wir": ["Kommst du mit uns?", "", "Are you coming with us?"],
    "er": ["Wo ist er?", "", "Where is he?"],
    "sie": ["Ich gehe mit ihr.", "", "I'm going with her."],
    "Essen": ["Wir machen das Essen zusammen.", "", "We're making the food together."],
    "wie viel": ["Wie viel Zeit hast du?", "", "How much time do you have?"],
  },

  // ===========================================================================
  // INDONESIAN
  // ===========================================================================
  id: {
    "Selamat tinggal": ["Dia bilang selamat tinggal", "", "He said goodbye"],
    "Kami": ["Ini rumah kami", "", "This is our house"],
    "Baik": ["Ibu saya orang baik", "", "My mother is a good person"],
    "Apa": ["Saya tidak tahu apa itu", "", "I don't know what that is"],
    "Ibu": ["Saya menelepon ibu", "", "I'm calling my mother"],
    "Ayah": ["Rumah ayah saya besar", "", "My father's house is big"],
    "Satu": ["Satu, dua, tiga", "", "One, two, three"],
    "Dua": ["Saya punya dua saudara", "", "I have two siblings"],
    "Tiga": ["Jam tiga sore", "", "Three in the afternoon"],
    "Air": ["Saya minum air setiap pagi", "", "I drink water every morning"],
    "Makan": ["Kita makan bersama", "", "We eat together"],
    "Minum": ["Mau minum apa?", "", "What would you like to drink?"],
    "Bagus": ["Ini buku yang bagus", "", "This is a good book"],
    "Rumah": ["Saya di rumah sekarang", "", "I'm at home now"],
    "Pergi": ["Kapan kamu pergi?", "", "When are you going?"],
    "Datang": ["Datang ke rumah saya", "", "Come to my house"],
    "Hari ini": ["Saya tidak kerja hari ini", "", "I'm not working today"],
    "Besok": ["Besok saya ke Jakarta", "", "Tomorrow I'm going to Jakarta"],
    "Bilang": ["Bilang sama saya", "", "Tell me"],
    "Mau": ["Kamu mau ke mana?", "", "Where do you want to go?"],
    "Kapan": ["Bilang kapan kamu sampai", "", "Tell me when you arrive"],
    "Kenapa": ["Saya tidak tahu kenapa", "", "I don't know why"],
    "Siapa": ["Kamu datang dengan siapa?", "", "Who are you coming with?"],
    "Permisi": ["Permisi, boleh tanya?", "", "Excuse me, may I ask?"],
    "Berapa": ["Kamu punya berapa saudara?", "", "How many siblings do you have?"],
    "Di mana": ["Saya tidak tahu di mana dia tinggal", "", "I don't know where he lives"],
    "Mengerti": ["Kamu mengerti bahasa Indonesia?", "", "Do you understand Indonesian?"],
    "Sampai jumpa": ["Baiklah, sampai jumpa", "", "All right, see you"],
    "kamu": ["Ini untuk kamu", "", "This is for you"],
    "buruk": ["Hari yang buruk", "", "A bad day"],
    "punya": ["Kamu punya waktu?", "", "Do you have time?"],
    "perlu": ["Berapa banyak yang kamu perlu?", "", "How much do you need?"],
    "berbicara": ["Ibu saya berbicara tiga bahasa", "", "My mother speaks three languages"],
    "kamar kecil": ["Kamar kecil ada di sebelah kanan", "", "The bathroom is on the right"],
  },

  // ===========================================================================
  // TURKISH
  // ===========================================================================
  tr: {
    "Selam": ["Ona selam söyle.", "", "Say hello to him."],
    "Güle güle": ["Annem güle güle dedi.", "", "My mother said goodbye."],
    "Teşekkürler": ["Yardımın için teşekkürler.", "", "Thanks for your help."],
    "Affedersiniz": ["Affedersiniz, geç kaldım.", "", "Sorry, I'm late."],
    "bir": ["Bir, iki, üç.", "", "One, two, three."],
    "iki": ["Saat iki.", "", "It's two o'clock."],
    "üç": ["Üç gün kaldım.", "", "I stayed three days."],
    "anne": ["Anneme telefon ediyorum.", "", "I'm calling my mother."],
    "baba": ["Babamın evi büyük.", "", "My father's house is big."],
    "su": ["Bir bardak su alabilir miyim?", "", "May I have a glass of water?"],
    "gitmek": ["Nereye gitmek istiyorsun?", "", "Where do you want to go?"],
    "gelmek": ["Yarın gelmek ister misin?", "", "Do you want to come tomorrow?"],
    "içmek": ["Ne içmek istersiniz?", "", "What would you like to drink?"],
    "istemek": ["Bir şey ister misin?", "", "Do you want something?"],
    "konuşmak": ["Annem üç dil konuşuyor.", "", "My mother speaks three languages."],
    "güzel": ["Güzel bir gün.", "", "A beautiful day."],
    "iyi": ["İyi bir fikir.", "", "A good idea."],
    "kötü": ["Kötü bir gün geçirdim.", "", "I had a bad day."],
    "bugün": ["Bugün çalışmıyorum.", "", "I'm not working today."],
    "yarın": ["Yarın İstanbul'a gidiyorum.", "", "Tomorrow I'm going to Istanbul."],
    "Ne kadar?": ["Ne kadar zamanın var?", "", "How much time do you have?"],
    "Hesap lütfen": ["Hesap lütfen, acelem var.", "", "The bill please, I'm in a hurry."],
    "Nerede?": ["Nerede buluşuyoruz?", "", "Where are we meeting?"],
    "ben": ["Bu benim için mi?", "", "Is this for me?"],
    "sen": ["Bu senin için.", "", "This is for you."],
    "özür dilerim": ["Çok özür dilerim.", "", "I'm very sorry."],
    "bilmek": ["Nerede olduğunu bilmek istiyorum.", "", "I want to know where he is."],
    "söylemek": ["Bana doğruyu söyle.", "", "Tell me the truth."],
    "yardım": ["Yardımın için teşekkür ederim.", "", "Thank you for your help."],
    "anlamak": ["Seni anlamak istiyorum.", "", "I want to understand you."],
    "ne": ["Ne diyeceğimi bilmiyorum.", "", "I don't know what to say."],
    "nerede": ["Nerede oturduğunu bilmiyorum.", "", "I don't know where he lives."],
    "ne zaman": ["Ne zaman geldiğini söyle.", "", "Tell me when you arrived."],
    "neden": ["Neden üzgün olduğunu bilmiyorum.", "", "I don't know why he's sad."],
    "kim": ["Kiminle geliyorsun?", "", "Who are you coming with?"],
    "isim": ["İsmini buraya yaz.", "", "Write your name here."],
    "tuvalet": ["Tuvalet sağda.", "", "The toilet is on the right."],
    "yiyecek": ["Yiyecek çok güzeldi.", "", "The food was very good."],
    "var": ["Sorun var mı?", "", "Is there a problem?"],
    "ihtiyaç": ["Ne kadar zamana ihtiyacın var?", "", "How much time do you need?"],
    "değil": ["Bu benim evim değil.", "", "This is not my house."],
    "yemek yemek": ["Birlikte yemek yiyelim.", "", "Let's eat together."],
    "biz": ["Bizimle gelir misin?", "", "Will you come with us?"],
    "o": ["Onunla gidiyorum.", "", "I'm going with him."],
  },

  // ===========================================================================
  // NIGERIAN PIDGIN
  // ===========================================================================
  pcm: {
    "Wetin": ["I no sabi wetin e mean", "", "I don't know what it means"],
    "Where": ["I no know where e dey", "", "I don't know where it is"],
    "Fine": ["Dis food fine well well", "", "This food is very good"],
    "Mama": ["Mama dey for house", "", "Mother is at home"],
    "Papa": ["My papa house big", "", "My father's house is big"],
    "One": ["One, two, three", "", "One, two, three"],
    "Two": ["I get two sister", "", "I have two sisters"],
    "Three": ["Na three o'clock", "", "It's three o'clock"],
    "Chop": ["Make we chop together", "", "Let's eat together"],
    "Water": ["I dey drink water every morning", "", "I drink water every morning"],
    "Go": ["Where you wan go?", "", "Where do you want to go?"],
    "Come": ["Come my house tomorrow", "", "Come to my house tomorrow"],
    "Wan": ["Wetin you wan chop?", "", "What do you want to eat?"],
    "Sabi": ["You sabi dis place?", "", "Do you know this place?"],
    "House": ["I dey go house now", "", "I'm going home now"],
    "Good": ["Dis one good well well", "", "This one is very good"],
    "Bad": ["I get bad news", "", "I have bad news"],
    "Today": ["I no dey work today", "", "I'm not working today"],
    "Tomorrow": ["Tomorrow I go Lagos", "", "Tomorrow I'm going to Lagos"],
    "Talk": ["Talk true to me", "", "Tell me the truth"],
    "When": ["Tell me when you go come", "", "Tell me when you'll come"],
    "Why": ["I no sabi why", "", "I don't know why"],
    "Who": ["Who you dey come with?", "", "Who are you coming with?"],
    "Una": ["Dis one na for una", "", "This one is for you all"],
    "yes": ["Yes, I dey come", "", "Yes, I'm coming"],
    "no": ["No, I no fit", "", "No, I can't"],
    "drink": ["Wetin you wan drink?", "", "What do you want to drink?"],
    "get": ["You get time?", "", "Do you have time?"],
    "need": ["How much you need?", "", "How much do you need?"],
    "helep": ["Thank you for your helep", "", "Thank you for your help"],
    "name": ["Write your name here", "", "Write your name here"],
    "toilet": ["Di toilet dey for right side", "", "The toilet is on the right"],
    "no be": ["Dis no be my house", "", "This is not my house"],
    "How much": ["How much time you get?", "", "How much time do you have?"],
  },

  // ===========================================================================
  // ARABIC — Modern Standard, matching the pack. Verbs are listed in the
  // third-person form a dictionary uses, so the second frame conjugates them
  // into a different person as well as moving them.
  // ===========================================================================
  ar: {
    "السلام عليكم": ["قال لي السلام عليكم", "qaala li as-salamu alaykum", "He said hello to me"],
    "أنت": ["هذا لك أنت", "hadha laka anta", "This is for you"],
    "اسم": ["اكتب اسمك هنا", "uktub ismak huna", "Write your name here"],
    "غداً": ["غداً أذهب إلى السوق", "ghadan adhhab ila as-suq", "Tomorrow I'm going to the market"],
    "يقول": ["قل لي الحقيقة", "qul li al-haqiqa", "Tell me the truth"],
    "من": ["مع من تأتي؟", "ma'a man ta'ti?", "Who are you coming with?"],
    "كم": ["كم أخا لديك؟", "kam akhan ladayk?", "How many brothers do you have?"],
    "يحتاج": ["كم من الوقت تحتاج؟", "kam min al-waqt tahtaaj?", "How much time do you need?"],
    "يفهم": ["أريد أن أفهم", "ureed an afham", "I want to understand"],
    "مساعدة": ["شكرا على المساعدة", "shukran ala al-musaada", "Thanks for the help"],
    "تفضل": ["الشاي جاهز، تفضل", "ash-shay jaahiz, tafaddal", "The tea is ready, help yourself"],
    "بخير": ["كل شيء بخير في البيت", "kull shay bi-khayr fi al-bayt", "Everything is fine at home"],
    "أكل": ["نحضر الأكل معا", "nuhaddir al-akl ma'an", "We're preparing the food together"],
    "يساعد": ["أساعد أمي كل يوم", "usa'id ummi kull yawm", "I help my mother every day"],
    "حمام": ["الحمام على اليمين", "al-hammam ala al-yameen", "The bathroom is on the right"],
    "ماذا": ["لا أعرف ماذا أقول", "la a'rif madha aqool", "I don't know what to say"],
    "سيء": ["كان يوما سيئا", "kaana yawman sayyi'an", "It was a bad day"],
    "يأتي": ["أختي تأتي غدا", "ukhti ta'ti ghadan", "My sister is coming tomorrow"],
    "يملك": ["هل تملك وقتا؟", "hal tamlik waqtan?", "Do you have time?"],
    "ليس": ["هذا ليس بيتي", "hadha laysa bayti", "This is not my house"],
    "نحن": ["هل تأتي معنا؟", "hal ta'ti ma'ana?", "Are you coming with us?"],
    "هو": ["أين هو الآن؟", "ayna huwa al-aan?", "Where is he now?"],
    "هي": ["أذهب معها", "adhhab ma'aha", "I'm going with her"],
  },

  // ===========================================================================
  // URDU
  // ===========================================================================
  ur: {
    "ہم": ["کیا آپ ہمارے ساتھ آئیں گے؟", "kya aap humare saath aayenge?", "Will you come with us?"],
    "وہ": ["میں وہاں اس کے ساتھ جاؤں گا", "main wahan uske saath jaunga", "I will go there with him"],
    "کیا": ["مجھے نہیں معلوم کیا کہوں", "mujhe nahin maloom kya kahun", "I don't know what to say"],
    "کون": ["آپ کس کے ساتھ آ رہے ہیں؟", "aap kis ke saath aa rahe hain?", "Who are you coming with?"],
    "آنا": ["میری بہن کل آ رہی ہے", "meri behan kal aa rahi hai", "My sister is coming tomorrow"],
    "پینا": ["میں روز چائے پیتا ہوں", "main roz chai peeta hoon", "I drink tea every day"],
    "بولنا": ["میری ماں تین زبانیں بولتی ہیں", "meri maan teen zabaanen bolti hain", "My mother speaks three languages"],
    "کہاں": ["مجھے نہیں معلوم وہ کہاں رہتا ہے", "mujhe nahin maloom woh kahan rehta hai", "I don't know where he lives"],
    "کتنا": ["آپ کے پاس کتنا وقت ہے؟", "aap ke paas kitna waqt hai?", "How much time do you have?"],
    "مدد": ["آپ کی مدد کے لیے شکریہ", "aap ki madad ke liye shukriya", "Thank you for your help"],
    "چاہنا": ["آپ کیا کھانا چاہتے ہیں؟", "aap kya khaana chahte hain?", "What do you want to eat?"],
    "جاننا": ["میں یہ جگہ نہیں جانتا", "main yeh jagah nahin jaanta", "I don't know this place"],
    "کہنا": ["مجھے سچ کہو", "mujhe sach kaho", "Tell me the truth"],
    "کب": ["بتاؤ تم کب پہنچو گے", "batao tum kab pahuncho ge", "Tell me when you'll arrive"],
    "کیوں": ["مجھے نہیں معلوم کیوں", "mujhe nahin maloom kyun", "I don't know why"],
    "ہونا": ["کیا آپ کے پاس وقت ہے؟", "kya aap ke paas waqt hai?", "Do you have time?"],
    "ضرورت": ["آپ کو کتنی ضرورت ہے؟", "aap ko kitni zaroorat hai?", "How much do you need?"],
    "سمجھنا": ["میں آپ کو سمجھنا چاہتا ہوں", "main aap ko samajhna chahta hoon", "I want to understand you"],
    "نام": ["اپنا نام یہاں لکھیں", "apna naam yahan likhen", "Write your name here"],
    "باتھ روم": ["باتھ روم دائیں طرف ہے", "bathroom daayen taraf hai", "The bathroom is on the right"],
    "برا": ["یہ ایک برا دن تھا", "yeh ek bura din tha", "It was a bad day"],
  },

  // ===========================================================================
  // PERSIAN — the pack's first frames are colloquial, so the second frames are
  // too. Verbs are listed as infinitives and used conjugated, which is the
  // pack's own convention.
  // ===========================================================================
  fa: {
    "تو": ["این برای توئه", "in barâye to'e", "This is for you"],
    "شما": ["با شما می‌آم", "bâ shomâ miâm", "I'll come with you"],
    "او": ["با او حرف زدم", "bâ u harf zadam", "I spoke with him"],
    "ما": ["با ما می‌آی؟", "bâ mâ miâi?", "Are you coming with us?"],
    "اسم": ["اسمت رو اینجا بنویس", "esmet ro injâ benevis", "Write your name here"],
    "مادر": ["به مادرم زنگ می‌زنم", "be mâdaram zang mizanam", "I'm calling my mother"],
    "پدر": ["خانه‌ی پدرم بزرگه", "khâne-ye pedaram bozorge", "My father's house is big"],
    "مامان": ["مامان غذا درست کرد", "mâmân ghazâ dorost kard", "Mum made the food"],
    "بابا": ["با بابا رفتم بازار", "bâ bâbâ raftam bâzâr", "I went to the market with dad"],
    "آب": ["یک لیوان آب بهم بده", "yek livân âb behem bede", "Give me a glass of water"],
    "غذا": ["غذا رو با هم درست می‌کنیم", "ghazâ ro bâ ham dorost mikonim", "We make the food together"],
    "خوردن": ["چی می‌خوای بخوری؟", "chi mikhâi bokhori?", "What do you want to eat?"],
    "رفتن": ["کجا می‌خوای بری؟", "kojâ mikhâi beri?", "Where do you want to go?"],
    "آمدن": ["خواهرم فردا می‌آد", "khâharam fardâ miâd", "My sister is coming tomorrow"],
    "گفتن": ["راستش رو به من بگو", "râstesh ro be man begu", "Tell me the truth"],
    "دانستن": ["می‌خوام بدونم کجاست", "mikhâm bedunam kojâst", "I want to know where it is"],
    "خواستن": ["چقدر می‌خوای؟", "cheghadr mikhâi?", "How much do you want?"],
    "خانه": ["الان خانه‌ام", "alân khâne-am", "I'm at home now"],
    "خوب": ["غذا خیلی خوب بود", "ghazâ kheyli khub bud", "The food was very good"],
    "یک": ["فقط یکی مونده", "faghat yeki munde", "Only one is left"],
    "دو": ["ساعت دوئه", "sâat do'e", "It's two o'clock"],
    "سه": ["سه تا خواهر دارم", "se tâ khâhar dâram", "I have three sisters"],
    "امروز": ["امروز کار نمی‌کنم", "emruz kâr nemikonam", "I'm not working today"],
    "فردا": ["فردا می‌رم تهران", "fardâ miram Tehrân", "Tomorrow I'm going to Tehran"],
    "چی": ["نمی‌دونم چی بگم", "nemidunam chi begam", "I don't know what to say"],
    "کجا": ["نمی‌دونم کجا زندگی می‌کنه", "nemidunam kojâ zendegi mikone", "I don't know where he lives"],
    "کی": ["بگو کی می‌رسی", "begu key miresi", "Tell me when you arrive"],
    "چرا": ["نمی‌دونم چرا", "nemidunam cherâ", "I don't know why"],
    "چند": ["چند تا برادر داری؟", "chand tâ barâdar dâri?", "How many brothers do you have?"],
    "داشتن": ["وقت داری؟", "vaght dâri?", "Do you have time?"],
    "لازم داشتن": ["چقدر وقت لازم داری؟", "cheghadr vaght lâzem dâri?", "How much time do you need?"],
    "کمک کردن": ["هر روز به مادرم کمک می‌کنم", "har ruz be mâdaram komak mikonam", "I help my mother every day"],
    "فهمیدن": ["می‌خوام تو رو بفهمم", "mikhâm to ro befahmam", "I want to understand you"],
    "حرف زدن": ["مادرم سه تا زبان حرف می‌زنه", "mâdaram se tâ zabân harf mizane", "My mother speaks three languages"],
    "بد": ["روز بدی بود", "ruz-e badi bud", "It was a bad day"],
    "بفرمایید": ["چای حاضره، بفرمایید", "chây hâzere, befarmâyid", "The tea is ready, help yourself"],
    "نوشیدن": ["چی می‌خوای بنوشی؟", "chi mikhâi benushi?", "What would you like to drink?"],
    "دستشویی": ["دستشویی سمت راسته", "dastshuyi samt-e râste", "The bathroom is on the right"],
  },

  // ===========================================================================
  // HINDI
  // ===========================================================================
  hi: {
    "एक": ["सिर्फ़ एक बचा है", "sirf ek bacha hai", "Only one is left"],
    "दो": ["दो बज गए", "do baj gaye", "It's two o'clock"],
    "तीन": ["मेरी तीन बहनें हैं", "meri teen bahnein hain", "I have three sisters"],
    "पीना": ["मैं रोज़ चाय पीता हूँ", "main roz chai peeta hoon", "I drink tea every day"],
    "बोलना": ["मेरी माँ तीन भाषाएँ बोलती हैं", "meri maa teen bhaashaayen bolti hain", "My mother speaks three languages"],
    "आना": ["मेरी बहन कल आ रही है", "meri bahan kal aa rahi hai", "My sister is coming tomorrow"],
    "नाम": ["अपना नाम यहाँ लिखिए", "apna naam yahan likhiye", "Write your name here"],
    "जानना": ["मैं यह जगह नहीं जानता", "main yah jagah nahin jaanta", "I don't know this place"],
    "कहना": ["मुझे सच कहो", "mujhe sach kaho", "Tell me the truth"],
    "कब": ["बताओ तुम कब पहुँचोगे", "batao tum kab pahunchoge", "Tell me when you'll arrive"],
    "क्यों": ["मुझे नहीं पता क्यों", "mujhe nahin pata kyun", "I don't know why"],
    "कौन": ["तुम किसके साथ आ रहे हो?", "tum kiske saath aa rahe ho?", "Who are you coming with?"],
    "माफ़ कीजिए": ["माफ़ कीजिए, मुझे देर हो गई", "maaf kijiye, mujhe der ho gayi", "Sorry, I'm late"],
    "मदद": ["आपकी मदद के लिए शुक्रिया", "aapki madad ke liye shukriya", "Thank you for your help"],
    "कितना": ["आपके पास कितना समय है?", "aapke paas kitna samay hai?", "How much time do you have?"],
    "कहाँ": ["मुझे नहीं पता वह कहाँ रहता है", "mujhe nahin pata vah kahan rehta hai", "I don't know where he lives"],
    "क्या": ["मुझे नहीं पता क्या कहूँ", "mujhe nahin pata kya kahun", "I don't know what to say"],
    "चाहिए": ["आपको कितना चाहिए?", "aapko kitna chahiye?", "How much do you need?"],
    "समझना": ["मैं आपको समझना चाहता हूँ", "main aapko samajhna chahta hoon", "I want to understand you"],
    "तुम": ["यह तुम्हारे लिए है", "yah tumhaare liye hai", "This is for you"],
    "होना": ["क्या आपके पास समय है?", "kya aapke paas samay hai?", "Do you have time?"],
    "चाहना": ["तुम क्या खाना चाहते हो?", "tum kya khaana chahte ho?", "What do you want to eat?"],
    "ज़रूरत": ["कितने समय की ज़रूरत है?", "kitne samay ki zaroorat hai?", "How much time do you need?"],
    "बाथरूम": ["बाथरूम दाईं तरफ़ है", "bathroom daayin taraf hai", "The bathroom is on the right"],
    "बुरा": ["वह एक बुरा दिन था", "vah ek bura din tha", "It was a bad day"],
    "हम": ["क्या तुम हमारे साथ आओगे?", "kya tum hamaare saath aaoge?", "Will you come with us?"],
    "वह": ["मैं उसके साथ जा रहा हूँ", "main uske saath ja raha hoon", "I'm going with him"],
  },

  // ===========================================================================
  // BENGALI
  // ===========================================================================
  bn: {
    "নমস্কার": ["তিনি শুধু নমস্কার বললেন", "tini shudhu nomoshkar bollen", "He only said hello"],
    "আসসালামু আলাইকুম": ["দাদা আসসালামু আলাইকুম বললেন", "dada assalamu alaikum bollen", "Grandfather said hello"],
    "পানি": ["আমি রোজ পানি খাই", "ami roj pani khai", "I drink water every day"],
    "খাবার": ["আমরা একসাথে খাবার বানাই", "amra ekshathe khabar banai", "We make the food together"],
    "যাওয়া": ["তুমি কোথায় যেতে চাও?", "tumi kothay jete chao?", "Where do you want to go?"],
    "আসা": ["আমার বোন কাল আসছে", "amar bon kal aashche", "My sister is coming tomorrow"],
    "খাওয়া": ["চলো একসাথে খাই", "cholo ekshathe khai", "Let's eat together"],
    "পান করা": ["তুমি কী পান করতে চাও?", "tumi ki pan korte chao?", "What do you want to drink?"],
    "বলা": ["আমাকে সত্যি বলো", "amake shotti bolo", "Tell me the truth"],
    "বাড়ি": ["আমি এখন বাড়িতে আছি", "ami ekhon barite achi", "I'm at home now"],
    "আজ": ["আমি আজ কাজ করছি না", "ami aaj kaj korchi na", "I'm not working today"],
    "কাল": ["কাল আমি ঢাকা যাব", "kal ami Dhaka jabo", "Tomorrow I'm going to Dhaka"],
    "কোথায়": ["আমি জানি না সে কোথায় থাকে", "ami jani na she kothay thake", "I don't know where he lives"],
    "কত": ["তোমার কত সময় আছে?", "tomar koto shomoy ache?", "How much time do you have?"],
    "সাহায্য": ["তোমার সাহায্যের জন্য ধন্যবাদ", "tomar shahajjer jonno dhonnobad", "Thank you for your help"],
    "ভালো": ["ভালো খবর আছে", "bhalo khobor achhe", "There is good news"],
    "জানা": ["আমি এই জায়গা জানি না", "ami ei jayga jani na", "I don't know this place"],
    "কখন": ["বলো তুমি কখন পৌঁছাবে", "bolo tumi kokhon pouchhabe", "Tell me when you'll arrive"],
    "কেন": ["আমি জানি না কেন", "ami jani na keno", "I don't know why"],
    "মাফ করবেন": ["মাফ করবেন, আমার দেরি হয়ে গেছে", "maaf korben, amar deri hoye gechhe", "Sorry, I'm late"],
    "কি": ["আমি জানি না কি বলব", "ami jani na ki bolbo", "I don't know what to say"],
    "চাই": ["তুমি কী খেতে চাও?", "tumi ki khete chao?", "What do you want to eat?"],
    "খারাপ": ["দিনটা খারাপ ছিল", "dinta kharap chhilo", "It was a bad day"],
    "থাকা": ["তোমার কি সময় আছে?", "tomar ki shomoy ache?", "Do you have time?"],
    "দরকার": ["তোমার কত দরকার?", "tomar koto dorkar?", "How much do you need?"],
    "বোঝা": ["আমি তোমাকে বুঝতে চাই", "ami tomake bujhte chai", "I want to understand you"],
    "নাম": ["এখানে তোমার নাম লেখো", "ekhane tomar nam lekho", "Write your name here"],
    "বাথরুম": ["বাথরুম ডান দিকে", "bathroom dan dike", "The bathroom is on the right"],
  },

  // ===========================================================================
  // PUNJABI — Shahmukhi, matching the pack.
  // ===========================================================================
  pa: {
    "السلام علیکم": ["اوہنے مینوں السلام علیکم آکھیا", "ohne mainu assalam alaikum aakhiya", "He said hello to me"],
    "اللہ حافظ": ["اللہ حافظ، فیر ملاں گے", "Allah hafiz, fer milaan ge", "Goodbye, we'll meet again"],
    "اک": ["بس اک رہ گیا", "bas ik rah gaya", "Only one is left"],
    "دو": ["دو وجے نیں", "do vaje nen", "It's two o'clock"],
    "تن": ["میریاں تن بھیناں نیں", "meriyan tinn bhenaan nen", "I have three sisters"],
    "پانی": ["پانی ٹھنڈا اے", "paani thanda ae", "The water is cold"],
    "روٹی": ["میں روٹی کھاندا ہاں", "main roti khaanda haan", "I eat bread"],
    "کھانا": ["اسیں رل کے کھانا بنائے آں", "asin ral ke khaana banaye aan", "We make the food together"],
    "گھر": ["میں ہُن گھر آں", "main hun ghar aan", "I'm at home now"],
    "اچھا": ["اچھا خیال اے", "achha khayaal ae", "That's a good idea"],
    "ماڑا": ["ایہہ ماڑی گل اے", "eh maadi gall ae", "That's a bad thing"],
    "اج": ["میں اج کم نئیں کردا", "main ajj kamm nahin karda", "I'm not working today"],
    "جانا": ["توں کتھے جانا چاہنا ایں؟", "tun kithe jana chahna ain?", "Where do you want to go?"],
    "آؤنا": ["میری بھین کل آؤندی اے", "meri bhen kal aundi ae", "My sister is coming tomorrow"],
    "جاننا": ["میں ایہہ تھاں نئیں جانناں", "main eh thaan nahin jaanaan", "I don't know this place"],
    "آکھنا": ["مینوں سچ آکھو", "mainu sach aakho", "Tell me the truth"],
    "کدوں": ["دسو تسیں کدوں پہنچو گے", "dasso tusin kadon pahuncho ge", "Tell me when you'll arrive"],
    "کیوں": ["مینوں نئیں پتہ کیوں", "mainu nahin pata kyun", "I don't know why"],
    "کون": ["تسیں کیہدے نال آ رہے او؟", "tusin kehde naal aa rahe o?", "Who are you coming with?"],
    "مہربانی کرکے": ["مہربانی کرکے بہہ جاؤ", "meharbani karke behh jao", "Please sit down"],
    "مدد": ["تہاڈی مدد لئی شکریہ", "tuhadi madad layi shukriya", "Thank you for your help"],
    "چاہیدا": ["تہانوں کِنا چاہیدا اے؟", "tuhanu kinna chahida ae?", "How much do you need?"],
    "کتھے": ["مینوں نئیں پتہ اوہ کتھے رہندا اے", "mainu nahin pata oh kithe rehnda ae", "I don't know where he lives"],
    "کنا": ["تہاڈے کول کِنا ویلا اے؟", "tuhade kol kinna vela ae?", "How much time do you have?"],
    "کی": ["مینوں نئیں پتہ کی آکھاں", "mainu nahin pata ki aakhaan", "I don't know what to say"],
    "بولنا": ["میری ماں تن زباناں بولدی اے", "meri maan tinn zabaanaan boldi ae", "My mother speaks three languages"],
    "چنگا": ["اج چنگا دن سی", "ajj changa din si", "Today was a good day"],
    "پینا": ["میں روز چاہ پیندا ہاں", "main roz chaa peenda haan", "I drink tea every day"],
    "ہونا": ["تہاڈے کول ویلا اے؟", "tuhade kol vela ae?", "Do you have time?"],
    "چاہنا": ["توں کی کھانا چاہنا ایں؟", "tun ki khaana chahna ain?", "What do you want to eat?"],
    "سمجھݨا": ["میں تہانوں سمجھݨا چاہنا واں", "main tuhanu samajhna chahna vaan", "I want to understand you"],
    "نام": ["اپنا نام ایتھے لکھو", "apna naam ithe likho", "Write your name here"],
    "لوڑ": ["مینوں کِنے ویلے دی لوڑ اے", "mainu kinne vele di lorr ae", "How much time do I need"],
    "غسل خانہ": ["غسل خانہ سجے پاسے اے", "ghusal khana sajje paase ae", "The bathroom is on the right"],
  },

  // ===========================================================================
  // JAPANESE — wapuro romanisation throughout, matching the pack's cards.
  // ===========================================================================
  ja: {
    "さようなら": ["先生にさようならを言いました", "sensei ni sayounara o iimashita", "I said goodbye to the teacher"],
    "あなた": ["これはあなたのですか", "kore wa anata no desu ka", "Is this yours?"],
    "来る": ["姉が明日来ます", "ane ga ashita kimasu", "My sister is coming tomorrow"],
    "食べる": ["何を食べたいですか", "nani o tabetai desu ka", "What do you want to eat?"],
    "飲む": ["毎朝お茶を飲みます", "maiasa ocha o nomimasu", "I drink tea every morning"],
    "話す": ["母は三か国語を話します", "haha wa sankakokugo o hanashimasu", "My mother speaks three languages"],
    "家": ["家に帰ります", "ie ni kaerimasu", "I'm going home"],
    "今日": ["今日は働きません", "kyou wa hatarakimasen", "I'm not working today"],
    "明日": ["明日東京に行きます", "ashita Toukyou ni ikimasu", "Tomorrow I'm going to Tokyo"],
    "はは": ["母に電話します", "haha ni denwa shimasu", "I'm calling my mother"],
    "ちち": ["父の家は大きいです", "chichi no ie wa ookii desu", "My father's house is big"],
    "いい": ["いい考えですね", "ii kangae desu ne", "That's a good idea"],
    "ください": ["ここに座ってください", "koko ni suwatte kudasai", "Please sit here"],
    "ごめんなさい": ["遅れてごめんなさい", "okurete gomennasai", "Sorry I'm late"],
    "みず": ["水が冷たいです", "mizu ga tsumetai desu", "The water is cold"],
    "いく": ["どこに行きたいですか", "doko ni ikitai desu ka", "Where do you want to go?"],
    "くる": ["また来てください", "mata kite kudasai", "Please come again"],
    "きょう": ["きょうはいい天気です", "kyou wa ii tenki desu", "The weather is good today"],
    "知る": ["この場所を知りません", "kono basho o shirimasen", "I don't know this place"],
    "言う": ["本当のことを言ってください", "hontou no koto o itte kudasai", "Please tell me the truth"],
    "いつ": ["いつ着くか教えてください", "itsu tsuku ka oshiete kudasai", "Tell me when you arrive"],
    "なぜ": ["なぜ来なかったか分かりません", "naze konakatta ka wakarimasen", "I don't know why he didn't come"],
    "誰": ["誰と来ますか", "dare to kimasu ka", "Who are you coming with?"],
    "どこ": ["彼がどこに住んでいるか知りません", "kare ga doko ni sunde iru ka shirimasen", "I don't know where he lives"],
    "お願いします": ["お茶をお願いします", "ocha o onegaishimasu", "Tea, please"],
    "もう一度お願いします": ["すみません、もう一度お願いします", "sumimasen, mou ichido onegaishimasu", "Sorry, one more time please"],
    "いくらですか": ["この本はいくらですか", "kono hon wa ikura desu ka", "How much is this book?"],
    "これをください": ["じゃあ、これをください", "jaa, kore o kudasai", "Then I'll take this one"],
    "悪い": ["悪い一日でした", "warui ichinichi deshita", "It was a bad day"],
    "食べ物": ["一緒に食べ物を作ります", "issho ni tabemono o tsukurimasu", "We make the food together"],
    "あります": ["時間がありますか", "jikan ga arimasu ka", "Do you have time?"],
    "ほしいです": ["どのくらいほしいですか", "dono kurai hoshii desu ka", "How much do you want?"],
    "必要": ["どのくらい時間が必要ですか", "dono kurai jikan ga hitsuyou desu ka", "How much time do you need?"],
    "手伝います": ["毎日母を手伝います", "mainichi haha o tetsudaimasu", "I help my mother every day"],
    "わかります": ["あなたをわかりたいです", "anata o wakaritai desu", "I want to understand you"],
    "何": ["何を言えばいいか分かりません", "nani o ieba ii ka wakarimasen", "I don't know what to say"],
    "名前": ["ここに名前を書いてください", "koko ni namae o kaite kudasai", "Please write your name here"],
    "トイレ": ["トイレは右です", "toire wa migi desu", "The toilet is on the right"],
    "ない": ["そんなことはない", "sonna koto wa nai", "That's not the case"],
    "私たち": ["私たちと来ますか", "watashitachi to kimasu ka", "Are you coming with us?"],
    "彼": ["今彼はどこですか", "ima kare wa doko desu ka", "Where is he now?"],
    "彼女": ["彼女と行きます", "kanojo to ikimasu", "I'm going with her"],
  },

  // ===========================================================================
  // KOREAN — Revised Romanization, matching the pack's cards.
  // ===========================================================================
  ko: {
    "안녕히 가세요": ["할머니께 안녕히 가세요라고 했어요", "halmeoniikke annyeonghi gaseyorago haesseoyo", "I said goodbye to grandmother"],
    "물": ["물 한 병 주세요", "mul han byeong juseyo", "A bottle of water, please"],
    "밥": ["같이 밥 먹어요", "gachi bap meogeoyo", "Let's eat together"],
    "가다": ["어디에 가고 싶어요?", "eodie gago sipeoyo?", "Where do you want to go?"],
    "오다": ["언니가 내일 와요", "eonniga naeil wayo", "My sister is coming tomorrow"],
    "먹다": ["뭐 먹고 싶어요?", "mwo meokgo sipeoyo?", "What do you want to eat?"],
    "마시다": ["매일 아침 차를 마셔요", "maeil achim chareul masyeoyo", "I drink tea every morning"],
    "집": ["지금 집에 있어요", "jigeum jibe isseoyo", "I'm at home now"],
    "오늘": ["오늘 일 안 해요", "oneul il an haeyo", "I'm not working today"],
    "내일": ["내일 서울에 가요", "naeil Seoure gayo", "Tomorrow I'm going to Seoul"],
    "어디": ["그가 어디 사는지 몰라요", "geuga eodi saneunji mollayo", "I don't know where he lives"],
    "얼마": ["시간이 얼마나 있어요?", "sigani eolmana isseoyo?", "How much time do you have?"],
    "좋아요": ["좋아요, 그렇게 해요", "joayo, geureoke haeyo", "All right, let's do that"],
    "알다": ["이 곳을 몰라요", "i goseul mollayo", "I don't know this place"],
    "필요하다": ["시간이 얼마나 필요해요?", "sigani eolmana piryohaeyo?", "How much time do you need?"],
    "언제": ["언제 도착하는지 말해 주세요", "eonje dochakhaneunji malhae juseyo", "Tell me when you arrive"],
    "왜": ["왜 그런지 몰라요", "wae geureonji mollayo", "I don't know why"],
    "주세요": ["차 한 잔 주세요", "cha han jan juseyo", "A cup of tea, please"],
    "얼마예요": ["이 책은 얼마예요?", "i chaegeun eolmayeyo?", "How much is this book?"],
    "저기요": ["저기요, 화장실이 어디예요?", "jeogiyo, hwajangsiri eodiyeyo?", "Excuse me, where is the toilet?"],
    "이거 주세요": ["그럼 이거 주세요", "geureom igeo juseyo", "Then I'll take this one"],
    "나쁘다": ["나쁜 하루였어요", "nappeun haruyeosseoyo", "It was a bad day"],
    "음식": ["같이 음식을 만들어요", "gachi eumsigeul mandeureoyo", "We make the food together"],
    "있다": ["시간 있어요?", "sigan isseoyo?", "Do you have time?"],
    "원하다": ["얼마나 원해요?", "eolmana wonhaeyo?", "How much do you want?"],
    "돕다": ["매일 어머니를 도와요", "maeil eomeonireul dowayo", "I help my mother every day"],
    "이해하다": ["당신을 이해하고 싶어요", "dangsineul ihaehago sipeoyo", "I want to understand you"],
    "이름": ["여기에 이름을 쓰세요", "yeogie ireumeul sseuseyo", "Write your name here"],
    "화장실": ["화장실은 오른쪽이에요", "hwajangsireun oreunjjogieyo", "The toilet is on the right"],
    "안": ["오늘은 안 바빠요", "oneureun an bappayo", "I'm not busy today"],
    "너": ["이건 너를 위한 거야", "igeon neoreul wihan geoya", "This is for you"],
    "여보세요": ["여보세요, 잘 안 들려요", "yeoboseyo, jal an deullyeoyo", "Hello, I can't hear you well"],
    "그": ["지금 그는 어디예요?", "jigeum geuneun eodiyeyo?", "Where is he now?"],
    "그녀": ["그녀와 같이 가요", "geunyeowa gachi gayo", "I'm going with her"],
  },

  // ===========================================================================
  // CHINESE — pinyin with tone marks, and the sandhi written as it is said.
  // ===========================================================================
  zh: {
    "一": ["只剩一个了", "zhǐ shèng yí ge le", "Only one is left"],
    "二": ["我有二十块钱", "wǒ yǒu èrshí kuài qián", "I have twenty yuan"],
    "三": ["我有三个姐姐", "wǒ yǒu sān ge jiějie", "I have three older sisters"],
    "水": ["我想喝水", "wǒ xiǎng hē shuǐ", "I want to drink water"],
    "去": ["你想去哪里？", "nǐ xiǎng qù nǎlǐ?", "Where do you want to go?"],
    "来": ["我姐姐明天来", "wǒ jiějie míngtiān lái", "My sister is coming tomorrow"],
    "吃": ["你想吃什么？", "nǐ xiǎng chī shénme?", "What do you want to eat?"],
    "喝": ["我每天早上喝茶", "wǒ měitiān zǎoshang hē chá", "I drink tea every morning"],
    "说": ["请说实话", "qǐng shuō shíhuà", "Please tell the truth"],
    "有": ["你有时间吗？", "nǐ yǒu shíjiān ma?", "Do you have time?"],
    "家": ["我现在在家", "wǒ xiànzài zài jiā", "I'm at home now"],
    "今天": ["我今天不工作", "wǒ jīntiān bù gōngzuò", "I'm not working today"],
    "明天": ["明天我去北京", "míngtiān wǒ qù Běijīng", "Tomorrow I'm going to Beijing"],
    "哪里": ["我不知道他住哪里", "wǒ bù zhīdào tā zhù nǎlǐ", "I don't know where he lives"],
    "多少": ["你有多少时间？", "nǐ yǒu duōshao shíjiān?", "How much time do you have?"],
    "帮助": ["谢谢你的帮助", "xièxie nǐ de bāngzhù", "Thank you for your help"],
    "好": ["这个主意很好", "zhège zhǔyi hěn hǎo", "This is a good idea"],
    "想": ["你想喝什么？", "nǐ xiǎng hē shénme?", "What would you like to drink?"],
    "需要": ["你需要多少时间？", "nǐ xūyào duōshao shíjiān?", "How much time do you need?"],
    "什么时候": ["告诉我你什么时候到", "gàosu wǒ nǐ shénme shíhou dào", "Tell me when you arrive"],
    "为什么": ["我不知道为什么", "wǒ bù zhīdào wèishénme", "I don't know why"],
    "请问": ["请问，车站怎么走？", "qǐngwèn, chēzhàn zěnme zǒu?", "Excuse me, how do I get to the station?"],
    "多少钱": ["这本书多少钱？", "zhè běn shū duōshao qián?", "How much is this book?"],
    "洗手间": ["洗手间在右边", "xǐshǒujiān zài yòubian", "The toilet is on the right"],
    "便宜一点": ["太贵了，便宜一点吧", "tài guì le, piányi yìdiǎn ba", "Too expensive, a bit cheaper please"],
    "坏": ["今天是坏的一天", "jīntiān shì huài de yì tiān", "Today was a bad day"],
    "食物": ["我们一起做食物", "wǒmen yìqǐ zuò shíwù", "We make the food together"],
    "明白": ["我想明白你", "wǒ xiǎng míngbai nǐ", "I want to understand you"],
    "房子": ["我父亲的房子很大", "wǒ fùqīn de fángzi hěn dà", "My father's house is big"],
    "名字": ["请在这里写名字", "qǐng zài zhèlǐ xiě míngzi", "Please write your name here"],
  },

  // ===========================================================================
  // TAMIL — spoken forms, matching the pack.
  // ===========================================================================
  ta: {
    "அப்பா": ["அப்பாவோட வீடு பெரிசு", "appavoda veedu perisu", "My father's house is big"],
    "தண்ணி": ["தண்ணி ரொம்ப ஜில்லுனு இருக்கு", "thanni romba jillunu irukku", "The water is very cold"],
    "சாப்பாடு": ["சேர்ந்து சாப்பாடு பண்ணலாம்", "serndhu saappaadu pannalaam", "Let's make the food together"],
    "போ": ["நீங்க எங்க போகணும்?", "neenga enga poganum?", "Where do you want to go?"],
    "வா": ["என் தங்கச்சி நாளைக்கு வராங்க", "en thangachi naalaikku varaanga", "My sister is coming tomorrow"],
    "சாப்பிடு": ["என்ன சாப்பிடணும்?", "enna saappidanum?", "What do you want to eat?"],
    "குடி": ["தினமும் காலையில டீ குடிப்பேன்", "thinamum kaalaiyila tea kudippen", "I drink tea every morning"],
    "சொல்": ["எனக்கு உண்மையை சொல்லுங்க", "enakku unmaiyai sollunga", "Tell me the truth"],
    "தெரியும்": ["இந்த இடம் எனக்கு தெரியும்", "indha idam enakku theriyum", "I know this place"],
    "வேணும்": ["உங்களுக்கு எவ்வளவு வேணும்?", "ungalukku evvalavu venum?", "How much do you need?"],
    "இருக்கு": ["உங்களுக்கு நேரம் இருக்கா?", "ungalukku neram irukka?", "Do you have time?"],
    "உதவு": ["தினமும் அம்மாவுக்கு உதவுவேன்", "thinamum ammavukku udhavuven", "I help my mother every day"],
    "புரியுது": ["உங்களை புரிஞ்சுக்கணும்", "ungalai purinjukkanum", "I want to understand you"],
    "பேசு": ["அம்மா மூணு மொழி பேசுவாங்க", "amma moonu mozhi pesuvaanga", "My mother speaks three languages"],
    "வீடு": ["வீடு பக்கத்துலயே இருக்கு", "veedu pakkathulaye irukku", "The house is nearby"],
    "நல்ல": ["இது ஒரு நல்ல யோசனை", "idhu oru nalla yosanai", "That's a good idea"],
    "மோசம்": ["அது ஒரு மோசமான நாள்", "adhu oru mosamaana naal", "That was a bad day"],
    "ஒன்று": ["ஒன்று மட்டும் மிச்சம்", "ondru mattum micham", "Only one is left"],
    "இரண்டு": ["எனக்கு இரண்டு அக்கா இருக்காங்க", "enakku irandu akka irukkaanga", "I have two older sisters"],
    "மூன்று": ["மணி மூன்று ஆச்சு", "mani moondru aachu", "It's three o'clock"],
    "இன்று": ["இன்னிக்கு நான் வேலைக்கு போகலை", "innikku naan velaikku pogalai", "I'm not going to work today"],
    "நாளை": ["நாளைக்கு சென்னை போறேன்", "naalaikku Chennai poren", "Tomorrow I'm going to Chennai"],
    "என்ன": ["என்ன சொல்றதுன்னு தெரியலை", "enna solradhunnu theriyalai", "I don't know what to say"],
    "எங்கே": ["அவரு எங்க இருக்காருன்னு தெரியலை", "avaru enga irukkaarunnu theriyalai", "I don't know where he is"],
    "எப்போ": ["அவரு எப்போ கிளம்புனாரு?", "avaru eppo kilambunaaru?", "When did he leave?"],
    "ஏன்": ["ஏன்னு எனக்கு தெரியலை", "ennu enakku theriyalai", "I don't know why"],
    "யார்": ["யாரோட வரீங்க?", "yaaroda vareenga?", "Who are you coming with?"],
    "கழிவறை": ["கழிவறை வலது பக்கம் இருக்கு", "kazhivarai valadhu pakkam irukku", "The bathroom is on the right"],
    "எவ்வளவு": ["உங்ககிட்ட எவ்வளவு நேரம் இருக்கு?", "ungakitta evvalavu neram irukku?", "How much time do you have?"],
  },

  // ===========================================================================
  // MALAYALAM
  // ===========================================================================
  ml: {
    "അമ്മ": ["ഞാൻ അമ്മയെ വിളിക്കുന്നു", "njaan ammaye vilikkunnu", "I'm calling my mother"],
    "അച്ഛൻ": ["അച്ഛന്റെ വീട് വലുതാണ്", "achchante veedu valuthaanu", "My father's house is big"],
    "വെള്ളം": ["ഞാൻ ദിവസവും വെള്ളം കുടിക്കും", "njaan divasavum vellam kudikkum", "I drink water every day"],
    "ഭക്ഷണം": ["നമുക്ക് ഒരുമിച്ച് ഭക്ഷണം ഉണ്ടാക്കാം", "namukku orumichu bhakshanam undaakkaam", "Let's make the food together"],
    "പോകുക": ["നിങ്ങൾക്ക് എവിടെ പോകണം?", "ningalkku evide pokanam?", "Where do you want to go?"],
    "വരുക": ["എന്റെ പെങ്ങൾ നാളെ വരും", "ente pengal naale varum", "My sister is coming tomorrow"],
    "കഴിക്കുക": ["എന്ത് കഴിക്കണം?", "enthu kazhikkanam?", "What do you want to eat?"],
    "കുടിക്കുക": ["ഞാൻ എന്നും രാവിലെ ചായ കുടിക്കും", "njaan ennum raavile chaaya kudikkum", "I drink tea every morning"],
    "പറയുക": ["എന്നോട് സത്യം പറയൂ", "ennodu sathyam parayoo", "Tell me the truth"],
    "അറിയുക": ["ഈ സ്ഥലം എനിക്ക് അറിയാം", "ee sthalam enikku ariyaam", "I know this place"],
    "വേണം": ["നിങ്ങൾക്ക് എത്ര വേണം?", "ningalkku ethra venam?", "How much do you need?"],
    "ഉണ്ട്": ["നിങ്ങൾക്ക് സമയമുണ്ടോ?", "ningalkku samayamundo?", "Do you have time?"],
    "സഹായിക്കുക": ["ഞാൻ എന്നും അമ്മയെ സഹായിക്കും", "njaan ennum ammaye sahaayikkum", "I help my mother every day"],
    "മനസ്സിലാകുക": ["നിങ്ങളെ മനസ്സിലാക്കണം", "ningale manassilaakkanam", "I want to understand you"],
    "സംസാരിക്കുക": ["അമ്മ മൂന്ന് ഭാഷ സംസാരിക്കും", "amma moonnu bhaasha samsaarikkum", "My mother speaks three languages"],
    "വീട്": ["ഞങ്ങളുടെ വീട് വലുതാണ്", "njangalude veedu valuthaanu", "Our house is big"],
    "നല്ല": ["അതൊരു നല്ല ആശയമാണ്", "atharu nalla aashayamaanu", "That's a good idea"],
    "മോശം": ["അതൊരു മോശം ദിവസമായിരുന്നു", "atharu mosham divasamaayirunnu", "That was a bad day"],
    "ഒന്ന്": ["ഒന്ന് മാത്രം ബാക്കി", "onnu maathram baakki", "Only one is left"],
    "രണ്ട്": ["എനിക്ക് രണ്ട് ചേച്ചിമാരുണ്ട്", "enikku randu chechimaarundu", "I have two older sisters"],
    "മൂന്ന്": ["മൂന്ന് മണിയായി", "moonnu maniyaayi", "It's three o'clock"],
    "ഇന്ന്": ["ഞാൻ ഇന്ന് ജോലിക്ക് പോകുന്നില്ല", "njaan innu jolikku pokunnilla", "I'm not going to work today"],
    "നാളെ": ["നാളെ ഞാൻ കൊച്ചിക്ക് പോകും", "naale njaan Kochikku pokum", "Tomorrow I'm going to Kochi"],
    "എന്ത്": ["എന്ത് പറയണമെന്ന് അറിയില്ല", "enthu parayanamennu ariyilla", "I don't know what to say"],
    "എവിടെ": ["അവൻ എവിടെ താമസിക്കുന്നെന്ന് അറിയില്ല", "avan evide thaamasikkunnennu ariyilla", "I don't know where he lives"],
    "എപ്പോൾ": ["എപ്പോൾ വരുമെന്ന് പറയൂ", "eppol varumennu parayoo", "Tell me when you'll come"],
    "എന്തുകൊണ്ട്": ["എന്തുകൊണ്ടെന്ന് എനിക്കറിയില്ല", "enthukondennu enikkariyilla", "I don't know why"],
    "ആര്": ["നിങ്ങൾ ആരുടെ കൂടെ വരുന്നു?", "ningal aarude koode varunnu?", "Who are you coming with?"],
    "ഇല്ല": ["ഇന്ന് ജോലി ഇല്ല", "innu joli illa", "There's no work today"],
    "കുളിമുറി": ["കുളിമുറി വലതുവശത്താണ്", "kulimuri valathuvashathaanu", "The bathroom is on the right"],
    "എത്ര": ["നിങ്ങൾക്ക് എത്ര സമയമുണ്ട്?", "ningalkku ethra samayamundu?", "How much time do you have?"],
  },

  // ===========================================================================
  // SOMALI
  // ===========================================================================
  so: {
    "isaga": ["Waxaan la tagayaa isaga.", "", "I'm going with him."],
    "iyada": ["Waan la hadlay iyada.", "", "I spoke with her."],
    "annaga": ["Ma na raacaysaa annaga?", "", "Are you coming with us?"],
    "magac": ["Magaciisu waa Xasan.", "", "His name is Hasan."],
    "hooyo": ["Maalin walba hooyaday waan caawiyaa.", "", "I help my mother every day."],
    "aabbe": ["Guriga aabbahay waa weyn yahay.", "", "My father's house is big."],
    "biyo": ["Biyuhu waa qabow yihiin.", "", "The water is cold."],
    "cunto": ["Cuntada waan wada kariyaa.", "", "We cook the food together."],
    "tag": ["Xaggee baad tegi rabtaa?", "", "Where do you want to go?"],
    "imow": ["Walaashay berri way imanaysaa.", "", "My sister is coming tomorrow."],
    "cun": ["Maxaad cuni rabtaa?", "", "What do you want to eat?"],
    "cab": ["Subax walba shaah baan cabaa.", "", "I drink tea every morning."],
    "dheh": ["Runta ii sheeg.", "", "Tell me the truth."],
    "garo": ["Waan garanayaa meeshan.", "", "I know this place."],
    "rab": ["Immisa baad rabtaa?", "", "How much do you want?"],
    "leeyahay": ["Waqti ma leedahay?", "", "Do you have time?"],
    "caawi": ["Waan ku caawin karaa.", "", "I can help you."],
    "fahan": ["Waan ku fahmi rabaa.", "", "I want to understand you."],
    "hadal": ["Hooyaday saddex luqadood ayay ku hadashaa.", "", "My mother speaks three languages."],
    "guri": ["Gurigu waa dhow yahay.", "", "The house is nearby."],
    "wanaagsan": ["Taasi waa fikrad wanaagsan.", "", "That's a good idea."],
    "xun": ["Maalin xun bay ahayd.", "", "It was a bad day."],
    "kow": ["Kow oo keliya ayaa hadhay.", "", "Only one is left."],
    "laba": ["Laba walaalo ah ayaan leeyahay.", "", "I have two siblings."],
    "saddex": ["Waa saddexdii saacadood.", "", "It is three o'clock."],
    "maanta": ["Maanta ma shaqeeyo.", "", "I'm not working today."],
    "berri": ["Berri waxaan aadayaa Muqdisho.", "", "Tomorrow I'm going to Mogadishu."],
    "maxay": ["Ma garanayo waxay tahay.", "", "I don't know what it is."],
    "xaggee": ["Ma garanayo xaggee uu joogo.", "", "I don't know where he is."],
    "goorma": ["Ii sheeg goorma aad imanayso.", "", "Tell me when you're coming."],
    "maxaad": ["Maxaad u tagtay suuqa?", "", "Why did you go to the market?"],
    "yaa": ["Yaa ku wehelinaya?", "", "Who is coming with you?"],
    "ma": ["Kani ma aha gurigayga.", "", "This is not my house."],
    "Hello": ["Wuxuu igu yidhi hello.", "", "He said hello to me."],
    "Raali ahow": ["Raali ahow, ma fahmin.", "", "Sorry, I didn't understand."],
    "u baahan": ["Immisa waqti ayaad u baahan tahay?", "", "How much time do you need?"],
    "musqusha": ["Musqushu waa midigta.", "", "The bathroom is on the right."],
    "immisa": ["Immisa saacadood ayaad haysaa?", "", "How many hours do you have?"],
  },

  // ===========================================================================
  // TAGALOG
  // ===========================================================================
  tl: {
    "ako": ["Kasama ako ni Juan.", "", "I'm with Juan."],
    "ikaw": ["Para sa iyo ito.", "", "This is for you."],
    "siya": ["Pupunta ako kasama siya.", "", "I'm going with him."],
    "kami": ["Sasama ka ba sa amin?", "", "Will you come with us?"],
    "tayo": ["Kumain na tayo.", "", "Let's eat now."],
    "pangalan": ["Isulat mo ang pangalan mo dito.", "", "Write your name here."],
    "nanay": ["Tinatawagan ko ang nanay ko.", "", "I'm calling my mother."],
    "tatay": ["Malaki ang bahay ng tatay ko.", "", "My father's house is big."],
    "tubig": ["Malamig ang tubig.", "", "The water is cold."],
    "pagkain": ["Magluto tayo ng pagkain.", "", "Let's cook the food."],
    "kumain": ["Ano ang gusto mong kainin?", "", "What do you want to eat?"],
    "uminom": ["Umiinom ako ng tsaa tuwing umaga.", "", "I drink tea every morning."],
    "pumunta": ["Saan ka gustong pumunta?", "", "Where do you want to go?"],
    "magsalita": ["Tatlong wika ang sinasalita ng nanay ko.", "", "My mother speaks three languages."],
    "maintindihan": ["Gusto kitang maintindihan.", "", "I want to understand you."],
    "tumulong": ["Tumutulong ako sa nanay ko araw-araw.", "", "I help my mother every day."],
    "bahay": ["Malapit lang ang bahay.", "", "The house is nearby."],
    "isa": ["Isa na lang ang natira.", "", "Only one is left."],
    "dalawa": ["May dalawa akong kapatid.", "", "I have two siblings."],
    "tatlo": ["Alas-tres na.", "", "It's three o'clock."],
    "ngayon": ["Hindi ako nagtatrabaho ngayon.", "", "I'm not working today."],
    "bukas": ["Bukas pupunta ako sa Cebu.", "", "Tomorrow I'm going to Cebu."],
    "ano": ["Hindi ko alam kung ano ang sasabihin.", "", "I don't know what to say."],
    "saan": ["Hindi ko alam kung saan siya nakatira.", "", "I don't know where he lives."],
    "sino": ["Sino ang kasama mo?", "", "Who are you with?"],
    "bakit": ["Hindi ko alam kung bakit.", "", "I don't know why."],
    "kailan": ["Sabihin mo kung kailan ka darating.", "", "Tell me when you'll arrive."],
    "magkano": ["Magkano ang librong ito?", "", "How much is this book?"],
    "dumating": ["Darating ang kapatid ko bukas.", "", "My sibling is arriving tomorrow."],
    "magkaroon": ["Gusto kong magkaroon ng oras.", "", "I want to have time."],
    "gusto": ["Ano ang gusto mong inumin?", "", "What do you want to drink?"],
    "alam": ["Hindi ko alam ang lugar na ito.", "", "I don't know this place."],
    "sabihin": ["Sabihin mo ang totoo.", "", "Tell the truth."],
    "kailangan": ["Gaano karaming oras ang kailangan mo?", "", "How much time do you need?"],
    "masama": ["Masamang araw iyon.", "", "That was a bad day."],
    "banyo": ["Nasa kanan ang banyo.", "", "The bathroom is on the right."],
  },
};
