// =============================================================================
// translit-ko.mjs (v92) — Revised Romanization for every Korean example.
//
// 178 of 189 example sentences had none. Hangul is the most learnable script in
// this app — genuinely a morning's work — but the learner meets these sentences
// on day one, before the script course, and had no way to say any of them.
//
// Conventions follow the eleven that already had it:
//   · Revised Romanization (the official system), not McCune-Reischauer
//   · particles hyphenated off the noun: -neun, -eun, -i, -ga, -eul, -reul, -e,
//     -ro, -yeyo, -ieyo — so the learner can see where the word stops
//   · liaison applied across the syllable break, as it is actually said:
//     할아버지 is harabeoji, 살아요 is sarayo, 알아요 is arayo
//   · proper nouns capitalised
//   · h kept in aspirated clusters (jalhaeyo, ganghaeyo) rather than collapsed
//     to a bare k/t, because the learner needs to see the 하 that is still there
// =============================================================================

export const KO = {
  "안녕하세요 친구": "annyeonghaseyo chingu",
  "안녕하세요, 반갑습니다": "annyeonghaseyo, bangapseumnida",
  "안녕 친구": "annyeong chingu",
  "정말 감사합니다": "jeongmal gamsahamnida",
  "네 맞아요": "ne majayo",
  "아니요 괜찮아요": "aniyo gwaenchanayo",
  "안녕히 가세요": "annyeonghi gaseyo",
  "정말 죄송합니다": "jeongmal joesonghamnida",
  "죄송합니다, 늦었어요": "joesonghamnida, neujeosseoyo",
  "실례합니다 어디예요": "sillyehamnida eodi-yeyo",
  "저는 학생이에요": "jeo-neun haksaeng-ieyo",
  "나도": "na-do",
  "나도 가요": "na-do gayo",
  "당신은 누구예요": "dangsin-eun nugu-yeyo",
  "당신은 어디에서 왔어요?": "dangsin-eun eodi-eseo wasseoyo?",
  "우리 친구": "uri chingu",
  "이것은 책이에요": "igeos-eun chaeg-ieyo",
  "이것은 무엇이에요": "igeos-eun mueos-ieyo",
  "저 사람은 누구예요": "jeo saram-eun nugu-yeyo",
  "우리 어머니": "uri eomeoni",
  "어머니는 요리를 잘해요": "eomeoni-neun yori-reul jalhaeyo",
  "우리 아버지": "uri abeoji",
  "아버지는 일해요": "abeoji-neun ilhaeyo",
  "우리 형": "uri hyeong",
  "우리 누나": "uri nuna",
  "제 친구": "je chingu",
  "작은 아이": "jageun ai",
  "하나 둘 셋": "hana dul set",
  "두 사람": "du saram",
  "셋 중에": "set jung-e",
  "네 시간": "ne sigan",
  "다섯 명": "daseot myeong",
  "열 시": "yeol si",
  "백 명": "baek myeong",
  "백 원": "baek won",
  "물 한 잔": "mul han jan",
  "밥 먹어요": "bap meogeoyo",
  "신선한 빵": "sinseonhan ppang",
  "커피 한 잔": "keopi han jan",
  "따뜻한 우유": "ttatteutan uyu",
  "신선한 고기": "sinseonhan gogi",
  "맛있는 김치": "masinneun gimchi",
  "녹차": "nokcha",
  "차로 가요": "cha-ro gayo",
  "학교에 가다": "hakgyo-e gada",
  "내일 오다": "naeil oda",
  "밥을 먹다": "bab-eul meokda",
  "물을 마시다": "mul-eul masida",
  "영화를 보다": "yeonghwa-reul boda",
  "한국어를 말하다": "hangug-eo-reul malhada",
  "뭐라고 말했어요?": "mworago malhaesseoyo?",
  "공부를 하다": "gongbu-reul hada",
  "책을 읽다": "chaeg-eul ikda",
  "우리 집": "uri jip",
  "학교에 가요": "hakgyo-e gayo",
  "큰 도시": "keun dosi",
  "작은 가게": "jageun gage",
  "좋은 식당": "joeun sikdang",
  "오늘은 월요일": "oneur-eun woryoil",
  "내일 봐요": "naeil bwayo",
  "지금 가요": "jigeum gayo",
  "하루 종일": "haru jong-il",
  "늦은 밤": "neujeun bam",
  "좋은 아침": "joeun achim",
  "너 그리고 나": "neo geurigo na",
  "하지만 어려워요": "hajiman eoryeowoyo",
  "왜냐하면 바빠요": "waenyahamyeon bappayo",
  "커피 또는 차": "keopi ttoneun cha",
  "나도 또": "na-do tto",
  "어디예요": "eodi-yeyo",
  "얼마예요": "eolma-yeyo",
  "도와주세요": "dowajuseyo",
  "좋은 호텔": "joeun hotel",
  "정말 좋아요": "jeongmal joayo",
  "많이 감사해요": "mani gamsahaeyo",
  "큰 집": "keun jip",
  "작은 강아지": "jageun gang-aji",
  "내 머리": "nae meori",
  "오른손": "oreunson",
  "큰 눈": "keun nun",
  "눈이 와요": "nun-i wayo",
  "배고파요": "baegopayo",
  "피곤해요": "pigonhaeyo",
  "오늘 피곤해요": "oneul pigonhaeyo",
  "매우 행복해요": "maeu haengbokhaeyo",
  "밝은 해": "balgeun hae",
  "비가 와요": "bi-ga wayo",
  "검은 구름": "geomeun gureum",
  "시원한 바람": "siwonhan baram",
  "바람이 강해요": "baram-i ganghaeyo",
  "파란 하늘": "paran haneul",
  "버스가 와요": "beoseu-ga wayo",
  "빠른 기차": "ppareun gicha",
  "오른쪽으로": "oreunjjog-euro",
  "오른쪽에 있어요": "oreunjjog-e isseoyo",
  "왼쪽으로": "oenjjog-euro",
  "왼쪽으로 가세요": "oenjjog-euro gaseyo",
  "여기로 와요": "yeogi-ro wayo",
  "거기로 가요": "geogi-ro gayo",
  "옷을 사다": "os-eul sada",
  "집을 팔다": "jib-eul palda",
  "소금 조금": "sogeum jogeum",
  "설탕 커피": "seoltang keopi",
  "빨리 와요": "ppalli wayo",
  "저는 알아요": "jeo-neun arayo",
  "저는 생각해요": "jeo-neun saenggakhaeyo",
  "주세요": "juseyo",
  "이것을 받아요": "igeos-eul badayo",
  "음악을 들어요": "eumag-eul deureoyo",
  "물이 필요해요": "mul-i piryohaeyo",
  "제 마음": "je maeum",
  "검정 커피": "geomjeong keopi",
  "하양 빵": "hayang ppang",
  "노랑 꽃": "norang kkot",
  "올해": "olhae",
  "이번 주": "ibeon ju",
  "언제 와요?": "eonje wayo?",
  "왜 안 와요?": "wae an wayo?",
  "저는 자요": "jeo-neun jayo",
  "물 주세요": "mul juseyo",
  "늦어서 미안해요": "neujeoseo mianhaeyo",
  "미안해요, 몰랐어요": "mianhaeyo, mollasseoyo",
  "저는 몰라요": "jeo-neun mollayo",
  "네, 알아요": "ne, arayo",
  "이거 얼마예요?": "igeo eolma-yeyo?",
  "화장실 어디예요?": "hwajangsil eodi-yeyo?",
  "저기요, 메뉴 주세요": "jeogiyo, menyu juseyo",
  "괜찮아요, 감사합니다": "gwaenchanayo, gamsahamnida",
  "이거 주세요": "igeo juseyo",
  "— 감사합니다. — 천만에요": "— gamsahamnida. — cheonman-eyo",
  "이게 뭐예요?": "ige mwo-yeyo?",
  "영어 할 수 있어요?": "yeong-eo hal su isseoyo?",
  "잠깐만요": "jamkkanmanyo",
  "날씨가 나빠요": "nalssi-ga nappayo",
  "음식이 맛있어요": "eumsig-i masisseoyo",
  "시간이 없어요": "sigan-i eopseoyo",
  "물을 원해요": "mul-eul wonhaeyo",
  "차를 만들어요": "cha-reul mandeureoyo",
  "도와줄 수 있어요?": "dowajul su isseoyo?",
  "이해 못 했어요": "ihae mot haesseoyo",
  "돈이 없어요": "don-i eopseoyo",
  "시간이 있어요?": "sigan-i isseoyo?",
  "어제 추웠어요": "eoje chuwosseoyo",
  "어떻게 가요?": "eotteoke gayo?",
  "저 남자는 제 형이에요": "jeo namja-neun je hyeong-ieyo",
  "저 여자는 의사예요": "jeo yeoja-neun uisa-yeyo",
  "이 길은 길어요": "i gir-eun gireoyo",
  "일이 많아요": "il-i manayo",
  "가격이 얼마예요?": "gagyeog-i eolma-yeyo?",
  "문을 열어 주세요": "mun-eul yeoreo juseyo",
  "오늘 더워요": "oneul deowoyo",
  "오늘 추워요": "oneul chuwoyo",
  "조금 더": "jogeum deo",
  "아주 좋아요": "aju joayo",
  "같이 가요": "gachi gayo",
  "설탕 없이": "seoltang eopsi",
  "모두 좋아요": "modu joayo",
  "여기서 가까워요": "yeogiseo gakkawoyo",
  "너무 멀어요": "neomu meoreoyo",
  "이름이 뭐예요?": "ireum-i mwo-yeyo?",
  "아파요": "apayo",
  "의사가 필요해요": "uisa-ga piryohaeyo",
  "화장실이 어디예요?": "hwajangsir-i eodi-yeyo?",
  "그의 아들은 일곱 살이에요": "geu-ui adeur-eun ilgop sar-ieyo",
  "제 딸은 학교에 가요": "je ttal-eun hakgyo-e gayo",
  "여덟 명": "yeodeol myeong",
  "아홉 시": "ahop si",
  "산에 가요": "san-e gayo",
  "안 가요": "an gayo",
  "아주 기뻐요": "aju gippeoyo",
  "슬퍼 보여요": "seulpeo boyeoyo",
  "너 어디야?": "neo eodiya?",
  "여보세요, 누구세요?": "yeoboseyo, nuguseyo?",
  "왼쪽으로 도세요": "oenjjog-euro doseyo",
  "오른쪽으로 가세요": "oreunjjog-euro gaseyo",
  "커피가 뜨거워요": "keopi-ga tteugeowoyo",
  "물이 차가워요": "mul-i chagawoyo",
};
