// =============================================================================
// translit-ja.mjs (v92) — romaji for every Japanese example sentence.
//
// 149 of 157 had none. Japanese is the worst case in the app: the sentences mix
// three scripts, and kanji readings cannot be worked out from the characters, so
// a learner who has just met 母 as "haha" sees 母は料理が上手です and can decode
// exactly one character of it.
//
// Conventions follow the eight that already had romaji:
//   · modified Hepburn with macrons — kyō, arigatō, gakkō, kōhī
//   · particles written as they are SAID, not as they are spelt:
//     は → wa, を → o, へ → e
//   · particles spaced off, so the learner can see the grammar
//   · long vowels from えい stay ei (gakusei, eiga), which is Hepburn's rule and
//     also how it is actually pronounced
//   · names capitalised (Tanaka, Tōkyō)
// =============================================================================

export const JA = {
  "こんにちは 田中さん": "konnichiwa Tanaka-san",
  "ありがとう ございます": "arigatō gozaimasu",
  "はい そうです": "hai sō desu",
  "いいえ 違います": "iie chigaimasu",
  "さようなら また明日": "sayōnara mata ashita",
  "おはよう ございます": "ohayō gozaimasu",
  "すみません 駅は どこですか": "sumimasen eki wa doko desu ka",
  "私は 学生です": "watashi wa gakusei desu",
  "あなたは": "anata wa",
  "私の 母": "watashi no haha",
  "母は料理が上手です": "haha wa ryōri ga jōzu desu",
  "私の 父": "watashi no chichi",
  "父は毎日働きます": "chichi wa mainichi hatarakimasu",
  "私の 兄": "watashi no ani",
  "兄は東京にいます": "ani wa Tōkyō ni imasu",
  "私の 姉": "watashi no ane",
  "姉は医者です": "ane wa isha desu",
  "私の 友達": "watashi no tomodachi",
  "彼は友達です": "kare wa tomodachi desu",
  "水を ください": "mizu o kudasai",
  "ご飯を 食べる": "gohan o taberu",
  "お茶を どうぞ": "ocha o dōzo",
  "新鮮な 魚": "shinsen na sakana",
  "肉が 好き": "niku ga suki",
  "パンを 食べる": "pan o taberu",
  "一つ": "hitotsu",
  "二人": "futari",
  "三日": "mikka",
  "十円": "jūen",
  "十分": "juppun",
  "百円": "hyakuen",
  "学校に 行く": "gakkō ni iku",
  "明日 来る": "ashita kuru",
  "水を 飲む": "mizu o nomu",
  "日本語を 話す": "nihongo o hanasu",
  "映画を 見る": "eiga o miru",
  "勉強を する": "benkyō o suru",
  "私の 家": "watashi no ie",
  "学校へ 行く": "gakkō e iku",
  "駅で 待つ": "eki de matsu",
  "駅はどこですか": "eki wa doko desu ka",
  "今日は 月曜日": "kyō wa getsuyōbi",
  "また 明日": "mata ashita",
  "今 すぐ": "ima sugu",
  "私の母": "watashi no haha",
  "私の父": "watashi no chichi",
  "私の姉": "watashi no ane",
  "私の兄": "watashi no ani",
  "とても嬉しい": "totemo ureshii",
  "疲れた": "tsukareta",
  "とてもいい": "totemo ii",
  "水をください": "mizu o kudasai",
  "ごめんなさい": "gomen nasai",
  "大きい家": "ōkii ie",
  "小さい猫": "chiisai neko",
  "ここに来て": "koko ni kite",
  "そこに行く": "soko ni iku",
  "冷たい水": "tsumetai mizu",
  "緑茶": "ryokucha",
  "牛乳をください": "gyūnyū o kudasai",
  "家に行く": "ie ni iku",
  "ここに来る": "koko ni kuru",
  "今日は月曜日": "kyō wa getsuyōbi",
  "知っています": "shitte imasu",
  "そう思います": "sō omoimasu",
  "彼が言います": "kare ga iimasu",
  "あげます": "agemasu",
  "音楽を聞きます": "ongaku o kikimasu",
  "私の頭": "watashi no atama",
  "私の手": "watashi no te",
  "私の心": "watashi no kokoro",
  "黒いコーヒー": "kuroi kōhī",
  "白いパン": "shiroi pan",
  "黄色い花": "kiiroi hana",
  "明るい太陽": "akarui taiyō",
  "雨が降ります": "ame ga furimasu",
  "今年": "kotoshi",
  "今週": "konshū",
  "一時間": "ichijikan",
  "いつ来ますか": "itsu kimasu ka",
  "なぜですか": "naze desu ka",
  "誰ですか": "dare desu ka",
  "どこですか": "doko desu ka",
  "寝ます": "nemasu",
  "起きます": "okimasu",
  "本を買います": "hon o kaimasu",
  "水をお願いします": "mizu o onegai shimasu",
  "すみません、わかりません": "sumimasen, wakarimasen",
  "はい、わかりました": "hai, wakarimashita",
  "もう一度お願いします": "mō ichido onegai shimasu",
  "これはいくらですか": "kore wa ikura desu ka",
  "すみません、トイレはどこですか": "sumimasen, toire wa doko desu ka",
  "これは何ですか": "kore wa nan desu ka",
  "これをください": "kore o kudasai",
  "ちょっと待ってください": "chotto matte kudasai",
  "大丈夫です、ありがとう": "daijōbu desu, arigatō",
  "英語を話せますか": "eigo o hanasemasu ka",
  "ゆっくり話してください": "yukkuri hanashite kudasai",
  "助けてください": "tasukete kudasai",
  "元気ですか — 元気です": "genki desu ka — genki desu",
  "天気が悪いです": "tenki ga warui desu",
  "食べ物がおいしいです": "tabemono ga oishii desu",
  "時間がありません": "jikan ga arimasen",
  "水がほしいです": "mizu ga hoshii desu",
  "お茶を作ります": "ocha o tsukurimasu",
  "手伝えますか": "tetsudaemasu ka",
  "助けが必要です": "tasuke ga hitsuyō desu",
  "電車を取ります": "densha o torimasu",
  "手伝ってください": "tetsudatte kudasai",
  "わかりません": "wakarimasen",
  "お金がありません": "okane ga arimasen",
  "いい日ですね": "ii hi desu ne",
  "昨日は寒かったです": "kinō wa samukatta desu",
  "どうやって使いますか": "dōyatte tsukaimasu ka",
  "あの男の人は兄です": "ano otoko no hito wa ani desu",
  "あの女の人は医者です": "ano onna no hito wa isha desu",
  "この町は静かです": "kono machi wa shizuka desu",
  "車で行きます": "kuruma de ikimasu",
  "道が長いです": "michi ga nagai desu",
  "仕事が忙しいです": "shigoto ga isogashii desu",
  "ドアを開けてください": "doa o akete kudasai",
  "今日は暑いです": "kyō wa atsui desu",
  "今日は寒いです": "kyō wa samui desu",
  "とてもいいです": "totemo ii desu",
  "小さいでもきれいです": "chiisai demo kirei desu",
  "雨だから行きません": "ame dakara ikimasen",
  "左に曲がります": "hidari ni magarimasu",
  "右にあります": "migi ni arimasu",
  "お名前は何ですか": "onamae wa nan desu ka",
  "病気です": "byōki desu",
  "医者が必要です": "isha ga hitsuyō desu",
  "トイレはどこですか": "toire wa doko desu ka",
  "息子は七歳です": "musuko wa nanasai desu",
  "娘は学校に行きます": "musume wa gakkō ni ikimasu",
  "八人です": "hachinin desu",
  "九時です": "kuji desu",
  "駅は近いです": "eki wa chikai desu",
  "七時に会いましょう": "shichiji ni aimashō",
  "値段はいくらですか": "nedan wa ikura desu ka",
  "もっとください": "motto kudasai",
  "パンとコーヒー": "pan to kōhī",
  "砂糖なしで": "satō nashi de",
  "お茶かコーヒー": "ocha ka kōhī",
  "時間がない": "jikan ga nai",
  "全部ください": "zenbu kudasai",
  "駅は遠いですか": "eki wa tōi desu ka",
  "悲しそうです": "kanashisō desu",
};
