// =============================================================================
// translit-zh.mjs (v92) — pinyin for every Mandarin example sentence.
//
// 163 of 173 example sentences had no transliteration at all. The vocabulary
// entries each carried pinyin, so a learner could say the WORD — and then met it
// inside a sentence written entirely in characters they cannot read, with no way
// to sound out a single one.
//
// Conventions follow the ten sentences that already had pinyin:
//   · tone marks, not tone numbers
//   · words spaced, not syllables
//   · proper nouns capitalised (Zhōngguó, Běijīng)
//   · neutral tone where the language actually neutralises it (xièxie, māma,
//     péngyǒu → péngyou is also seen; the existing data uses péngyǒu, kept)
//
// Tone sandhi IS marked on 不 and 一, because the learner has to say it that
// way: 不是 is bú shì, not bù shì. Textbooks split on this; marking it is the
// choice that helps someone reading the line out loud.
// =============================================================================

export const ZH = {
  "你好朋友": "nǐ hǎo péngyǒu",
  "非常谢谢": "fēicháng xièxie",
  "是的": "shì de",
  "不是": "bú shì",
  "明天再见": "míngtiān zàijiàn",
  "对不起，我迟到了": "duìbùqǐ, wǒ chídào le",
  "请坐": "qǐng zuò",
  "早安朋友": "zǎo'ān péngyǒu",
  "我是学生": "wǒ shì xuéshēng",
  "你好吗": "nǐ hǎo ma",
  "他是医生": "tā shì yīshēng",
  "她是老师": "tā shì lǎoshī",
  "我们是朋友": "wǒmen shì péngyǒu",
  "这是什么": "zhè shì shénme",
  "他是谁": "tā shì shéi",
  "我的妈妈": "wǒ de māma",
  "我妈妈做饭很好": "wǒ māma zuò fàn hěn hǎo",
  "我的爸爸": "wǒ de bàba",
  "我爸爸工作很忙": "wǒ bàba gōngzuò hěn máng",
  "我的哥哥": "wǒ de gēge",
  "我的姐姐": "wǒ de jiějie",
  "好朋友": "hǎo péngyǒu",
  "小孩子": "xiǎo háizi",
  "一个人": "yí ge rén",
  "二月": "èr yuè",
  "三天": "sān tiān",
  "四小时": "sì xiǎoshí",
  "五分钟": "wǔ fēnzhōng",
  "十块钱": "shí kuài qián",
  "一百": "yìbǎi",
  "一百块": "yìbǎi kuài",
  "一杯水": "yì bēi shuǐ",
  "中国茶": "Zhōngguó chá",
  "吃米饭": "chī mǐfàn",
  "牛肉面条": "niúròu miàntiáo",
  "热牛奶": "rè niúnǎi",
  "一杯咖啡": "yì bēi kāfēi",
  "煮鸡蛋": "zhǔ jīdàn",
  "鸡肉": "jīròu",
  "我去家": "wǒ qù jiā",
  "明天来": "míngtiān lái",
  "吃饭": "chī fàn",
  "喝水": "hē shuǐ",
  "说中文": "shuō Zhōngwén",
  "看电影": "kàn diànyǐng",
  "做饭": "zuò fàn",
  "我有一本书": "wǒ yǒu yì běn shū",
  "我在家": "wǒ zài jiā",
  "我的家": "wǒ de jiā",
  "去学校": "qù xuéxiào",
  "大城市": "dà chéngshì",
  "小商店": "xiǎo shāngdiàn",
  "中国饭店": "Zhōngguó fàndiàn",
  "今天星期一": "jīntiān xīngqīyī",
  "明天见": "míngtiān jiàn",
  "现在几点": "xiànzài jǐ diǎn",
  "早上好": "zǎoshang hǎo",
  "晚上好": "wǎnshang hǎo",
  "今年": "jīnnián",
  "这个月": "zhège yuè",
  "你和我": "nǐ hé wǒ",
  "但是很难": "dànshì hěn nán",
  "因为我累了": "yīnwèi wǒ lèi le",
  "茶或者咖啡": "chá huòzhě kāfēi",
  "我也是": "wǒ yě shì",
  "你在哪里": "nǐ zài nǎlǐ",
  "多少钱": "duōshao qián",
  "我需要帮助": "wǒ xūyào bāngzhù",
  "好酒店": "hǎo jiǔdiàn",
  "很好": "hěn hǎo",
  "很多": "hěn duō",
  "大房子": "dà fángzi",
  "小狗": "xiǎo gǒu",
  "我的头": "wǒ de tóu",
  "右手": "yòushǒu",
  "大眼睛": "dà yǎnjīng",
  "我饿了": "wǒ è le",
  "我很累": "wǒ hěn lèi",
  "很高兴": "hěn gāoxìng",
  "别难过": "bié nánguò",
  "大太阳": "dà tàiyáng",
  "下雨了": "xià yǔ le",
  "黑云": "hēi yún",
  "凉风": "liáng fēng",
  "风很大": "fēng hěn dà",
  "蓝天空": "lán tiānkōng",
  "快车": "kuài chē",
  "公共汽车来了": "gōnggòng qìchē lái le",
  "快火车": "kuài huǒchē",
  "向右": "xiàng yòu",
  "在右边": "zài yòubiān",
  "向左": "xiàng zuǒ",
  "往左转": "wǎng zuǒ zhuǎn",
  "来这里": "lái zhèlǐ",
  "去那里": "qù nàlǐ",
  "买衣服": "mǎi yīfu",
  "卖房子": "mài fángzi",
  "少盐": "shǎo yán",
  "加糖": "jiā táng",
  "快来": "kuài lái",
  "我知道": "wǒ zhīdào",
  "我不知道": "wǒ bù zhīdào",
  "我想你": "wǒ xiǎng nǐ",
  "给我": "gěi wǒ",
  "拿这个": "ná zhège",
  "听音乐": "tīng yīnyuè",
  "我需要水": "wǒ xūyào shuǐ",
  "我喜欢咖啡": "wǒ xǐhuan kāfēi",
  "我的心": "wǒ de xīn",
  "黑咖啡": "hēi kāfēi",
  "白米饭": "bái mǐfàn",
  "黄色的太阳": "huángsè de tàiyáng",
  "这个星期": "zhège xīngqī",
  "一个小时": "yí ge xiǎoshí",
  "什么时候来？": "shénme shíhou lái?",
  "为什么不？": "wèishénme bù?",
  "我要睡觉": "wǒ yào shuìjiào",
  "请问，洗手间在哪里？": "qǐngwèn, xǐshǒujiān zài nǎlǐ?",
  "这个多少钱？": "zhège duōshao qián?",
  "车站在哪里？": "chēzhàn zài nǎlǐ?",
  "洗手间在哪里？": "xǐshǒujiān zài nǎlǐ?",
  "对不起，我听不懂": "duìbùqǐ, wǒ tīng bu dǒng",
  "没关系": "méi guānxi",
  "请再说一遍": "qǐng zài shuō yí biàn",
  "请慢点儿说": "qǐng màn diǎnr shuō",
  "可以便宜一点吗？": "kěyǐ piányi yìdiǎn ma?",
  "我要这个，谢谢": "wǒ yào zhège, xièxie",
  "你会说英文吗？": "nǐ huì shuō Yīngwén ma?",
  "请帮我一下": "qǐng bāng wǒ yíxià",
  "这是什么？": "zhè shì shénme?",
  "天气很坏": "tiānqì hěn huài",
  "食物很好吃": "shíwù hěn hǎochī",
  "你能帮我吗？": "nǐ néng bāng wǒ ma?",
  "我不明白": "wǒ bù míngbai",
  "我没有钱": "wǒ méiyǒu qián",
  "我没有时间": "wǒ méiyǒu shíjiān",
  "今天是好天": "jīntiān shì hǎo tiān",
  "昨天很冷": "zuótiān hěn lěng",
  "这个怎么用？": "zhège zěnme yòng?",
  "那个男人是我哥哥": "nàge nánrén shì wǒ gēge",
  "那个女人是医生": "nàge nǚrén shì yīshēng",
  "房子很大": "fángzi hěn dà",
  "这条路很长": "zhè tiáo lù hěn cháng",
  "我的工作很忙": "wǒ de gōngzuò hěn máng",
  "价格是多少？": "jiàgé shì duōshao?",
  "请开门": "qǐng kāi mén",
  "今天很热": "jīntiān hěn rè",
  "水很冷": "shuǐ hěn lěng",
  "更好一点": "gèng hǎo yìdiǎn",
  "没有糖": "méiyǒu táng",
  "都很好": "dōu hěn hǎo",
  "很近": "hěn jìn",
  "太远了": "tài yuǎn le",
  "你叫什么名字？": "nǐ jiào shénme míngzi?",
  "我病了": "wǒ bìng le",
  "我需要医生": "wǒ xūyào yīshēng",
  "他儿子七岁": "tā érzi qī suì",
  "我女儿在上学": "wǒ nǚ'ér zài shàngxué",
  "八个人": "bā ge rén",
  "九点": "jiǔ diǎn",
  "下雪了": "xià xuě le",
  "我们去爬山": "wǒmen qù pá shān",
};

// Erhua fuses 儿 into the preceding syllable, so the syllable count legitimately
// comes out one short of the character count. Named here so the check can tell
// a real dropped word from a rule of the language.
export const ZH_ERHUA = ["请慢点儿说"];
