// =============================================================================
// v106-fill.mjs — the words for talking about the things around you.
//
// MEASURED, NOT GUESSED. v105 left every pack teaching 143 core concepts and
// 150–224 words, so the next gap was found the same way: roughly seventy
// high-frequency meanings checked against all twenty-one packs at once
// (scripts/_cov2 at the time). These were taught by almost nobody:
//
//   to play, to call, to come back, to find, to bring, never, clothes, shoes,
//   which, police                                         0/21 each
//   that 1/21 · this 2/21 · maybe 1/21 · always 2/21 · again 5/21 · cheap 2/21
//   expensive 4/21 · new 5/21 · egg 4/21 · fruit 4/21 · book 5/21 · fish 9/21
//
// Without "this" and "that" a learner cannot point at anything; without
// cheap/expensive and new, cannot shop; without always/never/again/maybe,
// cannot say how often or how sure; without to come back, to bring, to find,
// to call, cannot run a single errand with family. Hospital and police are
// the two places you cannot afford to be unable to ask for.
//
// Thirty concepts, tier 3 (reach) in coreVocabulary.js. 489 entries — each
// pack only gets the ones it was actually missing.
//
// Fields: [conceptId, lemma, translit, translation, category, unit,
//          exNative, exTranslit, exTranslation]
// translit is "" for the Latin-script languages, which carry none.
//
// UNIT PLACEMENT follows each pack's own layout, measured from anchor words:
// foods beside "bread", verbs beside "to wait", places beside "market"/"door",
// adjectives beside "easy", time words beside "today", "which" beside "what".
//
// EXAMPLES CONTAIN THE LEMMA as validate-word-truth reads it (a prefix of at
// least half the word). Where the natural inflection loses the stem — Korean
// 찾다/놀다/배우다, Persian compound infinitives — a construction that keeps
// it (찾다가, 배우다 보면, an infinitive subject) was chosen over a warning.
//
// HONEST GLOSSES where the word is not a one-to-one match:
//   · pcm "never" is also "not yet" (I never chop = I haven't eaten yet);
//     "find" is "to look for"; "cost" is the adjective "expensive"
//   · ml ഒരിക്കലും / ta ஒருபோதும் / yo láéláé / tl kailanman are "ever",
//     meaning "never" with a negative verb
//   · ja 帰る is "to go home / come back"; vi về the same
//
// CONFIDENCE: Somali and Yoruba sentences are kept short and are flagged for a
// native-speaker pass, as v104's and v105's were.
// =============================================================================

export const V106_FILL = {
  ar: [
    ["this", "هذا", "hadha", "this", "Common", "u10", "هذا بيتي", "hadha bayti", "This is my house"],
    ["that", "ذلك", "dhalika", "that", "Common", "u10", "ذلك الرجل طبيب", "dhalika ar-rajul tabib", "That man is a doctor"],
    ["which", "أي", "ayy", "which", "Common", "u10", "أي بيت؟", "ayy bayt?", "Which house?"],
    ["again", "مرة أخرى", "marra ukhra", "again", "Common", "u10", "قلها مرة أخرى", "qulha marra ukhra", "Say it again"],
    ["never", "أبدا", "abadan", "never", "Time", "u8", "لا أدخن أبدا", "la udakhkhin abadan", "I never smoke"],
    ["maybe", "ربما", "rubbama", "maybe", "Common", "u10", "ربما غدا", "rubbama ghadan", "Maybe tomorrow"],
    ["cheap", "رخيص", "rakhees", "cheap", "Common", "u10", "هذا رخيص", "hadha rakhees", "This is cheap"],
    ["expensive", "غالي", "ghali", "expensive", "Common", "u10", "هذا غالي جدا", "hadha ghali jiddan", "This is very expensive"],
    ["book", "كتاب", "kitab", "book", "Useful", "u10", "هذا كتاب جديد", "hadha kitab jadeed", "This is a new book"],
    ["fish", "سمك", "samak", "fish", "Food", "u5", "أحب السمك", "uhibb as-samak", "I like fish"],
    ["egg", "بيضة", "bayda", "egg", "Food", "u5", "أريد بيضة", "urid bayda", "I want an egg"],
    ["clothes", "ملابس", "malabis", "clothes", "Useful", "u10", "ملابسي نظيفة", "malabisi nadheefa", "My clothes are clean"],
    ["shoes", "حذاء", "hidha", "shoes", "Useful", "u10", "أين حذائي؟", "ayna hidha'i?", "Where are my shoes?"],
    ["to_like", "يحب", "yuhibb", "to like, to love", "Verbs", "u6", "أبي يحب الشاي", "abi yuhibb ash-shay", "My father likes tea"],
    ["to_learn", "يتعلم", "yata'allam", "to learn", "Verbs", "u6", "ابني يتعلم العربية", "ibni yata'allam al-arabiyya", "My son is learning Arabic"],
    ["to_read", "يقرأ", "yaqra", "to read", "Verbs", "u6", "أبي يقرأ الجريدة", "abi yaqra al-jareeda", "My father reads the newspaper"],
    ["to_return", "يرجع", "yarja", "to return, to come back", "Verbs", "u6", "متى يرجع أخوك؟", "mata yarja akhuk?", "When does your brother come back?"],
    ["to_find", "يجد", "yajid", "to find", "Verbs", "u6", "لا يجد مفتاحه", "la yajid miftahahu", "He can't find his key"],
    ["to_bring", "يحضر", "yuhdir", "to bring", "Verbs", "u6", "أخي يحضر الأكل", "akhi yuhdir al-akl", "My brother brings the food"],
    ["to_play", "يلعب", "yal'ab", "to play", "Verbs", "u6", "الولد يلعب في البيت", "al-walad yal'ab fil-bayt", "The boy plays at home"],
    ["police", "شرطة", "shurta", "police", "People", "u7", "اتصل بالشرطة", "ittasil bish-shurta", "Call the police"],
  ],

  bn: [
    ["this", "এটা", "eta", "this", "Common", "u10", "এটা আমার বাড়ি", "eta amar bari", "This is my house"],
    ["that", "ওটা", "ota", "that", "Common", "u10", "ওটা কী?", "ota ki?", "What is that?"],
    ["which", "কোনটা", "konta", "which", "Common", "u2", "কোনটা তোমার?", "konta tomar?", "Which one is yours?"],
    ["always", "সবসময়", "sobshomoy", "always", "Time", "u8", "মা সবসময় রান্না করেন", "ma sobshomoy ranna koren", "Mother always cooks"],
    ["never", "কখনো", "kokhono", "never (with না), ever", "Time", "u8", "আমি কখনো মাংস খাই না", "ami kokhono mangsho khai na", "I never eat meat"],
    ["maybe", "হয়তো", "hoyto", "maybe", "Common", "u10", "হয়তো কাল", "hoyto kal", "Maybe tomorrow"],
    ["cheap", "সস্তা", "shosta", "cheap", "Common", "u10", "এটা খুব সস্তা", "eta khub shosta", "This is very cheap"],
    ["expensive", "দামি", "dami", "expensive", "Common", "u10", "এই জামা দামি", "ei jama dami", "This shirt is expensive"],
    ["child", "বাচ্চা", "baccha", "child", "Family", "u3", "বাচ্চাটা ঘুমাচ্ছে", "bacchata ghumacche", "The child is sleeping"],
    ["book", "বই", "boi", "book", "Useful", "u10", "আমি বই পড়ি", "ami boi pori", "I read books"],
    ["egg", "ডিম", "dim", "egg", "Food", "u5", "দুটো ডিম দাও", "duto dim dao", "Give me two eggs"],
    ["fruit", "ফল", "fol", "fruit", "Food", "u5", "আমি ফল খাই", "ami fol khai", "I eat fruit"],
    ["clothes", "কাপড়", "kapor", "clothes", "Useful", "u10", "কাপড় ধুতে হবে", "kapor dhute hobe", "The clothes need washing"],
    ["shoes", "জুতা", "juta", "shoes", "Useful", "u10", "আমার জুতা কোথায়?", "amar juta kothay?", "Where are my shoes?"],
    ["to_like", "পছন্দ করা", "pochhondo kora", "to like", "Verbs", "u6", "আমি চা পছন্দ করি", "ami cha pochhondo kori", "I like tea"],
    ["to_return", "ফিরে আসা", "phire asha", "to come back", "Verbs", "u6", "বাবা কখন ফিরে আসবেন?", "baba kokhon phire ashben?", "When will Dad come back?"],
    ["to_find", "খুঁজে পাওয়া", "khuje paowa", "to find", "Verbs", "u6", "চাবি খুঁজে পাচ্ছি না", "chabi khuje pacchi na", "I can't find the key"],
    ["to_bring", "আনা", "ana", "to bring", "Verbs", "u6", "বাজার থেকে দুধ আনা লাগবে", "bazar theke dudh ana lagbe", "We need to bring milk from the market"],
    ["to_play", "খেলা", "khela", "to play", "Verbs", "u6", "বাচ্চারা খেলা করছে", "bacchara khela korche", "The children are playing"],
    ["police", "পুলিশ", "pulish", "police", "People", "u7", "পুলিশ ডাকো", "pulish dako", "Call the police"],
  ],

  de: [
    ["this", "dieser", "", "this", "Common", "u13", "Dieser Zug ist schnell", "", "This train is fast"],
    ["that", "das", "", "that", "Common", "u13", "Das ist mein Vater", "", "That is my father"],
    ["which", "welcher", "", "which", "Common", "u9", "Welcher Bus fährt zum Bahnhof?", "", "Which bus goes to the station?"],
    ["again", "wieder", "", "again", "Common", "u13", "Komm bald wieder", "", "Come again soon"],
    ["never", "nie", "", "never", "Time", "u8", "Ich rauche nie", "", "I never smoke"],
    ["maybe", "vielleicht", "", "maybe", "Common", "u13", "Vielleicht morgen", "", "Maybe tomorrow"],
    ["new", "neu", "", "new", "Common", "u13", "Das Auto ist neu", "", "The car is new"],
    ["school", "die Schule", "", "school", "Places", "u7", "Die Schule ist nah", "", "The school is near"],
    ["book", "das Buch", "", "book", "Useful", "u13", "Das Buch ist gut", "", "The book is good"],
    ["fish", "der Fisch", "", "fish", "Food", "u5", "Der Fisch ist frisch", "", "The fish is fresh"],
    ["meat", "das Fleisch", "", "meat", "Food", "u5", "Das Fleisch ist teuer", "", "The meat is expensive"],
    ["egg", "das Ei", "", "egg", "Food", "u5", "Das Ei ist gekocht", "", "The egg is boiled"],
    ["fruit", "das Obst", "", "fruit", "Food", "u5", "Das Obst ist süß", "", "The fruit is sweet"],
    ["clothes", "die Kleidung", "", "clothes", "Useful", "u13", "Die Kleidung ist sauber", "", "The clothes are clean"],
    ["shoes", "die Schuhe", "", "shoes", "Useful", "u13", "Die Schuhe sind neu", "", "The shoes are new"],
    ["to_like", "mögen", "", "to like", "Verbs", "u6", "Mögen Sie Kaffee?", "", "Do you like coffee?"],
    ["to_learn", "lernen", "", "to learn", "Verbs", "u6", "Ich will Deutsch lernen", "", "I want to learn German"],
    ["to_read", "lesen", "", "to read", "Verbs", "u6", "Kannst du das lesen?", "", "Can you read that?"],
    ["to_listen", "zuhören", "", "to listen", "Verbs", "u6", "Du musst gut zuhören", "", "You have to listen carefully"],
    ["to_call", "anrufen", "", "to call", "Verbs", "u6", "Ich muss meine Mutter anrufen", "", "I have to call my mother"],
    ["to_return", "zurückkommen", "", "to come back", "Verbs", "u6", "Er will morgen zurückkommen", "", "He wants to come back tomorrow"],
    ["to_find", "finden", "", "to find", "Verbs", "u6", "Ich kann meinen Schlüssel nicht finden", "", "I can't find my key"],
    ["to_bring", "bringen", "", "to bring", "Verbs", "u6", "Kannst du Brot bringen?", "", "Can you bring bread?"],
    ["to_play", "spielen", "", "to play", "Verbs", "u6", "Die Kinder spielen draußen", "", "The children are playing outside"],
    ["police", "die Polizei", "", "police", "People", "u7", "Ruf die Polizei!", "", "Call the police!"],
  ],

  es: [
    ["this", "este", "", "this", "Common", "u13", "Este tren es rápido", "", "This train is fast"],
    ["that", "eso", "", "that", "Common", "u13", "¿Qué es eso?", "", "What is that?"],
    ["which", "cuál", "", "which", "Common", "u2", "¿Cuál prefieres?", "", "Which do you prefer?"],
    ["always", "siempre", "", "always", "Time", "u8", "Mi madre siempre cocina", "", "My mother always cooks"],
    ["never", "nunca", "", "never", "Time", "u8", "Nunca fumo", "", "I never smoke"],
    ["cheap", "barato", "", "cheap", "Common", "u13", "Este mercado es barato", "", "This market is cheap"],
    ["expensive", "caro", "", "expensive", "Common", "u13", "El hotel es muy caro", "", "The hotel is very expensive"],
    ["child", "el niño", "", "child", "Family", "u3", "El niño está durmiendo", "", "The child is sleeping"],
    ["book", "el libro", "", "book", "Useful", "u13", "El libro es nuevo", "", "The book is new"],
    ["fruit", "la fruta", "", "fruit", "Food", "u5", "Me gusta la fruta", "", "I like fruit"],
    ["clothes", "la ropa", "", "clothes", "Useful", "u13", "La ropa está limpia", "", "The clothes are clean"],
    ["shoes", "los zapatos", "", "shoes", "Useful", "u13", "Los zapatos son nuevos", "", "The shoes are new"],
    ["to_return", "volver", "", "to come back", "Verbs", "u6", "Quiero volver mañana", "", "I want to come back tomorrow"],
    ["to_find", "encontrar", "", "to find", "Verbs", "u6", "No puedo encontrar la llave", "", "I can't find the key"],
    ["to_bring", "traer", "", "to bring", "Verbs", "u6", "¿Puedes traer pan?", "", "Can you bring bread?"],
    ["to_play", "jugar", "", "to play", "Verbs", "u6", "Los niños quieren jugar", "", "The children want to play"],
    ["police", "la policía", "", "police", "People", "u7", "¡Llama a la policía!", "", "Call the police!"],
  ],

  fa: [
    ["this", "این", "in", "this", "Common", "u7", "این خانهٔ من است", "in khâne-ye man ast", "This is my house"],
    ["that", "آن", "ân", "that", "Common", "u7", "آن مرد پزشک است", "ân mard pezeshk ast", "That man is a doctor"],
    ["which", "کدام", "kodâm", "which", "Questions", "u8", "کدام خانه؟", "kodâm khâne?", "Which house?"],
    ["again", "دوباره", "dobâre", "again", "Common", "u7", "دوباره بگو", "dobâre begu", "Say it again"],
    ["always", "همیشه", "hamishe", "always", "Time", "u8", "مادرم همیشه آشپزی می‌کند", "mâdaram hamishe âshpazi mikonad", "My mother always cooks"],
    ["never", "هرگز", "hargez", "never", "Time", "u8", "من هرگز سیگار نمی‌کشم", "man hargez sigâr nemikesham", "I never smoke"],
    ["maybe", "شاید", "shâyad", "maybe", "Common", "u7", "شاید فردا", "shâyad fardâ", "Maybe tomorrow"],
    ["new", "جدید", "jadid", "new", "Common", "u7", "ماشین جدید", "mâshin-e jadid", "A new car"],
    ["cheap", "ارزان", "arzân", "cheap", "Common", "u7", "این ارزان است", "in arzân ast", "This is cheap"],
    ["expensive", "گران", "gerân", "expensive", "Common", "u7", "هتل گران است", "hotel gerân ast", "The hotel is expensive"],
    ["child", "بچه", "bache", "child", "Family", "u4", "بچه خواب است", "bache khâb ast", "The child is asleep"],
    ["school", "مدرسه", "madrese", "school", "Places", "u8", "مدرسه نزدیک است", "madrese nazdik ast", "The school is near"],
    ["fish", "ماهی", "mâhi", "fish", "Food", "u6", "ماهی تازه است", "mâhi tâze ast", "The fish is fresh"],
    ["meat", "گوشت", "gusht", "meat", "Food", "u6", "گوشت نمی‌خورم", "gusht nemikhoram", "I don't eat meat"],
    ["egg", "تخم‌مرغ", "tokhm-e morgh", "egg", "Food", "u6", "دو تخم‌مرغ بده", "do tokhm-e morgh bede", "Give me two eggs"],
    ["fruit", "میوه", "mive", "fruit", "Food", "u6", "میوه دوست دارم", "mive dust dâram", "I like fruit"],
    ["clothes", "لباس", "lebâs", "clothes", "Useful", "u7", "لباس‌هایم تمیز است", "lebâshâyam tamiz ast", "My clothes are clean"],
    ["shoes", "کفش", "kafsh", "shoes", "Useful", "u7", "کفش‌هایم کجاست؟", "kafshhâyam kojâst?", "Where are my shoes?"],
    ["to_learn", "یاد گرفتن", "yâd gereftan", "to learn", "Verbs", "u7", "یاد گرفتن فارسی آسان نیست", "yâd gereftan-e fârsi âsân nist", "Learning Persian is not easy"],
    ["to_read", "خواندن", "khândan", "to read", "Verbs", "u7", "خواندن را دوست دارم", "khândan râ dust dâram", "I like reading"],
    ["to_listen", "گوش دادن", "gush dâdan", "to listen", "Verbs", "u7", "گوش دادن مهم است", "gush dâdan mohem ast", "Listening is important"],
    ["to_return", "برگشتن", "bargashtan", "to come back", "Verbs", "u7", "وقت برگشتن است", "vaqt-e bargashtan ast", "It's time to come back"],
    ["to_find", "پیدا کردن", "peydâ kardan", "to find", "Verbs", "u7", "کلیدم را پیدا کردم", "kelidam râ peydâ kardam", "I found my key"],
    ["to_bring", "آوردن", "âvardan", "to bring", "Verbs", "u7", "آوردن نان یادت نرود", "âvardan-e nân yâdat naravad", "Don't forget to bring bread"],
    ["to_play", "بازی کردن", "bâzi kardan", "to play", "Verbs", "u7", "بچه‌ها بازی کردن را دوست دارند", "bachehâ bâzi kardan râ dust dârand", "Children love to play"],
    ["hospital", "بیمارستان", "bimârestân", "hospital", "Places", "u8", "بیمارستان کجاست؟", "bimârestân kojâst?", "Where is the hospital?"],
    ["police", "پلیس", "polis", "police", "People", "u8", "به پلیس زنگ بزن", "be polis zang bezan", "Call the police"],
  ],

  fr: [
    ["this", "ce", "", "this", "Common", "u13", "Ce train est rapide", "", "This train is fast"],
    ["that", "ça", "", "that", "Common", "u13", "Ça coûte combien ?", "", "How much does that cost?"],
    ["which", "quel", "", "which", "Common", "u2", "Quel bus va à la gare ?", "", "Which bus goes to the station?"],
    ["again", "encore", "", "again", "Common", "u13", "Dis-le encore", "", "Say it again"],
    ["always", "toujours", "", "always", "Time", "u8", "Ma mère cuisine toujours", "", "My mother always cooks"],
    ["never", "jamais", "", "never", "Time", "u8", "Je ne fume jamais", "", "I never smoke"],
    ["maybe", "peut-être", "", "maybe", "Common", "u13", "Peut-être demain", "", "Maybe tomorrow"],
    ["new", "nouveau", "", "new", "Common", "u13", "C'est un nouveau livre", "", "It's a new book"],
    ["cheap", "bon marché", "", "cheap", "Common", "u13", "Ce restaurant est bon marché", "", "This restaurant is cheap"],
    ["expensive", "cher", "", "expensive", "Common", "u13", "L'hôtel est très cher", "", "The hotel is very expensive"],
    ["child", "l'enfant", "", "child", "Family", "u3", "L'enfant dort", "", "The child is sleeping"],
    ["book", "le livre", "", "book", "Useful", "u13", "Le livre est sur la table", "", "The book is on the table"],
    ["meat", "la viande", "", "meat", "Food", "u5", "La viande est chère", "", "The meat is expensive"],
    ["fruit", "le fruit", "", "fruit", "Food", "u5", "Le fruit est mûr", "", "The fruit is ripe"],
    ["clothes", "les vêtements", "", "clothes", "Useful", "u13", "Les vêtements sont propres", "", "The clothes are clean"],
    ["shoes", "les chaussures", "", "shoes", "Useful", "u13", "Les chaussures sont neuves", "", "The shoes are new"],
    ["to_return", "revenir", "", "to come back", "Verbs", "u6", "Je veux revenir demain", "", "I want to come back tomorrow"],
    ["to_find", "trouver", "", "to find", "Verbs", "u6", "Je ne peux pas trouver la clé", "", "I can't find the key"],
    ["to_bring", "apporter", "", "to bring", "Verbs", "u6", "Tu peux apporter du pain ?", "", "Can you bring some bread?"],
    ["to_play", "jouer", "", "to play", "Verbs", "u6", "Les enfants veulent jouer", "", "The children want to play"],
    ["police", "la police", "", "police", "People", "u7", "Appelle la police !", "", "Call the police!"],
  ],

  hi: [
    ["this", "यह", "yeh", "this", "Common", "u10", "यह मेरा घर है", "yeh mera ghar hai", "This is my house"],
    ["that", "वह", "vah", "that", "Common", "u10", "वह आदमी डॉक्टर है", "vah aadmi doctor hai", "That man is a doctor"],
    ["which", "कौन सा", "kaun sa", "which", "Common", "u1", "कौन सा रंग?", "kaun sa rang?", "Which colour?"],
    ["always", "हमेशा", "hamesha", "always", "Time", "u8", "माँ हमेशा खाना बनाती हैं", "maa hamesha khana banati hain", "Mother always cooks"],
    ["never", "कभी नहीं", "kabhi nahin", "never", "Time", "u8", "मैं कभी नहीं भूलूँगा", "main kabhi nahin bhooloonga", "I will never forget"],
    ["maybe", "शायद", "shayad", "maybe", "Common", "u10", "शायद कल", "shayad kal", "Maybe tomorrow"],
    ["new", "नया", "naya", "new", "Common", "u10", "यह नया घर है", "yeh naya ghar hai", "This is a new house"],
    ["cheap", "सस्ता", "sasta", "cheap", "Common", "u10", "यह बहुत सस्ता है", "yeh bahut sasta hai", "This is very cheap"],
    ["expensive", "महँगा", "mahanga", "expensive", "Common", "u10", "होटल महँगा है", "hotel mahanga hai", "The hotel is expensive"],
    ["book", "किताब", "kitaab", "book", "Useful", "u10", "यह किताब अच्छी है", "yeh kitaab achchhi hai", "This book is good"],
    ["fish", "मछली", "machhli", "fish", "Food", "u5", "मछली ताज़ा है", "machhli taaza hai", "The fish is fresh"],
    ["meat", "मांस", "maans", "meat", "Food", "u5", "मैं मांस नहीं खाता", "main maans nahin khata", "I don't eat meat"],
    ["egg", "अंडा", "anda", "egg", "Food", "u5", "दो अंडे दो", "do ande do", "Give me two eggs"],
    ["fruit", "फल", "phal", "fruit", "Food", "u5", "मुझे फल पसंद है", "mujhe phal pasand hai", "I like fruit"],
    ["clothes", "कपड़े", "kapde", "clothes", "Useful", "u10", "कपड़े साफ़ हैं", "kapde saaf hain", "The clothes are clean"],
    ["shoes", "जूते", "joote", "shoes", "Useful", "u10", "मेरे जूते कहाँ हैं?", "mere joote kahan hain?", "Where are my shoes?"],
    ["to_learn", "सीखना", "seekhna", "to learn", "Verbs", "u6", "मुझे हिंदी सीखना है", "mujhe hindi seekhna hai", "I want to learn Hindi"],
    ["to_read", "पढ़ना", "padhna", "to read", "Verbs", "u6", "मुझे पढ़ना पसंद है", "mujhe padhna pasand hai", "I like to read"],
    ["to_return", "लौटना", "lautna", "to come back", "Verbs", "u6", "पापा कब लौटेंगे?", "papa kab lautenge?", "When will Dad come back?"],
    ["to_find", "ढूँढना", "dhoondhna", "to look for, to find", "Verbs", "u6", "मैं चाबी ढूँढ रहा हूँ", "main chaabi dhoondh raha hoon", "I am looking for the key"],
    ["to_bring", "लाना", "laana", "to bring", "Verbs", "u6", "पानी लाना", "paani laana", "Bring water"],
    ["to_play", "खेलना", "khelna", "to play", "Verbs", "u6", "बच्चे बाहर खेल रहे हैं", "bachche bahar khel rahe hain", "The children are playing outside"],
    ["hospital", "अस्पताल", "aspataal", "hospital", "Places", "u7", "अस्पताल कहाँ है?", "aspataal kahan hai?", "Where is the hospital?"],
    ["police", "पुलिस", "pulis", "police", "People", "u7", "पुलिस को बुलाओ", "pulis ko bulao", "Call the police"],
  ],

  id: [
    ["this", "ini", "", "this", "Common", "u6", "Ini rumah saya", "", "This is my house"],
    ["that", "itu", "", "that", "Common", "u6", "Itu apa?", "", "What is that?"],
    ["which", "yang mana", "", "which", "Common", "u2", "Yang mana punyamu?", "", "Which one is yours?"],
    ["always", "selalu", "", "always", "Time", "u5", "Ibu selalu memasak", "", "Mother always cooks"],
    ["never", "tidak pernah", "", "never", "Time", "u5", "Saya tidak pernah merokok", "", "I never smoke"],
    ["maybe", "mungkin", "", "maybe", "Common", "u6", "Mungkin besok", "", "Maybe tomorrow"],
    ["new", "baru", "", "new", "Common", "u6", "Mobil ini baru", "", "This car is new"],
    ["cheap", "murah", "", "cheap", "Common", "u6", "Pasar ini murah", "", "This market is cheap"],
    ["expensive", "mahal", "", "expensive", "Common", "u6", "Hotel itu mahal", "", "That hotel is expensive"],
    ["school", "sekolah", "", "school", "Places", "u6", "Sekolah dekat dari rumah", "", "The school is near the house"],
    ["book", "buku", "", "book", "Useful", "u6", "Buku ini bagus", "", "This book is good"],
    ["fish", "ikan", "", "fish", "Food", "u5", "Ikan ini segar", "", "This fish is fresh"],
    ["meat", "daging", "", "meat", "Food", "u5", "Saya tidak makan daging", "", "I don't eat meat"],
    ["egg", "telur", "", "egg", "Food", "u5", "Dua telur, ya", "", "Two eggs, please"],
    ["fruit", "buah", "", "fruit", "Food", "u5", "Saya suka buah", "", "I like fruit"],
    ["clothes", "baju", "", "clothes", "Useful", "u6", "Bajunya sudah bersih", "", "The clothes are clean now"],
    ["shoes", "sepatu", "", "shoes", "Useful", "u6", "Di mana sepatu saya?", "", "Where are my shoes?"],
    ["to_learn", "belajar", "", "to learn", "Verbs", "u6", "Saya belajar bahasa Indonesia", "", "I am learning Indonesian"],
    ["to_read", "membaca", "", "to read", "Verbs", "u6", "Ayah membaca koran", "", "Father reads the newspaper"],
    ["to_return", "kembali", "", "to come back", "Verbs", "u6", "Kapan kamu kembali?", "", "When are you coming back?"],
    ["to_find", "menemukan", "", "to find", "Verbs", "u6", "Saya tidak bisa menemukan kunci", "", "I can't find the key"],
    ["to_bring", "membawa", "", "to bring", "Verbs", "u6", "Dia membawa makanan", "", "He brings food"],
    ["to_play", "bermain", "", "to play", "Verbs", "u6", "Anak-anak bermain di luar", "", "The children are playing outside"],
    ["hospital", "rumah sakit", "", "hospital", "Places", "u6", "Rumah sakit di mana?", "", "Where is the hospital?"],
    ["police", "polisi", "", "police", "People", "u6", "Panggil polisi!", "", "Call the police!"],
  ],

  ja: [
    ["that", "あれ", "are", "that", "Common", "u10", "あれは何ですか", "are wa nan desu ka", "What is that?"],
    ["which", "どれ", "dore", "which", "Common", "u10", "どれがいいですか", "dore ga ii desu ka", "Which one is good?"],
    ["again", "また", "mata", "again", "Common", "u10", "また会いましょう", "mata aimashou", "Let's meet again"],
    ["always", "いつも", "itsumo", "always", "Time", "u8", "母はいつも料理します", "haha wa itsumo ryouri shimasu", "My mother always cooks"],
    ["never", "決して", "kesshite", "never", "Time", "u8", "決して忘れません", "kesshite wasuremasen", "I will never forget"],
    ["maybe", "たぶん", "tabun", "maybe", "Common", "u10", "たぶん明日です", "tabun ashita desu", "Maybe tomorrow"],
    ["new", "新しい", "atarashii", "new", "Common", "u10", "新しい車です", "atarashii kuruma desu", "It is a new car"],
    ["cheap", "安い", "yasui", "cheap", "Common", "u10", "これは安いです", "kore wa yasui desu", "This is cheap"],
    ["expensive", "高い", "takai", "expensive, high", "Common", "u10", "このホテルは高いです", "kono hoteru wa takai desu", "This hotel is expensive"],
    ["child", "子供", "kodomo", "child", "Family", "u2", "子供が寝ています", "kodomo ga nete imasu", "The child is sleeping"],
    ["book", "本", "hon", "book", "Useful", "u10", "この本はおもしろいです", "kono hon wa omoshiroi desu", "This book is interesting"],
    ["egg", "卵", "tamago", "egg", "Food", "u5", "卵を二つください", "tamago wo futatsu kudasai", "Two eggs, please"],
    ["fruit", "果物", "kudamono", "fruit", "Food", "u5", "果物が好きです", "kudamono ga suki desu", "I like fruit"],
    ["clothes", "服", "fuku", "clothes", "Useful", "u10", "服を洗います", "fuku wo araimasu", "I wash the clothes"],
    ["shoes", "靴", "kutsu", "shoes", "Useful", "u10", "私の靴はどこですか", "watashi no kutsu wa doko desu ka", "Where are my shoes?"],
    ["to_like", "好き", "suki", "to like", "Verbs", "u6", "コーヒーが好きです", "koohii ga suki desu", "I like coffee"],
    ["to_learn", "習う", "narau", "to learn", "Verbs", "u6", "娘はピアノを習う", "musume wa piano wo narau", "My daughter learns piano"],
    ["to_read", "読む", "yomu", "to read", "Verbs", "u6", "父は新聞を読む", "chichi wa shinbun wo yomu", "My father reads the newspaper"],
    ["to_return", "帰る", "kaeru", "to go home, to come back", "Verbs", "u6", "何時に帰る？", "nanji ni kaeru?", "What time are you coming home?"],
    ["to_find", "見つける", "mitsukeru", "to find", "Verbs", "u6", "鍵を見つけるのは難しい", "kagi wo mitsukeru no wa muzukashii", "Finding the key is hard"],
    ["to_bring", "持ってくる", "motte kuru", "to bring", "Verbs", "u6", "水を持ってくる", "mizu wo motte kuru", "I'll bring water"],
    ["to_play", "遊ぶ", "asobu", "to play", "Verbs", "u6", "子供たちは外で遊ぶ", "kodomotachi wa soto de asobu", "The children play outside"],
    ["hospital", "病院", "byouin", "hospital", "Places", "u7", "病院はどこですか", "byouin wa doko desu ka", "Where is the hospital?"],
    ["police", "警察", "keisatsu", "police", "People", "u7", "警察を呼んでください", "keisatsu wo yonde kudasai", "Please call the police"],
  ],

  ko: [
    ["that", "저것", "jeogeot", "that", "Common", "u10", "저것은 뭐예요?", "jeogeoseun mwoyeyo?", "What is that?"],
    ["which", "어느", "eoneu", "which", "Common", "u2", "어느 것이 좋아요?", "eoneu geosi joayo?", "Which one is good?"],
    ["again", "다시", "dasi", "again", "Common", "u10", "다시 말해 주세요", "dasi malhae juseyo", "Please say it again"],
    ["always", "항상", "hangsang", "always", "Time", "u8", "엄마는 항상 요리해요", "eommaneun hangsang yorihaeyo", "Mom always cooks"],
    ["never", "절대", "jeoldae", "never", "Time", "u8", "절대 잊지 않을게요", "jeoldae itji aneulgeyo", "I will never forget"],
    ["maybe", "아마", "ama", "maybe", "Common", "u10", "아마 내일이요", "ama naeiriyo", "Maybe tomorrow"],
    ["new", "새", "sae", "new", "Common", "u10", "새 차예요", "sae chayeyo", "It's a new car"],
    ["cheap", "싸다", "ssada", "cheap", "Common", "u10", "이거 정말 싸다", "igeo jeongmal ssada", "This is really cheap"],
    ["expensive", "비싸다", "bissada", "expensive", "Common", "u10", "호텔이 너무 비싸다", "hoteri neomu bissada", "The hotel is too expensive"],
    ["book", "책", "chaek", "book", "Useful", "u10", "이 책은 재미있어요", "i chaegeun jaemiisseoyo", "This book is interesting"],
    ["fish", "생선", "saengseon", "fish", "Food", "u5", "생선이 신선해요", "saengseoni sinseonhaeyo", "The fish is fresh"],
    ["egg", "계란", "gyeran", "egg", "Food", "u5", "계란 두 개 주세요", "gyeran du gae juseyo", "Two eggs, please"],
    ["fruit", "과일", "gwail", "fruit", "Food", "u5", "과일을 좋아해요", "gwaireul joahaeyo", "I like fruit"],
    ["clothes", "옷", "ot", "clothes", "Useful", "u10", "옷 가게가 어디예요?", "ot gagega eodiyeyo?", "Where is the clothes shop?"],
    ["shoes", "신발", "sinbal", "shoes", "Useful", "u10", "신발이 어디 있어요?", "sinbari eodi isseoyo?", "Where are the shoes?"],
    ["to_like", "좋아하다", "joahada", "to like", "Verbs", "u6", "제가 좋아하는 음식이에요", "jega joahaneun eumsigieyo", "It's the food I like"],
    ["to_learn", "배우다", "baeuda", "to learn", "Verbs", "u6", "배우다 보면 쉬워져요", "baeuda bomyeon swiwojyeoyo", "It gets easier as you learn"],
    ["to_return", "돌아오다", "doraoda", "to come back", "Verbs", "u6", "빨리 돌아오세요", "ppalli doraoseyo", "Come back soon"],
    ["to_find", "찾다", "chatda", "to find, to look for", "Verbs", "u6", "열쇠를 찾다가 늦었어요", "yeolsoereul chatdaga neujeosseoyo", "I was late looking for my key"],
    ["to_bring", "가져오다", "gajyeooda", "to bring", "Verbs", "u6", "물 좀 가져오세요", "mul jom gajyeooseyo", "Please bring some water"],
    ["to_play", "놀다", "nolda", "to play", "Verbs", "u6", "놀다가 넘어졌어요", "noldaga neomeojyeosseoyo", "I fell while playing"],
    ["hospital", "병원", "byeongwon", "hospital", "Places", "u7", "병원이 어디예요?", "byeongwoni eodiyeyo?", "Where is the hospital?"],
    ["police", "경찰", "gyeongchal", "police", "People", "u7", "경찰을 불러 주세요", "gyeongchareul bulleo juseyo", "Please call the police"],
  ],

  ml: [
    ["this", "ഇത്", "ithu", "this", "Common", "u7", "ഇത് എന്റെ വീടാണ്", "ithu ente veedaanu", "This is my house"],
    ["that", "അത്", "athu", "that", "Common", "u7", "അത് എന്താണ്?", "athu enthaanu?", "What is that?"],
    ["which", "ഏത്", "ethu", "which", "Questions", "u8", "ഏത് ബസ്?", "ethu bus?", "Which bus?"],
    ["again", "വീണ്ടും", "veendum", "again", "Common", "u7", "വീണ്ടും വരൂ", "veendum varoo", "Come again"],
    ["always", "എപ്പോഴും", "eppozhum", "always", "Time", "u8", "അമ്മ എപ്പോഴും പാചകം ചെയ്യും", "amma eppozhum paachakam cheyyum", "Mother always cooks"],
    ["never", "ഒരിക്കലും", "orikkalum", "never (with a negative), ever", "Time", "u8", "ഞാൻ ഒരിക്കലും മറക്കില്ല", "njaan orikkalum marakkilla", "I will never forget"],
    ["maybe", "ഒരുപക്ഷേ", "orupakshe", "maybe", "Common", "u7", "ഒരുപക്ഷേ നാളെ", "orupakshe naale", "Maybe tomorrow"],
    ["new", "പുതിയ", "puthiya", "new", "Common", "u7", "ഇത് പുതിയ വീടാണ്", "ithu puthiya veedaanu", "This is a new house"],
    ["cheap", "വില കുറഞ്ഞ", "vila kuranja", "cheap", "Common", "u7", "ഇത് വില കുറഞ്ഞ സാധനമാണ്", "ithu vila kuranja saadhanamaanu", "This is a cheap item"],
    ["expensive", "വിലകൂടിയ", "vilakoodiya", "expensive", "Common", "u7", "ഇത് വിലകൂടിയ ഫോണാണ്", "ithu vilakoodiya phonaanu", "This is an expensive phone"],
    ["child", "കുട്ടി", "kutti", "child", "Family", "u4", "കുട്ടി ഉറങ്ങുകയാണ്", "kutti urangukayaanu", "The child is sleeping"],
    ["school", "സ്കൂൾ", "school", "school", "Places", "u8", "സ്കൂൾ അടുത്താണ്", "school aduthaanu", "The school is near"],
    ["meat", "ഇറച്ചി", "irachi", "meat", "Food", "u6", "ഞാൻ ഇറച്ചി കഴിക്കില്ല", "njaan irachi kazhikkilla", "I don't eat meat"],
    ["egg", "മുട്ട", "mutta", "egg", "Food", "u6", "രണ്ട് മുട്ട തരൂ", "randu mutta tharoo", "Give me two eggs"],
    ["clothes", "വസ്ത്രം", "vasthram", "clothes", "Useful", "u7", "വസ്ത്രം വൃത്തിയാണ്", "vasthram vruthiyaanu", "The clothes are clean"],
    ["shoes", "ചെരിപ്പ്", "cherippu", "shoes, footwear", "Useful", "u7", "എന്റെ ചെരിപ്പ് എവിടെ?", "ente cherippu evide?", "Where are my shoes?"],
    ["to_like", "ഇഷ്ടം", "ishtam", "to like, liking", "Verbs", "u7", "എനിക്ക് ചായ ഇഷ്ടമാണ്", "enikku chaaya ishtamaanu", "I like tea"],
    ["to_read", "വായിക്കുക", "vaayikkuka", "to read", "Verbs", "u7", "അച്ഛൻ പത്രം വായിക്കുന്നു", "achan pathram vaayikkunnu", "Father is reading the newspaper"],
    ["to_listen", "കേൾക്കുക", "kelkkuka", "to listen, to hear", "Verbs", "u7", "ഞാൻ പാട്ട് കേൾക്കുന്നു", "njaan paattu kelkkunnu", "I am listening to a song"],
    ["to_return", "തിരിച്ചുവരിക", "thirichuvarika", "to come back", "Verbs", "u7", "അച്ഛൻ എപ്പോൾ തിരിച്ചുവരും?", "achan eppol thirichuvarum?", "When will Father come back?"],
    ["to_find", "കണ്ടെത്തുക", "kandethuka", "to find", "Verbs", "u7", "താക്കോൽ കണ്ടെത്തി", "thaakkol kandethi", "I found the key"],
    ["to_bring", "കൊണ്ടുവരിക", "konduvarika", "to bring", "Verbs", "u7", "വെള്ളം കൊണ്ടുവരൂ", "vellam konduvaroo", "Bring water"],
    ["to_play", "കളിക്കുക", "kalikkuka", "to play", "Verbs", "u7", "കുട്ടികൾ പുറത്ത് കളിക്കുന്നു", "kuttikal purathu kalikkunnu", "The children are playing outside"],
    ["hospital", "ആശുപത്രി", "aashupathri", "hospital", "Places", "u8", "ആശുപത്രി എവിടെയാണ്?", "aashupathri evideyaanu?", "Where is the hospital?"],
    ["police", "പോലീസ്", "police", "police", "People", "u8", "പോലീസിനെ വിളിക്കൂ", "policine vilikkoo", "Call the police"],
  ],

  pa: [
    ["this", "ایہہ", "eh", "this", "Common", "u6", "ایہہ میرا گھر اے", "eh mera ghar ae", "This is my house"],
    ["which", "کیہڑا", "kehra", "which", "Common", "u2", "کیہڑا رنگ؟", "kehra rang?", "Which colour?"],
    ["always", "ہمیشہ", "hamesha", "always", "Time", "u4", "ماں ہمیشہ کھانا پکاندی اے", "maan hamesha khana pakaandi ae", "Mother always cooks"],
    ["never", "کدی نئیں", "kadi nahin", "never", "Time", "u4", "میں کدی نئیں بھلاں گا", "main kadi nahin bhulaan ga", "I will never forget"],
    ["maybe", "شاید", "shayad", "maybe", "Common", "u6", "شاید کل", "shayad kal", "Maybe tomorrow"],
    ["new", "نواں", "navaan", "new", "Common", "u6", "ایہہ نواں گھر اے", "eh navaan ghar ae", "This is a new house"],
    ["cheap", "سستا", "sasta", "cheap", "Common", "u6", "ایہہ بہت سستا اے", "eh bahut sasta ae", "This is very cheap"],
    ["expensive", "مہنگا", "mehnga", "expensive", "Common", "u6", "ہوٹل مہنگا اے", "hotel mehnga ae", "The hotel is expensive"],
    ["school", "سکول", "school", "school", "Places", "u6", "سکول نیڑے اے", "school nerre ae", "The school is near"],
    ["book", "کتاب", "kitaab", "book", "Useful", "u6", "ایہہ کتاب چنگی اے", "eh kitaab changi ae", "This book is good"],
    ["fish", "مچھی", "machhi", "fish", "Food", "u5", "مچھی تازی اے", "machhi taazi ae", "The fish is fresh"],
    ["meat", "گوشت", "gosht", "meat", "Food", "u5", "میں گوشت نئیں کھاندا", "main gosht nahin khaanda", "I don't eat meat"],
    ["egg", "انڈا", "anda", "egg", "Food", "u5", "دو انڈے دیو", "do ande deo", "Give me two eggs"],
    ["fruit", "پھل", "phal", "fruit", "Food", "u5", "مینوں پھل پسند اے", "mainu phal pasand ae", "I like fruit"],
    ["clothes", "کپڑے", "kapre", "clothes", "Useful", "u6", "کپڑے صاف نیں", "kapre saaf nein", "The clothes are clean"],
    ["shoes", "جتی", "jutti", "shoes", "Useful", "u6", "میری جتی کتھے اے؟", "meri jutti kithe ae?", "Where are my shoes?"],
    ["to_like", "پسند کرنا", "pasand karna", "to like", "Verbs", "u6", "مینوں چاہ پسند اے", "mainu chaah pasand ae", "I like tea"],
    ["to_learn", "سکھنا", "sikhna", "to learn", "Verbs", "u6", "میں پنجابی سکھنا چاہندا ہاں", "main punjabi sikhna chaahnda haan", "I want to learn Punjabi"],
    ["to_read", "پڑھنا", "parhna", "to read", "Verbs", "u6", "مینوں پڑھنا پسند اے", "mainu parhna pasand ae", "I like to read"],
    ["to_return", "واپس آنا", "vaapas aana", "to come back", "Verbs", "u6", "ابا کدوں واپس آن گے؟", "abba kadon vaapas aan ge?", "When will Dad come back?"],
    ["to_find", "لبھنا", "labhna", "to find", "Verbs", "u6", "چابی نئیں لبھدی", "chaabi nahin labhdi", "I can't find the key"],
    ["to_bring", "لیانا", "liaana", "to bring", "Verbs", "u6", "پانی لیاؤ", "paani liaao", "Bring water"],
    ["to_play", "کھیڈنا", "khedna", "to play", "Verbs", "u6", "بچے باہر کھیڈ رہے نیں", "bache baahar khed rahe nein", "The children are playing outside"],
    ["hospital", "ہسپتال", "haspataal", "hospital", "Places", "u6", "ہسپتال کتھے اے؟", "haspataal kithe ae?", "Where is the hospital?"],
    ["police", "پولیس", "police", "police", "People", "u6", "پولیس نوں بلاؤ", "police nu bulaao", "Call the police"],
  ],

  pcm: [
    ["this", "dis", "", "this", "Common", "u6", "Dis na my house", "", "This is my house"],
    ["that", "dat", "", "that", "Common", "u6", "Wetin be dat?", "", "What is that?"],
    ["which", "which one", "", "which", "Common", "u2", "Which one you want?", "", "Which one do you want?"],
    ["again", "again", "", "again", "Common", "u6", "Talk am again", "", "Say it again"],
    ["always", "every time", "", "always", "Time", "u4", "Mama dey cook every time", "", "Mama is always cooking"],
    ["never", "never", "", "never, not yet", "Time", "u4", "I never see am", "", "I haven't seen him yet"],
    ["maybe", "maybe", "", "maybe", "Common", "u6", "Maybe e go rain", "", "Maybe it will rain"],
    ["new", "new", "", "new", "Common", "u6", "Dis motor na new one", "", "This car is a new one"],
    ["cheap", "cheap", "", "cheap", "Common", "u6", "Dis market cheap well well", "", "This market is very cheap"],
    ["expensive", "cost", "", "expensive, costly", "Common", "u6", "Dat hotel cost well well", "", "That hotel is very expensive"],
    ["school", "school", "", "school", "Places", "u6", "Di pikin dey go school", "", "The child goes to school"],
    ["book", "book", "", "book", "Useful", "u6", "Dis book sweet", "", "This book is interesting"],
    ["fish", "fish", "", "fish", "Food", "u5", "Di fish fresh", "", "The fish is fresh"],
    ["meat", "meat", "", "meat", "Food", "u5", "I no dey chop meat", "", "I don't eat meat"],
    ["egg", "egg", "", "egg", "Food", "u5", "Give me two egg", "", "Give me two eggs"],
    ["fruit", "fruit", "", "fruit", "Food", "u5", "I like fruit well well", "", "I really like fruit"],
    ["clothes", "cloth", "", "clothes", "Useful", "u6", "My cloth don clean", "", "My clothes are clean now"],
    ["shoes", "shoe", "", "shoes", "Useful", "u6", "Where my shoe dey?", "", "Where are my shoes?"],
    ["to_learn", "learn", "", "to learn", "Verbs", "u6", "I wan learn Pidgin", "", "I want to learn Pidgin"],
    ["to_read", "read", "", "to read", "Verbs", "u6", "Papa dey read newspaper", "", "Dad is reading the newspaper"],
    ["to_return", "come back", "", "to come back", "Verbs", "u6", "When you go come back?", "", "When will you come back?"],
    ["to_find", "find", "", "to look for, to find", "Verbs", "u6", "I dey find my key", "", "I am looking for my key"],
    ["to_bring", "bring", "", "to bring", "Verbs", "u6", "Bring water come", "", "Bring some water"],
    ["to_play", "play", "", "to play", "Verbs", "u6", "Di pikin dem dey play for outside", "", "The children are playing outside"],
    ["hospital", "hospital", "", "hospital", "Places", "u6", "Where di hospital dey?", "", "Where is the hospital?"],
    ["police", "police", "", "police", "People", "u6", "Call police!", "", "Call the police!"],
  ],

  so: [
    ["this", "kan", "", "this (one)", "Common", "u7", "Kan waa guriga", "", "This is the house"],
    ["that", "kaas", "", "that (one)", "Common", "u7", "Kaas waa maxay?", "", "What is that?"],
    ["which", "kee", "", "which", "Questions", "u8", "Kee baad rabtaa?", "", "Which one do you want?"],
    ["again", "mar kale", "", "again", "Common", "u7", "Mar kale dheh", "", "Say it again"],
    ["always", "had iyo jeer", "", "always", "Time", "u8", "Hooyo had iyo jeer way karisaa", "", "Mother always cooks"],
    ["never", "weligay", "", "never (I have never)", "Time", "u8", "Weligay ma sigaar cabbin", "", "I have never smoked"],
    ["maybe", "malaha", "", "maybe", "Common", "u7", "Malaha berri", "", "Maybe tomorrow"],
    ["new", "cusub", "", "new", "Common", "u7", "Gaarigan waa cusub", "", "This car is new"],
    ["cheap", "jaban", "", "cheap", "Common", "u7", "Suuqan waa jaban", "", "This market is cheap"],
    ["expensive", "qaali", "", "expensive", "Common", "u7", "Huteelku waa qaali", "", "The hotel is expensive"],
    ["child", "ilmo", "", "child", "Family", "u4", "Ilmuhu wuu seexday", "", "The child is asleep"],
    ["school", "dugsi", "", "school", "Places", "u8", "Dugsigu wuu dhow yahay", "", "The school is near"],
    ["fish", "kalluun", "", "fish", "Food", "u6", "Kalluun baan jeclahay", "", "I like fish"],
    ["egg", "ukun", "", "egg", "Food", "u6", "Laba ukun i sii", "", "Give me two eggs"],
    ["fruit", "miro", "", "fruit", "Food", "u6", "Miro baan jeclahay", "", "I like fruit"],
    ["clothes", "dhar", "", "clothes", "Useful", "u7", "Dharku waa nadiif", "", "The clothes are clean"],
    ["shoes", "kabo", "", "shoes", "Useful", "u7", "Kabahaygu xaggee bay yaalliin?", "", "Where are my shoes?"],
    ["to_like", "jeclaan", "", "to like", "Verbs", "u7", "Shaah baan jeclahay", "", "I like tea"],
    ["to_read", "akhri", "", "to read", "Verbs", "u7", "Aabbe wargeyska wuu akhrinayaa", "", "Father is reading the newspaper"],
    ["to_listen", "dhegeyso", "", "to listen", "Verbs", "u7", "I dhegeyso", "", "Listen to me"],
    ["to_return", "soo noqo", "", "to come back", "Verbs", "u7", "Goorma ayaad soo noqonaysaa?", "", "When are you coming back?"],
    ["to_find", "hel", "", "to find", "Verbs", "u7", "Furihii waan helay", "", "I found the key"],
    ["to_bring", "keen", "", "to bring", "Verbs", "u7", "Biyo keen", "", "Bring water"],
    ["to_play", "ciyaar", "", "to play", "Verbs", "u7", "Carruurtu way ciyaarayaan", "", "The children are playing"],
    ["hospital", "isbitaal", "", "hospital", "Places", "u8", "Isbitaalku xaggee buu yaal?", "", "Where is the hospital?"],
    ["police", "booliis", "", "police", "People", "u8", "Booliiska u yeer!", "", "Call the police!"],
  ],

  ta: [
    ["this", "இது", "idhu", "this", "Common", "u7", "இது என் வீடு", "idhu en veedu", "This is my house"],
    ["that", "அது", "adhu", "that", "Common", "u7", "அது என்ன?", "adhu enna?", "What is that?"],
    ["which", "எது", "edhu", "which", "Questions", "u8", "எது உன்னுடையது?", "edhu unnudaiyadhu?", "Which one is yours?"],
    ["again", "மீண்டும்", "meendum", "again", "Common", "u7", "மீண்டும் வாருங்கள்", "meendum vaarungal", "Please come again"],
    ["always", "எப்போதும்", "eppodhum", "always", "Time", "u8", "அம்மா எப்போதும் சமைப்பார்", "amma eppodhum samaippaar", "Mother always cooks"],
    ["never", "ஒருபோதும்", "orupodhum", "never (with a negative), ever", "Time", "u8", "நான் ஒருபோதும் மறக்க மாட்டேன்", "naan orupodhum marakka maatten", "I will never forget"],
    ["maybe", "ஒருவேளை", "oruvelai", "maybe", "Common", "u7", "ஒருவேளை நாளை", "oruvelai naalai", "Maybe tomorrow"],
    ["new", "புதிய", "pudhiya", "new", "Common", "u7", "இது புதிய வீடு", "idhu pudhiya veedu", "This is a new house"],
    ["cheap", "மலிவு", "malivu", "cheap", "Common", "u7", "இது மலிவாக இருக்கிறது", "idhu malivaaga irukkiradhu", "This is cheap"],
    ["expensive", "விலை உயர்ந்த", "vilai uyarndha", "expensive", "Common", "u7", "இது விலை உயர்ந்த போன்", "idhu vilai uyarndha phone", "This is an expensive phone"],
    ["child", "குழந்தை", "kuzhandhai", "child", "Family", "u4", "குழந்தை தூங்குகிறது", "kuzhandhai thoongugiradhu", "The child is sleeping"],
    ["school", "பள்ளி", "palli", "school", "Places", "u8", "பள்ளி அருகில் இருக்கிறது", "palli arugil irukkiradhu", "The school is nearby"],
    ["meat", "இறைச்சி", "iraichi", "meat", "Food", "u6", "நான் இறைச்சி சாப்பிட மாட்டேன்", "naan iraichi saappida maatten", "I don't eat meat"],
    ["egg", "முட்டை", "muttai", "egg", "Food", "u6", "இரண்டு முட்டை கொடுங்கள்", "irandu muttai kodungal", "Give me two eggs"],
    ["clothes", "துணி", "thuni", "clothes", "Useful", "u7", "துணி சுத்தமாக இருக்கிறது", "thuni suththamaaga irukkiradhu", "The clothes are clean"],
    ["shoes", "செருப்பு", "seruppu", "shoes, footwear", "Useful", "u7", "என் செருப்பு எங்கே?", "en seruppu enge?", "Where are my shoes?"],
    ["to_like", "பிடிக்கும்", "pidikkum", "to like", "Verbs", "u7", "எனக்கு டீ பிடிக்கும்", "enakku tea pidikkum", "I like tea"],
    ["to_listen", "கேள்", "kel", "to listen, to hear", "Verbs", "u7", "தயவுசெய்து கேளுங்கள்", "thayavuseidhu kelungal", "Please listen"],
    ["to_return", "திரும்பி வா", "thirumbi vaa", "to come back", "Verbs", "u7", "சீக்கிரம் திரும்பி வா", "seekkiram thirumbi vaa", "Come back soon"],
    ["to_find", "கண்டுபிடி", "kandupidi", "to find", "Verbs", "u7", "சாவியைக் கண்டுபிடித்தேன்", "saaviyaik kandupidiththen", "I found the key"],
    ["to_bring", "கொண்டு வா", "kondu vaa", "to bring", "Verbs", "u7", "தண்ணீர் கொண்டு வா", "thanneer kondu vaa", "Bring water"],
    ["to_play", "விளையாடு", "vilaiyaadu", "to play", "Verbs", "u7", "குழந்தைகள் வெளியே விளையாடுகிறார்கள்", "kuzhandhaigal veliye vilaiyaadugiraargal", "The children are playing outside"],
    ["hospital", "மருத்துவமனை", "maruththuvamanai", "hospital", "Places", "u8", "மருத்துவமனை எங்கே?", "maruththuvamanai enge?", "Where is the hospital?"],
    ["police", "காவல்துறை", "kaavalthurai", "police", "People", "u8", "காவல்துறையை அழையுங்கள்", "kaavalthuraiyai azhaiyungal", "Call the police"],
  ],

  tl: [
    ["this", "ito", "", "this", "Common", "u7", "Ito ang bahay ko", "", "This is my house"],
    ["that", "iyan", "", "that", "Common", "u7", "Ano iyan?", "", "What is that?"],
    ["which", "alin", "", "which", "Questions", "u8", "Alin ang sa iyo?", "", "Which one is yours?"],
    ["again", "ulit", "", "again", "Common", "u7", "Sabihin mo ulit", "", "Say it again"],
    ["always", "palagi", "", "always", "Time", "u8", "Palaging nagluluto si Nanay", "", "Mother always cooks"],
    ["never", "kailanman", "", "ever, never (with hindi)", "Time", "u8", "Hindi ko ito kailanman malilimutan", "", "I will never forget this"],
    ["maybe", "siguro", "", "maybe", "Common", "u7", "Siguro bukas", "", "Maybe tomorrow"],
    ["new", "bago", "", "new", "Common", "u7", "Bago ang kotse ko", "", "My car is new"],
    ["cheap", "mura", "", "cheap", "Common", "u7", "Mura dito sa palengke", "", "It's cheap here at the market"],
    ["book", "libro", "", "book", "Useful", "u7", "Maganda ang librong ito", "", "This book is good"],
    ["meat", "karne", "", "meat", "Food", "u6", "Hindi ako kumakain ng karne", "", "I don't eat meat"],
    ["egg", "itlog", "", "egg", "Food", "u6", "Pahingi ng dalawang itlog", "", "Two eggs, please"],
    ["fruit", "prutas", "", "fruit", "Food", "u6", "Gusto ko ng prutas", "", "I like fruit"],
    ["clothes", "damit", "", "clothes", "Useful", "u7", "Malinis na ang damit", "", "The clothes are clean now"],
    ["shoes", "sapatos", "", "shoes", "Useful", "u7", "Nasaan ang sapatos ko?", "", "Where are my shoes?"],
    ["to_learn", "matuto", "", "to learn", "Verbs", "u7", "Gusto kong matuto ng Tagalog", "", "I want to learn Tagalog"],
    ["to_read", "magbasa", "", "to read", "Verbs", "u7", "Mahilig akong magbasa", "", "I love to read"],
    ["to_listen", "makinig", "", "to listen", "Verbs", "u7", "Makinig ka sa akin", "", "Listen to me"],
    ["to_return", "bumalik", "", "to come back", "Verbs", "u7", "Bumalik ka agad", "", "Come back soon"],
    ["to_find", "hanapin", "", "to look for, to find", "Verbs", "u7", "Hanapin mo ang susi", "", "Look for the key"],
    ["to_bring", "dalhin", "", "to bring", "Verbs", "u7", "Dalhin mo ang tubig", "", "Bring the water"],
    ["to_play", "maglaro", "", "to play", "Verbs", "u7", "Gusto nilang maglaro sa labas", "", "They want to play outside"],
    ["hospital", "ospital", "", "hospital", "Places", "u8", "Nasaan ang ospital?", "", "Where is the hospital?"],
    ["police", "pulis", "", "police", "People", "u8", "Tumawag ka ng pulis!", "", "Call the police!"],
  ],

  tr: [
    ["this", "bu", "", "this", "Common", "u10", "Bu benim evim", "", "This is my house"],
    ["that", "şu", "", "that", "Common", "u10", "Şu ne?", "", "What is that?"],
    ["which", "hangi", "", "which", "Common", "u10", "Hangi otobüs?", "", "Which bus?"],
    ["again", "tekrar", "", "again", "Common", "u10", "Tekrar söyler misin?", "", "Can you say it again?"],
    ["always", "her zaman", "", "always", "Time", "u9", "Annem her zaman yemek yapar", "", "My mother always cooks"],
    ["never", "asla", "", "never", "Time", "u9", "Asla unutmam", "", "I will never forget"],
    ["maybe", "belki", "", "maybe", "Common", "u10", "Belki yarın", "", "Maybe tomorrow"],
    ["cheap", "ucuz", "", "cheap", "Adjectives", "u8", "Bu pazar ucuz", "", "This market is cheap"],
    ["expensive", "pahalı", "", "expensive", "Adjectives", "u8", "Otel çok pahalı", "", "The hotel is very expensive"],
    ["egg", "yumurta", "", "egg", "Food", "u5", "İki yumurta lütfen", "", "Two eggs, please"],
    ["fruit", "meyve", "", "fruit", "Food", "u5", "Meyve severim", "", "I like fruit"],
    ["clothes", "kıyafet", "", "clothes", "Useful", "u10", "Kıyafetler temiz", "", "The clothes are clean"],
    ["shoes", "ayakkabı", "", "shoes", "Useful", "u10", "Ayakkabılarım nerede?", "", "Where are my shoes?"],
    ["to_learn", "öğrenmek", "", "to learn", "Verbs", "u6", "Türkçe öğrenmek istiyorum", "", "I want to learn Turkish"],
    ["to_listen", "dinlemek", "", "to listen", "Verbs", "u6", "Müzik dinlemek güzel", "", "Listening to music is nice"],
    ["to_return", "dönmek", "", "to come back, to return", "Verbs", "u6", "Ne zaman dönmek istiyorsun?", "", "When do you want to come back?"],
    ["to_find", "bulmak", "", "to find", "Verbs", "u6", "Anahtarı bulmak zor", "", "Finding the key is hard"],
    ["to_bring", "getirmek", "", "to bring", "Verbs", "u6", "Ekmek getirmeyi unutma", "", "Don't forget to bring bread"],
    ["to_play", "oynamak", "", "to play", "Verbs", "u6", "Çocuklar dışarıda oynamak istiyor", "", "The children want to play outside"],
    ["police", "polis", "", "police", "People", "u7", "Polisi ara!", "", "Call the police!"],
  ],

  ur: [
    ["that", "وہ", "woh", "that", "Common", "u10", "وہ آدمی ڈاکٹر ہے", "woh aadmi doctor hai", "That man is a doctor"],
    ["which", "کون سا", "kaun sa", "which", "Common", "u2", "کون سا رنگ؟", "kaun sa rang?", "Which colour?"],
    ["again", "دوبارہ", "dobara", "again", "Common", "u10", "دوبارہ بولیں", "dobara bolein", "Please say it again"],
    ["always", "ہمیشہ", "hamesha", "always", "Time", "u8", "امی ہمیشہ کھانا پکاتی ہیں", "ammi hamesha khana pakati hain", "Mom always cooks"],
    ["never", "کبھی نہیں", "kabhi nahin", "never", "Time", "u8", "میں کبھی نہیں بھولوں گا", "main kabhi nahin bhoolun ga", "I will never forget"],
    ["maybe", "شاید", "shayad", "maybe", "Common", "u10", "شاید کل", "shayad kal", "Maybe tomorrow"],
    ["cheap", "سستا", "sasta", "cheap", "Common", "u10", "یہ بہت سستا ہے", "yeh bohat sasta hai", "This is very cheap"],
    ["expensive", "مہنگا", "mehnga", "expensive", "Common", "u10", "ہوٹل مہنگا ہے", "hotel mehnga hai", "The hotel is expensive"],
    ["book", "کتاب", "kitaab", "book", "Useful", "u10", "یہ کتاب اچھی ہے", "yeh kitaab achhi hai", "This book is good"],
    ["clothes", "کپڑے", "kapray", "clothes", "Useful", "u10", "کپڑے صاف ہیں", "kapray saaf hain", "The clothes are clean"],
    ["shoes", "جوتے", "jootay", "shoes", "Useful", "u10", "میرے جوتے کہاں ہیں؟", "meray jootay kahan hain?", "Where are my shoes?"],
    ["to_like", "پسند کرنا", "pasand karna", "to like", "Verbs", "u6", "مجھے چائے پسند ہے", "mujhe chai pasand hai", "I like tea"],
    ["to_learn", "سیکھنا", "seekhna", "to learn", "Verbs", "u6", "مجھے اردو سیکھنا ہے", "mujhe urdu seekhna hai", "I want to learn Urdu"],
    ["to_return", "واپس آنا", "wapas aana", "to come back", "Verbs", "u6", "ابو کب واپس آئیں گے؟", "abbu kab wapas aayen ge?", "When will Dad come back?"],
    ["to_find", "ڈھونڈنا", "dhoondna", "to look for, to find", "Verbs", "u6", "میں چابی ڈھونڈ رہا ہوں", "main chaabi dhoond raha hoon", "I am looking for the key"],
    ["to_bring", "لانا", "laana", "to bring", "Verbs", "u6", "پانی لانا", "paani laana", "Bring water"],
    ["to_play", "کھیلنا", "khelna", "to play", "Verbs", "u6", "بچے باہر کھیل رہے ہیں", "bachay bahar khel rahay hain", "The children are playing outside"],
    ["police", "پولیس", "police", "police", "People", "u7", "پولیس کو بلاؤ", "police ko bulao", "Call the police"],
  ],

  vi: [
    ["this", "này", "", "this", "Common", "u8", "Cái này bao nhiêu tiền?", "", "How much is this?"],
    ["that", "kia", "", "that", "Common", "u8", "Cái kia là gì?", "", "What is that?"],
    ["which", "nào", "", "which", "Questions", "u2", "Bạn muốn cái nào?", "", "Which one do you want?"],
    ["again", "lại", "", "again", "Common", "u8", "Nói lại đi", "", "Say it again"],
    ["always", "luôn luôn", "", "always", "Time", "u8", "Mẹ luôn luôn nấu ăn", "", "Mother always cooks"],
    ["never", "không bao giờ", "", "never", "Time", "u8", "Tôi không bao giờ quên", "", "I never forget"],
    ["maybe", "có lẽ", "", "maybe", "Common", "u8", "Có lẽ ngày mai", "", "Maybe tomorrow"],
    ["new", "mới", "", "new", "Common", "u8", "Xe này mới", "", "This car is new"],
    ["child", "đứa trẻ", "", "child", "Family", "u3", "Đứa trẻ đang ngủ", "", "The child is sleeping"],
    ["school", "trường", "", "school", "Places", "u7", "Trường gần nhà", "", "The school is near home"],
    ["book", "sách", "", "book", "Useful", "u8", "Quyển sách này hay", "", "This book is good"],
    ["fish", "cá", "", "fish", "Food", "u5", "Cá này tươi", "", "This fish is fresh"],
    ["meat", "thịt", "", "meat", "Food", "u5", "Tôi không ăn thịt", "", "I don't eat meat"],
    ["egg", "trứng", "", "egg", "Food", "u5", "Cho tôi hai quả trứng", "", "Give me two eggs"],
    ["fruit", "trái cây", "", "fruit", "Food", "u5", "Tôi thích trái cây", "", "I like fruit"],
    ["clothes", "quần áo", "", "clothes", "Useful", "u8", "Quần áo sạch rồi", "", "The clothes are clean now"],
    ["shoes", "giày", "", "shoes", "Useful", "u8", "Giày của tôi đâu?", "", "Where are my shoes?"],
    ["to_like", "thích", "", "to like", "Verbs", "u6", "Tôi thích uống trà", "", "I like drinking tea"],
    ["to_learn", "học", "", "to learn, to study", "Verbs", "u6", "Tôi đang học tiếng Việt", "", "I am learning Vietnamese"],
    ["to_read", "đọc", "", "to read", "Verbs", "u6", "Bố đọc báo", "", "Dad reads the newspaper"],
    ["to_listen", "nghe", "", "to listen, to hear", "Verbs", "u6", "Tôi nghe nhạc", "", "I listen to music"],
    ["to_return", "về", "", "to come back, to return home", "Verbs", "u6", "Khi nào bạn về?", "", "When are you coming back?"],
    ["to_find", "tìm", "", "to find, to look for", "Verbs", "u6", "Tôi đang tìm chìa khóa", "", "I am looking for the key"],
    ["to_bring", "mang", "", "to bring, to carry", "Verbs", "u6", "Mang nước đến đây", "", "Bring water here"],
    ["to_play", "chơi", "", "to play", "Verbs", "u6", "Trẻ con chơi ở ngoài", "", "The children play outside"],
    ["hospital", "bệnh viện", "", "hospital", "Places", "u7", "Bệnh viện ở đâu?", "", "Where is the hospital?"],
    ["police", "cảnh sát", "", "police", "People", "u7", "Gọi cảnh sát!", "", "Call the police!"],
  ],

  yo: [
    ["this", "èyí", "", "this", "Common", "u8", "Èyí ni ilé mi", "", "This is my house"],
    ["that", "ìyẹn", "", "that", "Common", "u8", "Kí ni ìyẹn?", "", "What is that?"],
    ["which", "èwo", "", "which", "Questions", "u2", "Èwo lo fẹ́?", "", "Which one do you want?"],
    ["again", "lẹ́ẹ̀kan sí i", "", "again", "Common", "u8", "Sọ ọ́ lẹ́ẹ̀kan sí i", "", "Say it again"],
    ["always", "nígbà gbogbo", "", "always", "Time", "u8", "Màmá máa ń se oúnjẹ nígbà gbogbo", "", "Mother always cooks"],
    ["never", "láéláé", "", "never (with a negative), ever", "Time", "u8", "Mi ò ní gbàgbé láéláé", "", "I will never forget"],
    ["maybe", "bóyá", "", "maybe", "Common", "u8", "Bóyá ní ọ̀la", "", "Maybe tomorrow"],
    ["new", "tuntun", "", "new", "Common", "u8", "Ọkọ̀ tuntun ni", "", "It's a new car"],
    ["cheap", "pọ́ọ́kú", "", "cheap", "Common", "u8", "Ọjà yìí pọ́ọ́kú", "", "These goods are cheap"],
    ["school", "ilé ìwé", "", "school", "Places", "u7", "Ilé ìwé wà nítòsí", "", "The school is nearby"],
    ["book", "ìwé", "", "book", "Useful", "u8", "Ìwé yìí dára", "", "This book is good"],
    ["fish", "ẹja", "", "fish", "Food", "u5", "Mo fẹ́ràn ẹja", "", "I like fish"],
    ["meat", "ẹran", "", "meat", "Food", "u5", "Mi ò jẹ ẹran", "", "I don't eat meat"],
    ["egg", "ẹyin", "", "egg", "Food", "u5", "Fún mi ní ẹyin méjì", "", "Give me two eggs"],
    ["fruit", "èso", "", "fruit", "Food", "u5", "Mo fẹ́ràn èso", "", "I like fruit"],
    ["clothes", "aṣọ", "", "clothes", "Useful", "u8", "Aṣọ mi ti mọ́", "", "My clothes are clean"],
    ["shoes", "bàtà", "", "shoes", "Useful", "u8", "Níbo ni bàtà mi wà?", "", "Where are my shoes?"],
    ["to_learn", "kọ́", "", "to learn", "Verbs", "u6", "Mo fẹ́ kọ́ èdè Yorùbá", "", "I want to learn Yoruba"],
    ["to_read", "ka", "", "to read", "Verbs", "u6", "Bàbá ń ka ìwé ìròyìn", "", "Father is reading the newspaper"],
    ["to_return", "padà wá", "", "to come back", "Verbs", "u6", "Ìgbà wo lo máa padà wá?", "", "When will you come back?"],
    ["to_find", "rí", "", "to find, to see", "Verbs", "u6", "Mi ò rí kọ́kọ́rọ́ mi", "", "I can't find my key"],
    ["to_bring", "mú wá", "", "to bring", "Verbs", "u6", "Mú omi wá", "", "Bring water"],
    ["to_play", "ṣeré", "", "to play", "Verbs", "u6", "Àwọn ọmọdé ń ṣeré níta", "", "The children are playing outside"],
    ["hospital", "ilé ìwòsàn", "", "hospital", "Places", "u7", "Níbo ni ilé ìwòsàn wà?", "", "Where is the hospital?"],
    ["police", "ọlọ́pàá", "", "police", "People", "u7", "Pe ọlọ́pàá!", "", "Call the police!"],
  ],

  zh: [
    ["this", "这个", "zhège", "this", "Common", "u10", "这个多少钱？", "zhège duōshao qián?", "How much is this?"],
    ["that", "那个", "nàge", "that", "Common", "u10", "那个是什么？", "nàge shì shénme?", "What is that?"],
    ["which", "哪个", "nǎge", "which", "Common", "u2", "你要哪个？", "nǐ yào nǎge?", "Which one do you want?"],
    ["again", "再", "zài", "again", "Common", "u10", "请再说一遍", "qǐng zài shuō yí biàn", "Please say it again"],
    ["always", "总是", "zǒngshì", "always", "Time", "u8", "妈妈总是做饭", "māma zǒngshì zuòfàn", "Mom always cooks"],
    ["never", "从来不", "cónglái bù", "never", "Time", "u8", "我从来不抽烟", "wǒ cónglái bù chōuyān", "I never smoke"],
    ["maybe", "也许", "yěxǔ", "maybe", "Common", "u10", "也许明天", "yěxǔ míngtiān", "Maybe tomorrow"],
    ["new", "新", "xīn", "new", "Common", "u10", "这是新车", "zhè shì xīn chē", "This is a new car"],
    ["cheap", "便宜", "piányi", "cheap", "Common", "u10", "这个很便宜", "zhège hěn piányi", "This is very cheap"],
    ["expensive", "贵", "guì", "expensive", "Common", "u10", "酒店很贵", "jiǔdiàn hěn guì", "The hotel is expensive"],
    ["book", "书", "shū", "book", "Useful", "u10", "这本书很好看", "zhè běn shū hěn hǎokàn", "This book is good"],
    ["fish", "鱼", "yú", "fish", "Food", "u5", "我喜欢吃鱼", "wǒ xǐhuan chī yú", "I like eating fish"],
    ["fruit", "水果", "shuǐguǒ", "fruit", "Food", "u5", "我每天吃水果", "wǒ měitiān chī shuǐguǒ", "I eat fruit every day"],
    ["clothes", "衣服", "yīfu", "clothes", "Useful", "u10", "衣服干净了", "yīfu gānjìng le", "The clothes are clean now"],
    ["shoes", "鞋", "xié", "shoes", "Useful", "u10", "我的鞋在哪儿？", "wǒ de xié zài nǎr?", "Where are my shoes?"],
    ["to_learn", "学", "xué", "to learn, to study", "Verbs", "u6", "我在学中文", "wǒ zài xué zhōngwén", "I am learning Chinese"],
    ["to_return", "回来", "huílai", "to come back", "Verbs", "u6", "你什么时候回来？", "nǐ shénme shíhou huílai?", "When are you coming back?"],
    ["to_find", "找到", "zhǎodào", "to find", "Verbs", "u6", "我找到钥匙了", "wǒ zhǎodào yàoshi le", "I found the key"],
    ["to_bring", "带", "dài", "to bring, to take along", "Verbs", "u6", "别忘了带水", "bié wàng le dài shuǐ", "Don't forget to bring water"],
    ["to_play", "玩", "wán", "to play", "Verbs", "u6", "孩子们在外面玩", "háizimen zài wàimiàn wán", "The children are playing outside"],
    ["hospital", "医院", "yīyuàn", "hospital", "Places", "u7", "医院在哪儿？", "yīyuàn zài nǎr?", "Where is the hospital?"],
    ["police", "警察", "jǐngchá", "police", "People", "u7", "快叫警察！", "kuài jiào jǐngchá!", "Call the police, quick!"],
  ],
};

// A WORD THE PACK ALREADY HAS, WITH A MEANING IT WASN'T GIVEN. Four of the
// thirty concepts collided with an existing lemma, and in every case the
// existing word genuinely carries the missing meaning too — so the honest fix
// is to widen its gloss (and give it a sentence for the new sense), not to
// add the same word twice:
//   · hi वह / ur وہ are "he, she" and also "that" (वह आदमी = that man)
//   · vi kia was glossed "there, over there"; its own example is "that one"
//   · yo rí is "to see" and also "to find" (Mi ò rí … = I can't find …)
// [conceptId, lemma, glossToAdd, exNative, exTranslit, exTranslation]
// merge-core-vocab applies these idempotently: a gloss already present, or a
// sentence already there, is left alone.
export const V106_EXTEND = {
  hi: [["that", "वह", "that", "वह आदमी डॉक्टर है", "vah aadmi doctor hai", "That man is a doctor"]],
  ur: [["that", "وہ", "that", "وہ گھر بڑا ہے", "woh ghar bara hai", "That house is big"]],
  vi: [["that", "kia", "that (over there)", "", "", ""]],
  yo: [["to_find", "rí", "to find", "Mi ò rí kọ́kọ́rọ́ mi", "", "I can't find my key"]],
};

