// =============================================================================
// v109-fill.mjs — family life and the home.
//
// MEASURED, as every batch before it: ~70 more high-frequency meanings checked
// against all 21 packs. The largest gap left was the life this app's learners
// actually want the language FOR — family, and the house they meet it in:
//
//   baby, guest, neighbour, birthday, wedding, gift, kitchen, table, bed,
//   to wash, to wear, to forget, to remember, to start, to finish, to laugh,
//   ready, busy, young, early                        0/21 each
//   husband, wife 7/21 · late 1/21 · clean 1/21
//
// "Happy birthday", "the food is ready", "we have guests today", "wash your
// hands", "don't forget", "my sister's wedding is tomorrow" — the sentences a
// heritage learner hears at every family gathering and couldn't say back.
//
// 24 concepts, tier 3. Each pack gets only what it was missing: 487 rows, of
// which 483 are new words and 4 were words the pack already had under another
// meaning (see V109_EXTEND and V109_REGLOSS at the end) — in the units where
// it already keeps family, home, verbs, descriptions and time words.
//
// Fields: [conceptId, lemma, translit, translation, category, unit,
//          exNative, exTranslit, exTranslation]
//
// HONEST GLOSSES where the languages don't map one-to-one:
//   · tl asawa / tr eş are "spouse" — one word for husband and wife
//   · ko 준비 / ja 準備 are "preparation"; "ready" is 준비됐어요 / 準備ができた
//   · pa منجی is a cot — the bed a Punjabi grandmother means
//   · ja 覚える is "memorise"; "remember" in the sense of still knowing
//   · early words that also mean "quickly" (hi/ur jaldi, bn taratari, ja 早く)
//     say so
//
// CONFIDENCE: Somali and Yoruba are short and flagged for a native-speaker
// pass, as every batch's have been. Yoruba tone on wọ (to wear) especially.
// =============================================================================

export const V109_FILL = {
  ar: [
    ["baby", "رضيع", "radee'", "baby", "People", "u2", "الرضيع نائم", "ar-radee' na'im", "The baby is asleep"],
    ["guest", "ضيف", "dayf", "guest", "People", "u2", "عندنا ضيف اليوم", "indana dayf al-yawm", "We have a guest today"],
    ["neighbor", "جار", "jaar", "neighbour", "People", "u2", "جاري طيب", "jaari tayyib", "My neighbour is kind"],
    ["birthday", "عيد ميلاد", "eid milad", "birthday", "People", "u2", "عيد ميلاد سعيد", "eid milad sa'eed", "Happy birthday"],
    ["wedding", "عرس", "'urs", "wedding", "People", "u2", "العرس يوم الجمعة", "al-'urs yawm al-jum'a", "The wedding is on Friday"],
    ["gift", "هدية", "hadiyya", "gift", "People", "u2", "هذه هدية لك", "hadhihi hadiyya lak", "This is a gift for you"],
    ["kitchen", "مطبخ", "matbakh", "kitchen", "Places", "u7", "أمي في المطبخ", "ummi fil-matbakh", "My mother is in the kitchen"],
    ["table", "طاولة", "tawila", "table", "Places", "u7", "الأكل على الطاولة", "al-akl ala at-tawila", "The food is on the table"],
    ["bed", "سرير", "sareer", "bed", "Places", "u7", "السرير مريح", "as-sareer mureeh", "The bed is comfortable"],
    ["to_wash", "يغسل", "yaghsil", "to wash", "Verbs", "u6", "أخي يغسل الصحون", "akhi yaghsil as-suhun", "My brother washes the dishes"],
    ["to_wear", "يلبس", "yalbas", "to wear", "Verbs", "u6", "أبي يلبس قميصا أبيض", "abi yalbas qamisan abyad", "My father wears a white shirt"],
    ["to_forget", "ينسى", "yansa", "to forget", "Verbs", "u6", "أبي ينسى مفتاحه دائما", "abi yansa miftahahu da'iman", "My father always forgets his key"],
    ["to_remember", "يتذكر", "yatadhakkar", "to remember", "Verbs", "u6", "جدي يتذكر كل شيء", "jaddi yatadhakkar kull shay'", "My grandfather remembers everything"],
    ["to_start", "يبدأ", "yabda'", "to start, to begin", "Verbs", "u6", "الدرس يبدأ الآن", "ad-dars yabda' al-aan", "The lesson starts now"],
    ["to_finish", "ينتهي", "yantahi", "to finish, to end", "Verbs", "u6", "الفيلم ينتهي الساعة تسعة", "al-film yantahi as-sa'a tis'a", "The film ends at nine"],
    ["to_laugh", "يضحك", "yadhak", "to laugh", "Verbs", "u6", "الطفل يضحك", "at-tifl yadhak", "The child laughs"],
    ["ready", "جاهز", "jahiz", "ready", "Common", "u10", "الأكل جاهز", "al-akl jahiz", "The food is ready"],
    ["busy", "مشغول", "mashghul", "busy", "Common", "u10", "أنا مشغول اليوم", "ana mashghul al-yawm", "I am busy today"],
    ["young", "شاب", "shabb", "young, young man", "Common", "u10", "أخي شاب", "akhi shabb", "My brother is young"],
    ["clean", "نظيف", "nadheef", "clean", "Common", "u10", "البيت نظيف", "al-bayt nadheef", "The house is clean"],
    ["early", "مبكرا", "mubakkiran", "early", "Time", "u8", "أصحو مبكرا", "as-hu mubakkiran", "I wake up early"],
    ["late", "متأخر", "muta'akhkhir", "late", "Time", "u8", "أنا متأخر", "ana muta'akhkhir", "I am late"],
  ],

  bn: [
    ["baby", "শিশু", "shishu", "baby", "Family", "u3", "শিশুটা ঘুমাচ্ছে", "shishuta ghumacche", "The baby is sleeping"],
    ["guest", "অতিথি", "otithi", "guest", "Family", "u3", "আজ বাড়িতে অতিথি আসবে", "aj barite otithi ashbe", "A guest is coming home today"],
    ["neighbor", "প্রতিবেশী", "protibeshi", "neighbour", "Family", "u3", "আমাদের প্রতিবেশী খুব ভালো", "amader protibeshi khub bhalo", "Our neighbour is very nice"],
    ["birthday", "জন্মদিন", "jonmodin", "birthday", "Family", "u3", "শুভ জন্মদিন", "shubho jonmodin", "Happy birthday"],
    ["wedding", "বিয়ে", "biye", "wedding", "Family", "u3", "বোনের বিয়ে কাল", "boner biye kal", "My sister's wedding is tomorrow"],
    ["gift", "উপহার", "upohar", "gift", "Family", "u3", "এটা তোমার জন্য উপহার", "eta tomar jonno upohar", "This is a gift for you"],
    ["kitchen", "রান্নাঘর", "rannaghor", "kitchen", "Places", "u7", "মা রান্নাঘরে", "ma rannaghore", "Mother is in the kitchen"],
    ["table", "টেবিল", "tebil", "table", "Places", "u7", "খাবার টেবিলে আছে", "khabar tebile ache", "The food is on the table"],
    ["bed", "বিছানা", "bichhana", "bed", "Places", "u7", "বিছানাটা নরম", "bichhanata norom", "The bed is soft"],
    ["to_wash", "ধোয়া", "dhoya", "to wash", "Verbs", "u6", "থালা ধোয়া হয়ে গেছে", "thala dhoya hoye geche", "The plates have been washed"],
    ["to_wear", "পরা", "pora", "to wear", "Verbs", "u6", "নতুন জামা পরা ভালো লাগে", "notun jama pora bhalo lage", "I like wearing new clothes"],
    ["to_forget", "ভুলে যাওয়া", "bhule jaowa", "to forget", "Verbs", "u6", "ভুলে যাওয়া সহজ, মনে রাখা কঠিন", "bhule jaowa shohoj, mone rakha kothin", "Forgetting is easy, remembering is hard"],
    ["to_remember", "মনে রাখা", "mone rakha", "to remember", "Verbs", "u6", "কথাটা মনে রাখো", "kothata mone rakho", "Remember this"],
    ["to_start", "শুরু করা", "shuru kora", "to start, to begin", "Verbs", "u6", "কাজ শুরু করো", "kaj shuru koro", "Start the work"],
    ["to_finish", "শেষ করা", "shesh kora", "to finish", "Verbs", "u6", "খাওয়া শেষ করো", "khaoya shesh koro", "Finish eating"],
    ["to_laugh", "হাসা", "hasha", "to laugh", "Verbs", "u6", "হাসা ভালো", "hasha bhalo", "Laughing is good"],
    ["ready", "তৈরি", "toiri", "ready", "Common", "u10", "খাবার তৈরি", "khabar toiri", "The food is ready"],
    ["busy", "ব্যস্ত", "byosto", "busy", "Common", "u10", "আমি আজ ব্যস্ত", "ami aj byosto", "I am busy today"],
    ["young", "তরুণ", "torun", "young", "Common", "u10", "তিনি খুব তরুণ", "tini khub torun", "He is very young"],
    ["clean", "পরিষ্কার", "porishkar", "clean", "Common", "u10", "ঘরটা পরিষ্কার", "ghorta porishkar", "The room is clean"],
    ["early", "তাড়াতাড়ি", "taratari", "early, quickly", "Time", "u8", "কাল তাড়াতাড়ি এসো", "kal taratari esho", "Come early tomorrow"],
    ["late", "দেরি", "deri", "late, delay", "Time", "u8", "আমার দেরি হয়ে গেছে", "amar deri hoye geche", "I'm late"],
  ],

  de: [
    ["baby", "das Baby", "", "baby", "Family", "u3", "Das Baby schläft", "", "The baby is sleeping"],
    ["guest", "der Gast", "", "guest", "Family", "u3", "Der Gast ist da", "", "The guest is here"],
    ["neighbor", "der Nachbar", "", "neighbour", "Family", "u3", "Der Nachbar ist nett", "", "The neighbour is nice"],
    ["birthday", "der Geburtstag", "", "birthday", "Family", "u3", "Der Geburtstag ist morgen", "", "The birthday is tomorrow"],
    ["wedding", "die Hochzeit", "", "wedding", "Family", "u3", "Die Hochzeit ist im Mai", "", "The wedding is in May"],
    ["gift", "das Geschenk", "", "gift, present", "Family", "u3", "Das Geschenk ist für dich", "", "The gift is for you"],
    ["kitchen", "die Küche", "", "kitchen", "Places", "u7", "Die Küche ist groß", "", "The kitchen is big"],
    ["table", "der Tisch", "", "table", "Places", "u7", "Der Tisch ist neu", "", "The table is new"],
    ["bed", "das Bett", "", "bed", "Places", "u7", "Das Bett ist bequem", "", "The bed is comfortable"],
    ["to_wash", "waschen", "", "to wash", "Verbs", "u6", "Ich muss die Wäsche waschen", "", "I have to wash the laundry"],
    ["to_wear", "tragen", "", "to wear, to carry", "Verbs", "u6", "Sie will ein Kleid tragen", "", "She wants to wear a dress"],
    ["to_forget", "vergessen", "", "to forget", "Verbs", "u6", "Ich will das nicht vergessen", "", "I don't want to forget that"],
    ["to_remember", "erinnern", "", "to remember (sich erinnern)", "Verbs", "u6", "Kannst du dich erinnern?", "", "Can you remember?"],
    ["to_start", "anfangen", "", "to start, to begin", "Verbs", "u6", "Wir können jetzt anfangen", "", "We can start now"],
    ["to_finish", "beenden", "", "to finish, to end", "Verbs", "u6", "Ich muss die Arbeit beenden", "", "I have to finish the work"],
    ["to_laugh", "lachen", "", "to laugh", "Verbs", "u6", "Die Kinder lachen viel", "", "The children laugh a lot"],
    ["ready", "fertig", "", "ready, finished", "Common", "u13", "Das Essen ist fertig", "", "The food is ready"],
    ["busy", "beschäftigt", "", "busy", "Common", "u13", "Ich bin heute beschäftigt", "", "I am busy today"],
    ["young", "jung", "", "young", "Common", "u13", "Meine Oma ist jung geblieben", "", "My grandma has stayed young"],
    ["clean", "sauber", "", "clean", "Common", "u13", "Die Küche ist sauber", "", "The kitchen is clean"],
    ["early", "früh", "", "early", "Time", "u8", "Ich stehe früh auf", "", "I get up early"],
    ["late", "spät", "", "late", "Time", "u8", "Es ist schon spät", "", "It's already late"],
  ],

  es: [
    ["baby", "el bebé", "", "baby", "Family", "u3", "El bebé está durmiendo", "", "The baby is sleeping"],
    ["guest", "el invitado", "", "guest", "Family", "u3", "El invitado ya llegó", "", "The guest has arrived"],
    ["neighbor", "el vecino", "", "neighbour", "Family", "u3", "El vecino es muy amable", "", "The neighbour is very kind"],
    ["birthday", "el cumpleaños", "", "birthday", "Family", "u3", "El cumpleaños es mañana", "", "The birthday is tomorrow"],
    ["wedding", "la boda", "", "wedding", "Family", "u3", "La boda es en junio", "", "The wedding is in June"],
    ["gift", "el regalo", "", "gift, present", "Family", "u3", "El regalo es para ti", "", "The gift is for you"],
    ["kitchen", "la cocina", "", "kitchen", "Places", "u7", "La cocina está limpia", "", "The kitchen is clean"],
    ["table", "la mesa", "", "table", "Places", "u7", "La comida está en la mesa", "", "The food is on the table"],
    ["bed", "la cama", "", "bed", "Places", "u7", "La cama es cómoda", "", "The bed is comfortable"],
    ["to_wash", "lavar", "", "to wash", "Verbs", "u6", "Tengo que lavar los platos", "", "I have to wash the dishes"],
    ["to_wear", "llevar", "", "to wear, to carry", "Verbs", "u6", "Quiero llevar el vestido azul", "", "I want to wear the blue dress"],
    ["to_forget", "olvidar", "", "to forget", "Verbs", "u6", "No quiero olvidar tu cumpleaños", "", "I don't want to forget your birthday"],
    ["to_remember", "recordar", "", "to remember", "Verbs", "u6", "¿Puedes recordar su nombre?", "", "Can you remember his name?"],
    ["to_start", "empezar", "", "to start, to begin", "Verbs", "u6", "Vamos a empezar", "", "Let's start"],
    ["to_finish", "terminar", "", "to finish", "Verbs", "u6", "Tengo que terminar la tarea", "", "I have to finish the homework"],
    ["to_laugh", "reír", "", "to laugh", "Verbs", "u6", "Me gusta reír con mi familia", "", "I like laughing with my family"],
    ["ready", "listo", "", "ready", "Common", "u13", "¿Estás listo para salir?", "", "Are you ready to go out?"],
    ["busy", "ocupado", "", "busy", "Common", "u13", "Estoy ocupado hoy", "", "I'm busy today"],
    ["young", "joven", "", "young", "Common", "u13", "Mi tía es muy joven", "", "My aunt is very young"],
    ["clean", "limpio", "", "clean", "Common", "u13", "El cuarto está limpio", "", "The room is clean"],
    ["early", "temprano", "", "early", "Time", "u8", "Me levanto temprano", "", "I get up early"],
  ],

  fa: [
    ["baby", "نوزاد", "nowzâd", "baby", "Family", "u4", "نوزاد خواب است", "nowzâd khâb ast", "The baby is asleep"],
    ["husband", "شوهر", "showhar", "husband", "Family", "u4", "شوهرم معلم است", "showharam mo'allem ast", "My husband is a teacher"],
    ["wife", "همسر", "hamsar", "wife, spouse", "Family", "u4", "همسرم پزشک است", "hamsaram pezeshk ast", "My wife is a doctor"],
    ["guest", "مهمان", "mehmân", "guest", "Family", "u4", "امشب مهمان داریم", "emshab mehmân dârim", "We have guests tonight"],
    ["neighbor", "همسایه", "hamsâye", "neighbour", "Family", "u4", "همسایه ما مهربان است", "hamsâye-ye mâ mehrabân ast", "Our neighbour is kind"],
    ["birthday", "تولد", "tavallod", "birthday", "Family", "u4", "تولدت مبارک", "tavallodat mobârak", "Happy birthday"],
    ["wedding", "عروسی", "arusi", "wedding", "Family", "u4", "عروسی خواهرم فرداست", "arusi-ye khâharam fardâst", "My sister's wedding is tomorrow"],
    ["gift", "هدیه", "hediye", "gift", "Family", "u4", "این هدیه برای توست", "in hediye barâye tost", "This gift is for you"],
    ["kitchen", "آشپزخانه", "âshpazkhâne", "kitchen", "Common", "u7", "مادرم در آشپزخانه است", "mâdaram dar âshpazkhâne ast", "My mother is in the kitchen"],
    ["table", "میز", "miz", "table", "Common", "u7", "غذا روی میز است", "ghazâ ru-ye miz ast", "The food is on the table"],
    ["bed", "تخت", "takht", "bed", "Common", "u7", "تخت راحت است", "takht râhat ast", "The bed is comfortable"],
    ["to_wash", "شستن", "shostan", "to wash", "Verbs", "u7", "شستن ظرف‌ها با من", "shostan-e zarfhâ bâ man", "Washing the dishes is on me"],
    ["to_wear", "پوشیدن", "pushidan", "to wear", "Verbs", "u7", "پوشیدن لباس گرم لازم است", "pushidan-e lebâs-e garm lâzem ast", "Wearing warm clothes is necessary"],
    ["to_forget", "فراموش کردن", "farâmush kardan", "to forget", "Verbs", "u7", "اسمش را فراموش کردم", "esmash râ farâmush kardam", "I forgot his name"],
    ["to_remember", "یاد داشتن", "yâd dâshtan", "to remember", "Verbs", "u7", "یاد داشتن اسم‌ها سخت است", "yâd dâshtan-e esmhâ sakht ast", "Remembering names is hard"],
    ["to_start", "شروع کردن", "shoru' kardan", "to start, to begin", "Verbs", "u7", "کار را شروع کردم", "kâr râ shoru' kardam", "I started the work"],
    ["to_finish", "تمام کردن", "tamâm kardan", "to finish", "Verbs", "u7", "کارم را تمام کردم", "kâram râ tamâm kardam", "I finished my work"],
    ["to_laugh", "خندیدن", "khandidan", "to laugh", "Verbs", "u7", "خندیدن برای سلامتی خوب است", "khandidan barâye salâmati khub ast", "Laughing is good for your health"],
    ["ready", "آماده", "âmâde", "ready", "Common", "u7", "غذا آماده است", "ghazâ âmâde ast", "The food is ready"],
    ["busy", "مشغول", "mashghul", "busy", "Common", "u7", "امروز مشغولم", "emruz mashghulam", "I'm busy today"],
    ["young", "جوان", "javân", "young", "Common", "u7", "او خیلی جوان است", "u kheyli javân ast", "He is very young"],
    ["clean", "تمیز", "tamiz", "clean", "Common", "u7", "اتاق تمیز است", "otâgh tamiz ast", "The room is clean"],
    ["early", "زود", "zud", "early", "Time", "u8", "فردا زود بیا", "fardâ zud biyâ", "Come early tomorrow"],
    ["late", "دیر", "dir", "late", "Time", "u8", "دیر شد", "dir shod", "It got late"],
  ],

  fr: [
    ["baby", "le bébé", "", "baby", "Family", "u3", "Le bébé dort", "", "The baby is sleeping"],
    ["guest", "l'invité", "", "guest", "Family", "u3", "L'invité est arrivé", "", "The guest has arrived"],
    ["neighbor", "le voisin", "", "neighbour", "Family", "u3", "Le voisin est gentil", "", "The neighbour is kind"],
    ["birthday", "l'anniversaire", "", "birthday", "Family", "u3", "L'anniversaire est demain", "", "The birthday is tomorrow"],
    ["wedding", "le mariage", "", "wedding", "Family", "u3", "Le mariage est en juin", "", "The wedding is in June"],
    ["gift", "le cadeau", "", "gift, present", "Family", "u3", "Le cadeau est pour toi", "", "The gift is for you"],
    ["kitchen", "la cuisine", "", "kitchen", "Places", "u7", "La cuisine est propre", "", "The kitchen is clean"],
    ["table", "la table", "", "table", "Places", "u7", "Le repas est sur la table", "", "The meal is on the table"],
    ["bed", "le lit", "", "bed", "Places", "u7", "Le lit est confortable", "", "The bed is comfortable"],
    ["to_wash", "laver", "", "to wash", "Verbs", "u6", "Je dois laver la vaisselle", "", "I have to wash the dishes"],
    ["to_wear", "porter", "", "to wear, to carry", "Verbs", "u6", "Elle veut porter sa robe bleue", "", "She wants to wear her blue dress"],
    ["to_forget", "oublier", "", "to forget", "Verbs", "u6", "Je ne veux pas oublier", "", "I don't want to forget"],
    ["to_remember", "se souvenir", "", "to remember", "Verbs", "u6", "Il faut se souvenir de tout", "", "You have to remember everything"],
    ["to_start", "commencer", "", "to start, to begin", "Verbs", "u6", "On peut commencer", "", "We can start"],
    ["to_finish", "finir", "", "to finish", "Verbs", "u6", "Je dois finir mon travail", "", "I have to finish my work"],
    ["to_laugh", "rire", "", "to laugh", "Verbs", "u6", "Les enfants aiment rire", "", "The children love to laugh"],
    ["ready", "prêt", "", "ready", "Common", "u13", "Le dîner est prêt", "", "Dinner is ready"],
    ["busy", "occupé", "", "busy", "Common", "u13", "Je suis occupé aujourd'hui", "", "I'm busy today"],
    ["young", "jeune", "", "young", "Common", "u13", "Ma tante est très jeune", "", "My aunt is very young"],
    ["clean", "propre", "", "clean", "Common", "u13", "La chambre est propre", "", "The room is clean"],
    ["early", "tôt", "", "early", "Time", "u8", "Je me lève tôt", "", "I get up early"],
    ["late", "tard", "", "late", "Time", "u8", "Il est tard", "", "It's late"],
  ],

  hi: [
    ["baby", "शिशु", "shishu", "baby", "People", "u2", "शिशु सो रहा है", "shishu so raha hai", "The baby is sleeping"],
    ["guest", "मेहमान", "mehmaan", "guest", "People", "u2", "आज घर में मेहमान हैं", "aaj ghar mein mehmaan hain", "There are guests at home today"],
    ["neighbor", "पड़ोसी", "padosi", "neighbour", "People", "u2", "हमारे पड़ोसी अच्छे हैं", "hamare padosi achchhe hain", "Our neighbours are nice"],
    ["birthday", "जन्मदिन", "janmadin", "birthday", "People", "u2", "जन्मदिन मुबारक", "janmadin mubarak", "Happy birthday"],
    ["wedding", "शादी", "shaadi", "wedding, marriage", "People", "u2", "दीदी की शादी कल है", "didi ki shaadi kal hai", "My sister's wedding is tomorrow"],
    ["gift", "तोहफ़ा", "tohfa", "gift", "People", "u2", "यह तोहफ़ा तुम्हारे लिए है", "yeh tohfa tumhare liye hai", "This gift is for you"],
    ["kitchen", "रसोई", "rasoi", "kitchen", "Places", "u7", "माँ रसोई में हैं", "maa rasoi mein hain", "Mother is in the kitchen"],
    ["table", "मेज़", "mez", "table", "Places", "u7", "खाना मेज़ पर है", "khana mez par hai", "The food is on the table"],
    ["bed", "बिस्तर", "bistar", "bed", "Places", "u7", "बिस्तर आरामदायक है", "bistar aaramdayak hai", "The bed is comfortable"],
    ["to_wash", "धोना", "dhona", "to wash", "Verbs", "u6", "मुझे बर्तन धोना है", "mujhe bartan dhona hai", "I have to wash the dishes"],
    ["to_wear", "पहनना", "pahanna", "to wear", "Verbs", "u6", "आज साड़ी पहनना है", "aaj saadi pahanna hai", "I want to wear a sari today"],
    ["to_forget", "भूलना", "bhoolna", "to forget", "Verbs", "u6", "मैं नाम भूल गया", "main naam bhool gaya", "I forgot the name"],
    ["to_remember", "याद रखना", "yaad rakhna", "to remember", "Verbs", "u6", "यह बात याद रखना", "yeh baat yaad rakhna", "Remember this"],
    ["to_start", "शुरू करना", "shuru karna", "to start, to begin", "Verbs", "u6", "काम शुरू करो", "kaam shuru karo", "Start the work"],
    ["to_finish", "ख़त्म करना", "khatm karna", "to finish", "Verbs", "u6", "खाना ख़त्म करो", "khana khatm karo", "Finish your food"],
    ["to_laugh", "हँसना", "hansna", "to laugh", "Verbs", "u6", "बच्चे हँस रहे हैं", "bachche hans rahe hain", "The children are laughing"],
    ["ready", "तैयार", "taiyaar", "ready", "Common", "u10", "क्या तुम तैयार हो?", "kya tum taiyaar ho?", "Are you ready?"],
    ["busy", "व्यस्त", "vyast", "busy", "Common", "u10", "मैं आज व्यस्त हूँ", "main aaj vyast hoon", "I am busy today"],
    ["young", "जवान", "javaan", "young", "Common", "u10", "मेरी मौसी जवान हैं", "meri mausi javaan hain", "My aunt is young"],
    ["clean", "साफ़", "saaf", "clean", "Common", "u10", "कमरा साफ़ है", "kamra saaf hai", "The room is clean"],
    ["early", "जल्दी", "jaldi", "early, quickly", "Time", "u8", "कल जल्दी आना", "kal jaldi aana", "Come early tomorrow"],
    ["late", "देर", "der", "late, delay", "Time", "u8", "मुझे देर हो गई", "mujhe der ho gayi", "I'm late"],
  ],

  id: [
    ["baby", "bayi", "", "baby", "Family", "u3", "Bayi itu sedang tidur", "", "The baby is sleeping"],
    ["husband", "suami", "", "husband", "Family", "u3", "Suami saya dokter", "", "My husband is a doctor"],
    ["wife", "istri", "", "wife", "Family", "u3", "Istri saya guru", "", "My wife is a teacher"],
    ["guest", "tamu", "", "guest", "Family", "u3", "Ada tamu di rumah", "", "There's a guest at home"],
    ["neighbor", "tetangga", "", "neighbour", "Family", "u3", "Tetangga kami baik", "", "Our neighbours are kind"],
    ["birthday", "ulang tahun", "", "birthday", "Family", "u3", "Selamat ulang tahun", "", "Happy birthday"],
    ["wedding", "pernikahan", "", "wedding", "Family", "u3", "Pernikahan kakak saya besok", "", "My sister's wedding is tomorrow"],
    ["gift", "hadiah", "", "gift", "Family", "u3", "Ini hadiah untukmu", "", "This is a gift for you"],
    ["kitchen", "dapur", "", "kitchen", "Common", "u5", "Ibu ada di dapur", "", "Mother is in the kitchen"],
    ["table", "meja", "", "table", "Common", "u5", "Makanan ada di meja", "", "The food is on the table"],
    ["bed", "tempat tidur", "", "bed", "Common", "u5", "Tempat tidurnya nyaman", "", "The bed is comfortable"],
    ["to_wash", "mencuci", "", "to wash", "Verbs", "u6", "Saya mencuci piring", "", "I wash the dishes"],
    ["to_wear", "memakai", "", "to wear", "Verbs", "u6", "Dia memakai baju merah", "", "She is wearing a red top"],
    ["to_forget", "lupa", "", "to forget", "Verbs", "u6", "Saya lupa namanya", "", "I forgot his name"],
    ["to_remember", "ingat", "", "to remember", "Verbs", "u6", "Kamu ingat saya?", "", "Do you remember me?"],
    ["to_start", "mulai", "", "to start, to begin", "Verbs", "u6", "Kita mulai sekarang", "", "We start now"],
    ["to_finish", "selesai", "", "to finish, finished", "Verbs", "u6", "Saya sudah selesai", "", "I've finished"],
    ["to_laugh", "tertawa", "", "to laugh", "Verbs", "u6", "Anak-anak tertawa", "", "The children are laughing"],
    ["ready", "siap", "", "ready", "Common", "u6", "Makanan sudah siap", "", "The food is ready"],
    ["busy", "sibuk", "", "busy", "Common", "u6", "Saya sibuk hari ini", "", "I'm busy today"],
    ["young", "muda", "", "young", "Common", "u6", "Tante saya masih muda", "", "My aunt is still young"],
    ["clean", "bersih", "", "clean", "Common", "u6", "Kamarnya bersih", "", "The room is clean"],
    ["early", "awal", "", "early, beginning", "Time", "u5", "Besok datang lebih awal", "", "Come earlier tomorrow"],
    ["late", "terlambat", "", "late", "Time", "u5", "Maaf, saya terlambat", "", "Sorry, I'm late"],
  ],

  ja: [
    ["baby", "赤ちゃん", "akachan", "baby", "People", "u2", "赤ちゃんが寝ています", "akachan ga nete imasu", "The baby is sleeping"],
    ["husband", "夫", "otto", "husband", "People", "u2", "夫は先生です", "otto wa sensei desu", "My husband is a teacher"],
    ["wife", "妻", "tsuma", "wife", "People", "u2", "妻は医者です", "tsuma wa isha desu", "My wife is a doctor"],
    ["guest", "お客さん", "okyakusan", "guest", "People", "u2", "今日はお客さんが来ます", "kyou wa okyakusan ga kimasu", "Guests are coming today"],
    ["neighbor", "隣の人", "tonari no hito", "neighbour", "People", "u2", "隣の人は親切です", "tonari no hito wa shinsetsu desu", "The neighbour is kind"],
    ["birthday", "誕生日", "tanjoubi", "birthday", "People", "u2", "誕生日おめでとう", "tanjoubi omedetou", "Happy birthday"],
    ["wedding", "結婚式", "kekkonshiki", "wedding", "People", "u2", "姉の結婚式は明日です", "ane no kekkonshiki wa ashita desu", "My sister's wedding is tomorrow"],
    ["gift", "プレゼント", "purezento", "gift, present", "People", "u2", "これはプレゼントです", "kore wa purezento desu", "This is a present"],
    ["kitchen", "台所", "daidokoro", "kitchen", "Places", "u7", "母は台所にいます", "haha wa daidokoro ni imasu", "My mother is in the kitchen"],
    ["table", "テーブル", "teeburu", "table", "Places", "u7", "ご飯はテーブルの上です", "gohan wa teeburu no ue desu", "The food is on the table"],
    ["bed", "ベッド", "beddo", "bed", "Places", "u7", "ベッドは大きいです", "beddo wa ookii desu", "The bed is big"],
    ["to_wash", "洗う", "arau", "to wash", "Verbs", "u6", "手を洗う", "te wo arau", "Wash your hands"],
    ["to_wear", "着る", "kiru", "to wear (clothes)", "Verbs", "u6", "着物を着る", "kimono wo kiru", "I wear a kimono"],
    ["to_forget", "忘れる", "wasureru", "to forget", "Verbs", "u6", "忘れるな", "wasureru na", "Don't forget"],
    ["to_remember", "覚える", "oboeru", "to remember, to memorise", "Verbs", "u6", "新しい単語を覚える", "atarashii tango wo oboeru", "I memorise new words"],
    ["to_start", "始める", "hajimeru", "to start, to begin", "Verbs", "u6", "仕事を始める", "shigoto wo hajimeru", "I start work"],
    ["to_finish", "終わる", "owaru", "to finish, to end", "Verbs", "u6", "授業は三時に終わる", "jugyou wa sanji ni owaru", "Class finishes at three"],
    ["to_laugh", "笑う", "warau", "to laugh", "Verbs", "u6", "子供たちはよく笑う", "kodomotachi wa yoku warau", "The children laugh a lot"],
    ["ready", "準備", "junbi", "ready, preparation", "Common", "u10", "準備ができました", "junbi ga dekimashita", "I'm ready"],
    ["busy", "忙しい", "isogashii", "busy", "Common", "u10", "今日は忙しいです", "kyou wa isogashii desu", "I'm busy today"],
    ["young", "若い", "wakai", "young", "Common", "u10", "叔母は若いです", "oba wa wakai desu", "My aunt is young"],
    ["early", "早く", "hayaku", "early, quickly", "Time", "u8", "明日は早く来てください", "ashita wa hayaku kite kudasai", "Please come early tomorrow"],
    ["late", "遅い", "osoi", "late, slow", "Time", "u8", "もう遅いです", "mou osoi desu", "It's already late"],
  ],

  ko: [
    ["baby", "아기", "agi", "baby", "Family", "u3", "아기가 자요", "agiga jayo", "The baby is sleeping"],
    ["husband", "남편", "nampyeon", "husband", "Family", "u3", "남편은 선생님이에요", "nampyeoneun seonsaengnimieyo", "My husband is a teacher"],
    ["wife", "아내", "anae", "wife", "Family", "u3", "아내는 의사예요", "anaeneun uisayeyo", "My wife is a doctor"],
    ["guest", "손님", "sonnim", "guest", "Family", "u3", "오늘 손님이 와요", "oneul sonnimi wayo", "A guest is coming today"],
    ["neighbor", "이웃 사람", "iut saram", "neighbour", "Family", "u3", "이웃 사람이 친절해요", "iut sarami chinjeolhaeyo", "The neighbour is kind"],
    ["birthday", "생일", "saengil", "birthday", "Family", "u3", "생일 축하해요", "saengil chukahaeyo", "Happy birthday"],
    ["wedding", "결혼식", "gyeolhonsik", "wedding", "Family", "u3", "언니 결혼식은 내일이에요", "eonni gyeolhonsigeun naeirieyo", "My sister's wedding is tomorrow"],
    ["gift", "선물", "seonmul", "gift, present", "Family", "u3", "이건 선물이에요", "igeon seonmurieyo", "This is a gift"],
    ["kitchen", "부엌", "bueok", "kitchen", "Places", "u7", "엄마는 부엌에 있어요", "eommaneun bueoge isseoyo", "Mom is in the kitchen"],
    ["table", "식탁", "siktak", "table (dining)", "Places", "u7", "밥이 식탁 위에 있어요", "babi siktak wie isseoyo", "The food is on the table"],
    ["bed", "침대", "chimdae", "bed", "Places", "u7", "침대가 편해요", "chimdaega pyeonhaeyo", "The bed is comfortable"],
    ["to_wash", "씻다", "ssitda", "to wash", "Verbs", "u6", "손을 씻다가 전화를 받았어요", "soneul ssitdaga jeonhwareul badasseoyo", "I answered the phone while washing my hands"],
    ["to_wear", "입다", "ipda", "to wear (clothes)", "Verbs", "u6", "옷을 입다가 늦었어요", "oseul ipdaga neujeosseoyo", "I was late getting dressed"],
    ["to_forget", "잊어버리다", "ijeobeorida", "to forget", "Verbs", "u6", "이름을 잊어버렸어요", "ireumeul ijeobeoryeosseoyo", "I forgot the name"],
    ["to_remember", "기억하다", "gieokhada", "to remember", "Verbs", "u6", "이 말을 기억하세요", "i mareul gieokhaseyo", "Remember these words"],
    ["to_start", "시작하다", "sijakhada", "to start, to begin", "Verbs", "u6", "지금 시작하세요", "jigeum sijakhaseyo", "Start now"],
    ["to_finish", "끝내다", "kkeunnaeda", "to finish", "Verbs", "u6", "일을 끝내다가 잠들었어요", "ireul kkeunnaedaga jamdeureosseoyo", "I fell asleep while finishing work"],
    ["to_laugh", "웃다", "utda", "to laugh", "Verbs", "u6", "웃다가 울었어요", "utdaga ureosseoyo", "I laughed until I cried"],
    ["ready", "준비", "junbi", "ready, preparation", "Common", "u10", "준비됐어요", "junbidwaesseoyo", "I'm ready"],
    ["busy", "바쁘다", "bappeuda", "busy", "Common", "u10", "오늘은 정말 바쁘다", "oneureun jeongmal bappeuda", "I'm really busy today"],
    ["young", "젊다", "jeomda", "young", "Common", "u10", "이모는 아직 젊다", "imoneun ajik jeomda", "My aunt is still young"],
    ["clean", "깨끗하다", "kkaekkeuthada", "clean", "Common", "u10", "방이 아주 깨끗하다", "bangi aju kkaekkeuthada", "The room is very clean"],
    ["early", "일찍", "iljjik", "early", "Time", "u8", "내일 일찍 오세요", "naeil iljjik oseyo", "Come early tomorrow"],
    ["late", "늦다", "neutda", "late, to be late", "Time", "u8", "늦다고 연락했어요", "neutdago yeollakhaesseoyo", "I let them know I'd be late"],
  ],

  ml: [
    ["baby", "കുഞ്ഞ്", "kunju", "baby", "Family", "u4", "കുഞ്ഞ് ഉറങ്ങുന്നു", "kunju urangunnu", "The baby is sleeping"],
    ["husband", "ഭർത്താവ്", "bharthaavu", "husband", "Family", "u4", "എന്റെ ഭർത്താവ് അധ്യാപകനാണ്", "ente bharthaavu adhyaapakanaanu", "My husband is a teacher"],
    ["wife", "ഭാര്യ", "bhaarya", "wife", "Family", "u4", "എന്റെ ഭാര്യ ഡോക്ടറാണ്", "ente bhaarya doctoraanu", "My wife is a doctor"],
    ["guest", "അതിഥി", "athithi", "guest", "Family", "u4", "ഇന്ന് വീട്ടിൽ അതിഥി വരും", "innu veettil athithi varum", "A guest is coming home today"],
    ["neighbor", "അയൽക്കാരൻ", "ayalkkaaran", "neighbour", "Family", "u4", "ഞങ്ങളുടെ അയൽക്കാരൻ നല്ലവനാണ്", "njangalude ayalkkaaran nallavanaanu", "Our neighbour is a good man"],
    ["birthday", "പിറന്നാൾ", "pirannaal", "birthday", "Family", "u4", "പിറന്നാൾ ആശംസകൾ", "pirannaal aashamsakal", "Happy birthday"],
    ["wedding", "കല്യാണം", "kalyaanam", "wedding", "Family", "u4", "ചേച്ചിയുടെ കല്യാണം നാളെയാണ്", "chechiyude kalyaanam naaleyaanu", "My sister's wedding is tomorrow"],
    ["gift", "സമ്മാനം", "sammaanam", "gift", "Family", "u4", "ഇത് നിനക്കുള്ള സമ്മാനമാണ്", "ithu ninakkulla sammaanamaanu", "This is a gift for you"],
    ["kitchen", "അടുക്കള", "adukkala", "kitchen", "Common", "u7", "അമ്മ അടുക്കളയിലാണ്", "amma adukkalayilaanu", "Mother is in the kitchen"],
    ["table", "മേശ", "mesha", "table", "Common", "u7", "ഭക്ഷണം മേശപ്പുറത്തുണ്ട്", "bhakshanam meshappurathundu", "The food is on the table"],
    ["bed", "കട്ടിൽ", "kattil", "bed", "Common", "u7", "കട്ടിൽ സുഖമുള്ളതാണ്", "kattil sukhamullathaanu", "The bed is comfortable"],
    ["to_wash", "കഴുകുക", "kazhukuka", "to wash", "Verbs", "u7", "ഞാൻ പാത്രം കഴുകുന്നു", "njaan paathram kazhukunnu", "I am washing the dishes"],
    ["to_wear", "ധരിക്കുക", "dharikkuka", "to wear", "Verbs", "u7", "അവൾ സാരി ധരിക്കുന്നു", "aval saari dharikkunnu", "She is wearing a sari"],
    ["to_forget", "മറക്കുക", "marakkuka", "to forget", "Verbs", "u7", "ഇത് മറക്കരുത്", "ithu marakkaruthu", "Don't forget this"],
    ["to_remember", "ഓർക്കുക", "orkkuka", "to remember", "Verbs", "u7", "ഞാൻ അത് ഓർക്കുന്നു", "njaan athu orkkunnu", "I remember that"],
    ["to_start", "തുടങ്ങുക", "thudanguka", "to start, to begin", "Verbs", "u7", "ക്ലാസ് തുടങ്ങുന്നു", "class thudangunnu", "The class is starting"],
    ["to_finish", "തീർക്കുക", "theerkkuka", "to finish", "Verbs", "u7", "ജോലി തീർക്കുന്നു", "joli theerkkunnu", "I am finishing the work"],
    ["to_laugh", "ചിരിക്കുക", "chirikkuka", "to laugh", "Verbs", "u7", "കുട്ടികൾ ചിരിക്കുന്നു", "kuttikal chirikkunnu", "The children are laughing"],
    ["ready", "തയ്യാർ", "thayyaar", "ready", "Common", "u7", "ഭക്ഷണം തയ്യാറാണ്", "bhakshanam thayyaaraanu", "The food is ready"],
    ["busy", "തിരക്ക്", "thirakku", "busy, rush", "Common", "u7", "ഇന്ന് എനിക്ക് തിരക്കാണ്", "innu enikku thirakkaanu", "I'm busy today"],
    ["young", "ചെറുപ്പം", "cheruppam", "young, youth", "Common", "u7", "അമ്മായി ഇപ്പോഴും ചെറുപ്പമാണ്", "ammaayi ippozhum cheruppamaanu", "My aunt is still young"],
    ["clean", "വൃത്തി", "vruthi", "clean, cleanliness", "Common", "u7", "മുറി വൃത്തിയാണ്", "muri vruthiyaanu", "The room is clean"],
    ["early", "നേരത്തെ", "nerathe", "early", "Time", "u8", "നാളെ നേരത്തെ വരൂ", "naale nerathe varoo", "Come early tomorrow"],
    ["late", "വൈകി", "vaiki", "late", "Time", "u8", "ഞാൻ വൈകി", "njaan vaiki", "I'm late"],
  ],

  pa: [
    ["baby", "نیانا", "nyaana", "baby, small child", "Family", "u3", "نیانا سوں رہیا اے", "nyaana saun rehya ae", "The baby is sleeping"],
    ["husband", "گھر والا", "ghar wala", "husband", "Family", "u3", "میرا گھر والا استاد اے", "mera ghar wala ustaad ae", "My husband is a teacher"],
    ["wife", "گھر والی", "ghar wali", "wife", "Family", "u3", "میری گھر والی ڈاکٹر اے", "meri ghar wali doctor ae", "My wife is a doctor"],
    ["guest", "پروہنا", "prauhna", "guest", "Family", "u3", "اج پروہنے آ رہے نیں", "aj prauhne aa rahe nein", "Guests are coming today"],
    ["neighbor", "گوانڈی", "guaandi", "neighbour", "Family", "u3", "ساڈے گوانڈی چنگے نیں", "saade guaandi change nein", "Our neighbours are good"],
    ["birthday", "جنم دن", "janam din", "birthday", "Family", "u3", "جنم دن مبارک", "janam din mubarak", "Happy birthday"],
    ["wedding", "ویاہ", "viyah", "wedding", "Family", "u3", "بھین دا ویاہ کل اے", "bhain da viyah kal ae", "My sister's wedding is tomorrow"],
    ["gift", "تحفہ", "tohfa", "gift", "Family", "u3", "ایہہ تحفہ تیرے لئی اے", "eh tohfa tere layi ae", "This gift is for you"],
    ["kitchen", "رسوئی", "rasoi", "kitchen", "Common", "u5", "ماں رسوئی وچ اے", "maan rasoi vich ae", "Mother is in the kitchen"],
    ["table", "میز", "mez", "table", "Common", "u5", "روٹی میز تے اے", "roti mez te ae", "The food is on the table"],
    ["bed", "منجی", "manji", "bed, cot", "Common", "u5", "منجی ڈاہ دیو", "manji daah deo", "Set up the bed"],
    ["to_wash", "دھونا", "dhona", "to wash", "Verbs", "u6", "بھانڈے دھونے نیں", "bhaande dhone nein", "The dishes need washing"],
    ["to_wear", "پانا", "paana", "to wear, to put on", "Verbs", "u6", "نویں کپڑے پانے نیں", "naveen kapre paane nein", "I'm going to wear new clothes"],
    ["to_forget", "بھلنا", "bhulna", "to forget", "Verbs", "u6", "میں ناں بھل گیا", "main naan bhul gaya", "I forgot the name"],
    ["to_remember", "یاد رکھنا", "yaad rakhna", "to remember", "Verbs", "u6", "ایہہ گل یاد رکھنا", "eh gal yaad rakhna", "Remember this"],
    ["to_start", "شروع کرنا", "shuru karna", "to start, to begin", "Verbs", "u6", "کم شروع کرو", "kam shuru karo", "Start the work"],
    ["to_finish", "مکاؤنا", "mukaauna", "to finish", "Verbs", "u6", "کم مکا لیا", "kam muka liya", "I finished the work"],
    ["to_laugh", "ہسنا", "hasna", "to laugh", "Verbs", "u6", "ہسنا چنگا اے", "hasna changa ae", "Laughing is good"],
    ["ready", "تیار", "tiyaar", "ready", "Common", "u6", "روٹی تیار اے", "roti tiyaar ae", "The food is ready"],
    ["busy", "مصروف", "masroof", "busy", "Common", "u6", "میں اج مصروف ہاں", "main aj masroof haan", "I'm busy today"],
    ["young", "جوان", "javaan", "young", "Common", "u6", "میری ماسی جوان اے", "meri maasi javaan ae", "My aunt is young"],
    ["clean", "صاف", "saaf", "clean", "Common", "u6", "کمرہ صاف اے", "kamra saaf ae", "The room is clean"],
    ["early", "سویرے", "savere", "early", "Time", "u4", "کل سویرے آئیں", "kal savere aayin", "Come early tomorrow"],
    ["late", "دیر", "der", "late, delay", "Time", "u4", "مینوں دیر ہو گئی", "mainu der ho gayi", "I'm late"],
  ],

  pcm: [
    ["baby", "small pikin", "", "baby", "Family", "u3", "Di small pikin dey sleep", "", "The baby is sleeping"],
    ["husband", "husband", "", "husband", "Family", "u3", "My husband na teacher", "", "My husband is a teacher"],
    ["wife", "wife", "", "wife", "Family", "u3", "My wife na doctor", "", "My wife is a doctor"],
    ["guest", "visitor", "", "guest, visitor", "Family", "u3", "Visitor dey come today", "", "A visitor is coming today"],
    ["neighbor", "neighbour", "", "neighbour", "Family", "u3", "My neighbour good well well", "", "My neighbour is very kind"],
    ["birthday", "birthday", "", "birthday", "Family", "u3", "Happy birthday to you", "", "Happy birthday to you"],
    ["wedding", "wedding", "", "wedding", "Family", "u3", "My sister wedding na tomorrow", "", "My sister's wedding is tomorrow"],
    ["gift", "gift", "", "gift", "Family", "u3", "Dis gift na for you", "", "This gift is for you"],
    ["kitchen", "kitchen", "", "kitchen", "Common", "u5", "Mama dey kitchen", "", "Mama is in the kitchen"],
    ["table", "table", "", "table", "Common", "u5", "Food dey for table", "", "The food is on the table"],
    ["bed", "bed", "", "bed", "Common", "u5", "Dis bed soft well well", "", "This bed is very soft"],
    ["to_wash", "wash", "", "to wash", "Verbs", "u6", "Make you wash plate", "", "Wash the plates"],
    ["to_wear", "wear", "", "to wear", "Verbs", "u6", "I go wear my new cloth", "", "I'll wear my new clothes"],
    ["to_forget", "forget", "", "to forget", "Verbs", "u6", "I don forget im name", "", "I've forgotten his name"],
    ["to_remember", "remember", "", "to remember", "Verbs", "u6", "You remember me?", "", "Do you remember me?"],
    ["to_start", "start", "", "to start", "Verbs", "u6", "Make we start now", "", "Let's start now"],
    ["to_finish", "finish", "", "to finish", "Verbs", "u6", "I don finish my work", "", "I've finished my work"],
    ["to_laugh", "laugh", "", "to laugh", "Verbs", "u6", "Di pikin dem dey laugh", "", "The children are laughing"],
    ["ready", "ready", "", "ready", "Common", "u6", "Food don ready", "", "The food is ready"],
    ["busy", "busy", "", "busy", "Common", "u6", "I dey busy today", "", "I'm busy today"],
    ["young", "young", "", "young", "Common", "u6", "My aunty still young", "", "My aunt is still young"],
    ["clean", "clean", "", "clean", "Common", "u6", "Dis room clean well well", "", "This room is very clean"],
    ["early", "early", "", "early", "Time", "u4", "Come early tomorrow", "", "Come early tomorrow"],
    ["late", "late", "", "late", "Time", "u4", "I don late", "", "I'm late"],
  ],

  so: [
    ["baby", "dhallaan", "", "baby", "Family", "u4", "Dhallaanku wuu seexday", "", "The baby is asleep"],
    ["husband", "nin", "", "husband", "Family", "u4", "Ninkaygu waa macallin", "", "My husband is a teacher"],
    ["wife", "xaas", "", "wife", "Family", "u4", "Xaaskaygu waa dhakhtar", "", "My wife is a doctor"],
    ["guest", "marti", "", "guest", "Family", "u4", "Maanta marti ayaa noo imanaysa", "", "A guest is coming to us today"],
    ["neighbor", "deris", "", "neighbour", "Family", "u4", "Deriskayagu waa wanaagsan yahay", "", "Our neighbour is good"],
    ["birthday", "dhalasho", "", "birthday", "Family", "u4", "Dhalasho wacan", "", "Happy birthday"],
    ["wedding", "aroos", "", "wedding", "Family", "u4", "Arooska walaashay waa berri", "", "My sister's wedding is tomorrow"],
    ["gift", "hadiyad", "", "gift", "Family", "u4", "Tani waa hadiyad adiga kuu ah", "", "This is a gift for you"],
    ["kitchen", "jiko", "", "kitchen", "Common", "u7", "Hooyo waxay joogtaa jikada", "", "Mother is in the kitchen"],
    ["table", "miis", "", "table", "Common", "u7", "Cuntadu waxay saaran tahay miiska", "", "The food is on the table"],
    ["bed", "sariir", "", "bed", "Common", "u7", "Sariirtu way raaxo leedahay", "", "The bed is comfortable"],
    ["to_wash", "dhaq", "", "to wash", "Verbs", "u7", "Gacmahaaga dhaq", "", "Wash your hands"],
    ["to_wear", "xiro", "", "to wear", "Verbs", "u7", "Dharka cusub xiro", "", "Wear the new clothes"],
    ["to_forget", "ilaaw", "", "to forget", "Verbs", "u7", "Ha ilaawin", "", "Don't forget"],
    ["to_remember", "xusuuso", "", "to remember", "Verbs", "u7", "Magacayga xusuuso", "", "Remember my name"],
    ["to_start", "bilow", "", "to start, to begin", "Verbs", "u7", "Hadda bilow", "", "Start now"],
    ["to_finish", "dhammee", "", "to finish", "Verbs", "u7", "Shaqada dhammee", "", "Finish the work"],
    ["to_laugh", "qosol", "", "to laugh, laughter", "Verbs", "u7", "Carruurtu way qoslayaan", "", "The children are laughing"],
    ["ready", "diyaar", "", "ready", "Common", "u7", "Cuntadu waa diyaar", "", "The food is ready"],
    ["busy", "mashquul", "", "busy", "Common", "u7", "Maanta waan mashquulsanahay", "", "I'm busy today"],
    ["young", "da' yar", "", "young (of age)", "Common", "u7", "Eeddaday waa da' yar tahay", "", "My aunt is young"],
    ["clean", "nadiif", "", "clean", "Common", "u7", "Qolku waa nadiif", "", "The room is clean"],
    ["early", "goor hore", "", "early", "Time", "u8", "Berri goor hore kaalay", "", "Come early tomorrow"],
    ["late", "daah", "", "late", "Time", "u8", "Waan daahay", "", "I'm late"],
  ],

  ta: [
    ["baby", "பாப்பா", "paappaa", "baby", "Family", "u4", "பாப்பா தூங்குகிறது", "paappaa thoongugiradhu", "The baby is sleeping"],
    ["husband", "கணவர்", "kanavar", "husband", "Family", "u4", "என் கணவர் ஆசிரியர்", "en kanavar aasiriyar", "My husband is a teacher"],
    ["wife", "மனைவி", "manaivi", "wife", "Family", "u4", "என் மனைவி மருத்துவர்", "en manaivi maruththuvar", "My wife is a doctor"],
    ["guest", "விருந்தினர்", "virundhinar", "guest", "Family", "u4", "இன்று வீட்டுக்கு விருந்தினர் வருகிறார்கள்", "indru veettukku virundhinar varugiraargal", "Guests are coming home today"],
    ["neighbor", "பக்கத்து வீட்டுக்காரர்", "pakkaththu veettukkaarar", "neighbour", "Family", "u4", "பக்கத்து வீட்டுக்காரர் நல்லவர்", "pakkaththu veettukkaarar nallavar", "The neighbour is a good person"],
    ["birthday", "பிறந்தநாள்", "pirandhanaal", "birthday", "Family", "u4", "பிறந்தநாள் வாழ்த்துக்கள்", "pirandhanaal vaazhththukkal", "Happy birthday"],
    ["wedding", "கல்யாணம்", "kalyaanam", "wedding", "Family", "u4", "அக்காவின் கல்யாணம் நாளை", "akkaavin kalyaanam naalai", "My sister's wedding is tomorrow"],
    ["gift", "பரிசு", "parisu", "gift", "Family", "u4", "இது உனக்கான பரிசு", "idhu unakkaana parisu", "This is a gift for you"],
    ["kitchen", "சமையலறை", "samaiyalarai", "kitchen", "Common", "u7", "அம்மா சமையலறையில் இருக்கிறார்", "amma samaiyalaraiyil irukkiraar", "Mother is in the kitchen"],
    ["table", "மேசை", "mesai", "table", "Common", "u7", "சாப்பாடு மேசையில் இருக்கிறது", "saappaadu mesaiyil irukkiradhu", "The food is on the table"],
    ["bed", "படுக்கை", "padukkai", "bed", "Common", "u7", "படுக்கை வசதியாக இருக்கிறது", "padukkai vasadhiyaaga irukkiradhu", "The bed is comfortable"],
    ["to_wash", "கழுவு", "kazhuvu", "to wash", "Verbs", "u7", "கையைக் கழுவு", "kaiyaik kazhuvu", "Wash your hands"],
    ["to_wear", "அணி", "ani", "to wear", "Verbs", "u7", "புதிய சட்டை அணி", "pudhiya sattai ani", "Wear the new shirt"],
    ["to_forget", "மற", "mara", "to forget", "Verbs", "u7", "மறக்காதே", "marakkaadhe", "Don't forget"],
    ["to_remember", "நினைவில் வை", "ninaivil vai", "to remember, to keep in mind", "Verbs", "u7", "இதை நினைவில் வை", "idhai ninaivil vai", "Remember this"],
    ["to_start", "தொடங்கு", "thodangu", "to start, to begin", "Verbs", "u7", "வேலையைத் தொடங்கு", "velaiyaith thodangu", "Start the work"],
    ["to_finish", "முடி", "mudi", "to finish", "Verbs", "u7", "வேலையை முடி", "velaiyai mudi", "Finish the work"],
    ["to_laugh", "சிரி", "siri", "to laugh", "Verbs", "u7", "குழந்தைகள் சிரிக்கிறார்கள்", "kuzhandhaigal sirikkiraargal", "The children are laughing"],
    ["ready", "தயார்", "thayaar", "ready", "Common", "u7", "சாப்பாடு தயார்", "saappaadu thayaar", "The food is ready"],
    ["busy", "பிஸி", "bisi", "busy", "Common", "u7", "இன்று நான் பிஸி", "indru naan bisi", "I'm busy today"],
    ["young", "இளமை", "ilamai", "young, youth", "Common", "u7", "சித்தி இன்னும் இளமையாக இருக்கிறார்", "chiththi innum ilamaiyaaga irukkiraar", "My aunt is still young"],
    ["clean", "சுத்தம்", "suththam", "clean, cleanliness", "Common", "u7", "அறை சுத்தமாக இருக்கிறது", "arai suththamaaga irukkiradhu", "The room is clean"],
    ["early", "சீக்கிரம்", "seekkiram", "early, soon", "Time", "u8", "நாளை சீக்கிரம் வா", "naalai seekkiram vaa", "Come early tomorrow"],
    ["late", "தாமதம்", "thaamadham", "late, delay", "Time", "u8", "எனக்கு தாமதமாகிவிட்டது", "enakku thaamadhamaagivittadhu", "I'm late"],
  ],

  tl: [
    ["baby", "sanggol", "", "baby", "Family", "u4", "Natutulog ang sanggol", "", "The baby is sleeping"],
    ["husband", "asawa", "", "spouse, husband, wife", "Family", "u4", "Guro ang asawa ko", "", "My spouse is a teacher"],
    ["guest", "bisita", "", "guest, visitor", "Family", "u4", "May bisita tayo ngayon", "", "We have a guest today"],
    ["neighbor", "kapitbahay", "", "neighbour", "Family", "u4", "Mabait ang kapitbahay namin", "", "Our neighbour is kind"],
    ["birthday", "kaarawan", "", "birthday", "Family", "u4", "Maligayang kaarawan", "", "Happy birthday"],
    ["wedding", "kasal", "", "wedding", "Family", "u4", "Bukas ang kasal ng ate ko", "", "My sister's wedding is tomorrow"],
    ["gift", "regalo", "", "gift", "Family", "u4", "Regalo ko ito sa iyo", "", "This is my gift to you"],
    ["kitchen", "kusina", "", "kitchen", "Common", "u7", "Nasa kusina si Nanay", "", "Mother is in the kitchen"],
    ["table", "mesa", "", "table", "Common", "u7", "Nasa mesa ang pagkain", "", "The food is on the table"],
    ["bed", "kama", "", "bed", "Common", "u7", "Malambot ang kama", "", "The bed is soft"],
    ["to_wash", "maghugas", "", "to wash", "Verbs", "u7", "Maghugas ka ng kamay", "", "Wash your hands"],
    ["to_wear", "magsuot", "", "to wear", "Verbs", "u7", "Gusto kong magsuot ng bagong damit", "", "I want to wear new clothes"],
    ["to_forget", "kalimutan", "", "to forget", "Verbs", "u7", "Huwag mong kalimutan", "", "Don't forget"],
    ["to_remember", "tandaan", "", "to remember", "Verbs", "u7", "Tandaan mo ito", "", "Remember this"],
    ["to_start", "magsimula", "", "to start, to begin", "Verbs", "u7", "Puwede na tayong magsimula", "", "We can start now"],
    ["to_finish", "tapusin", "", "to finish", "Verbs", "u7", "Tapusin mo ang trabaho", "", "Finish the work"],
    ["to_laugh", "tumawa", "", "to laugh", "Verbs", "u7", "Gusto kong tumawa", "", "I want to laugh"],
    ["ready", "handa", "", "ready", "Common", "u7", "Handa na ang pagkain", "", "The food is ready"],
    ["busy", "abala", "", "busy", "Common", "u7", "Abala ako ngayon", "", "I'm busy today"],
    ["young", "bata pa", "", "young (bata pa = still young)", "Common", "u7", "Bata pa ang tita ko", "", "My aunt is still young"],
    ["clean", "malinis", "", "clean", "Common", "u7", "Malinis ang kuwarto", "", "The room is clean"],
    ["early", "maaga", "", "early", "Time", "u8", "Pumunta ka nang maaga bukas", "", "Come early tomorrow"],
    ["late", "huli", "", "late", "Time", "u8", "Huli na ako", "", "I'm late"],
  ],

  tr: [
    ["baby", "bebek", "", "baby", "Family", "u4", "Bebek uyuyor", "", "The baby is sleeping"],
    ["husband", "koca", "", "husband", "Family", "u4", "Kocam öğretmen", "", "My husband is a teacher"],
    ["wife", "eş", "", "spouse, wife, husband", "Family", "u4", "Eşim doktor", "", "My wife is a doctor"],
    ["guest", "misafir", "", "guest", "Family", "u4", "Bugün misafirimiz var", "", "We have a guest today"],
    ["neighbor", "komşu", "", "neighbour", "Family", "u4", "Komşumuz çok iyi", "", "Our neighbour is very nice"],
    ["birthday", "doğum günü", "", "birthday", "Family", "u4", "Doğum günün kutlu olsun", "", "Happy birthday"],
    ["wedding", "düğün", "", "wedding", "Family", "u4", "Ablamın düğünü yarın", "", "My sister's wedding is tomorrow"],
    ["gift", "hediye", "", "gift", "Family", "u4", "Bu hediye senin için", "", "This gift is for you"],
    ["kitchen", "mutfak", "", "kitchen", "Places", "u7", "Annem mutfakta", "", "My mother is in the kitchen"],
    ["table", "masa", "", "table", "Places", "u7", "Yemek masada", "", "The food is on the table"],
    ["bed", "yatak", "", "bed", "Places", "u7", "Yatak çok rahat", "", "The bed is very comfortable"],
    ["to_wash", "yıkamak", "", "to wash", "Verbs", "u6", "Bulaşıkları yıkamak lazım", "", "The dishes need washing"],
    ["to_wear", "giymek", "", "to wear", "Verbs", "u6", "Yeni elbisemi giymek istiyorum", "", "I want to wear my new dress"],
    ["to_forget", "unutmak", "", "to forget", "Verbs", "u6", "Unutmak istemiyorum", "", "I don't want to forget"],
    ["to_remember", "hatırlamak", "", "to remember", "Verbs", "u6", "Adını hatırlamak zor", "", "Remembering his name is hard"],
    ["to_start", "başlamak", "", "to start, to begin", "Verbs", "u6", "Şimdi başlamak istiyorum", "", "I want to start now"],
    ["to_finish", "bitirmek", "", "to finish", "Verbs", "u6", "İşi bitirmek zorundayım", "", "I have to finish the work"],
    ["to_laugh", "gülmek", "", "to laugh", "Verbs", "u6", "Gülmek sağlığa iyi gelir", "", "Laughing is good for your health"],
    ["ready", "hazır", "", "ready", "Adjectives", "u8", "Yemek hazır", "", "The food is ready"],
    ["busy", "meşgul", "", "busy", "Adjectives", "u8", "Bugün meşgulüm", "", "I'm busy today"],
    ["young", "genç", "", "young", "Adjectives", "u8", "Teyzem çok genç", "", "My aunt is very young"],
    ["clean", "temiz", "", "clean", "Adjectives", "u8", "Oda temiz", "", "The room is clean"],
    ["early", "erken", "", "early", "Time", "u9", "Yarın erken gel", "", "Come early tomorrow"],
    ["late", "geç", "", "late", "Time", "u9", "Geç kaldım", "", "I'm late"],
  ],

  ur: [
    ["baby", "ننھا بچہ", "nanha bachcha", "baby, little child", "Family", "u3", "ننھا بچہ سو رہا ہے", "nanha bachcha so raha hai", "The baby is sleeping"],
    ["guest", "مہمان", "mehmaan", "guest", "Family", "u3", "آج گھر میں مہمان ہیں", "aaj ghar mein mehmaan hain", "There are guests at home today"],
    ["neighbor", "پڑوسی", "parosi", "neighbour", "Family", "u3", "ہمارے پڑوسی اچھے ہیں", "hamaray parosi achay hain", "Our neighbours are nice"],
    ["birthday", "سالگرہ", "saalgirah", "birthday", "Family", "u3", "سالگرہ مبارک", "saalgirah mubarak", "Happy birthday"],
    ["wedding", "شادی", "shaadi", "wedding, marriage", "Family", "u3", "باجی کی شادی کل ہے", "baaji ki shaadi kal hai", "My sister's wedding is tomorrow"],
    ["gift", "تحفہ", "tohfa", "gift", "Family", "u3", "یہ تحفہ آپ کے لیے ہے", "yeh tohfa aap ke liye hai", "This gift is for you"],
    ["kitchen", "باورچی خانہ", "baawarchi khaana", "kitchen", "Places", "u7", "امی باورچی خانے میں ہیں", "ammi baawarchi khaane mein hain", "Mom is in the kitchen"],
    ["table", "میز", "mez", "table", "Places", "u7", "کھانا میز پر ہے", "khana mez par hai", "The food is on the table"],
    ["bed", "بستر", "bistar", "bed", "Places", "u7", "بستر آرام دہ ہے", "bistar aaraam deh hai", "The bed is comfortable"],
    ["to_wash", "دھونا", "dhona", "to wash", "Verbs", "u6", "مجھے برتن دھونا ہیں", "mujhe bartan dhona hain", "I have to wash the dishes"],
    ["to_wear", "پہننا", "pehenna", "to wear", "Verbs", "u6", "آج نئے کپڑے پہننا ہیں", "aaj naye kapray pehenna hain", "I have to wear new clothes today"],
    ["to_forget", "بھولنا", "bhoolna", "to forget", "Verbs", "u6", "میں نام بھول گیا", "main naam bhool gaya", "I forgot the name"],
    ["to_remember", "یاد رکھنا", "yaad rakhna", "to remember", "Verbs", "u6", "یہ بات یاد رکھنا", "yeh baat yaad rakhna", "Remember this"],
    ["to_start", "شروع کرنا", "shuru karna", "to start, to begin", "Verbs", "u6", "کام شروع کرو", "kaam shuru karo", "Start the work"],
    ["to_finish", "ختم کرنا", "khatam karna", "to finish", "Verbs", "u6", "کھانا ختم کرو", "khana khatam karo", "Finish your food"],
    ["to_laugh", "ہنسنا", "hansna", "to laugh", "Verbs", "u6", "بچے ہنس رہے ہیں", "bachay hans rahay hain", "The children are laughing"],
    ["ready", "تیار", "tayyar", "ready", "Common", "u10", "کھانا تیار ہے", "khana tayyar hai", "The food is ready"],
    ["busy", "مصروف", "masroof", "busy", "Common", "u10", "میں آج مصروف ہوں", "main aaj masroof hoon", "I'm busy today"],
    ["young", "جوان", "jawan", "young", "Common", "u10", "میری خالہ جوان ہیں", "meri khala jawan hain", "My aunt is young"],
    ["clean", "صاف", "saaf", "clean", "Common", "u10", "کمرہ صاف ہے", "kamra saaf hai", "The room is clean"],
    ["early", "جلدی", "jaldi", "early, quickly", "Time", "u8", "کل جلدی آنا", "kal jaldi aana", "Come early tomorrow"],
    ["late", "دیر", "der", "late, delay", "Time", "u8", "مجھے دیر ہو گئی", "mujhe der ho gayi", "I'm late"],
  ],

  vi: [
    ["baby", "em bé", "", "baby", "Family", "u3", "Em bé đang ngủ", "", "The baby is sleeping"],
    ["husband", "chồng", "", "husband", "Family", "u3", "Chồng tôi là giáo viên", "", "My husband is a teacher"],
    ["wife", "vợ", "", "wife", "Family", "u3", "Vợ tôi là bác sĩ", "", "My wife is a doctor"],
    ["guest", "khách", "", "guest", "Family", "u3", "Hôm nay nhà có khách", "", "We have guests today"],
    ["neighbor", "hàng xóm", "", "neighbour", "Family", "u3", "Hàng xóm của tôi rất tốt", "", "My neighbour is very nice"],
    ["birthday", "sinh nhật", "", "birthday", "Family", "u3", "Chúc mừng sinh nhật", "", "Happy birthday"],
    ["wedding", "đám cưới", "", "wedding", "Family", "u3", "Đám cưới của chị tôi là ngày mai", "", "My sister's wedding is tomorrow"],
    ["gift", "quà", "", "gift", "Family", "u3", "Đây là quà cho bạn", "", "This is a gift for you"],
    ["kitchen", "nhà bếp", "", "kitchen", "Places", "u7", "Mẹ đang ở trong nhà bếp", "", "Mother is in the kitchen"],
    ["table", "bàn", "", "table", "Places", "u7", "Cơm ở trên bàn", "", "The food is on the table"],
    ["bed", "giường", "", "bed", "Places", "u7", "Giường này rất êm", "", "This bed is very soft"],
    ["to_wash", "rửa", "", "to wash", "Verbs", "u6", "Rửa tay đi", "", "Wash your hands"],
    ["to_wear", "mặc", "", "to wear", "Verbs", "u6", "Hôm nay tôi mặc áo dài", "", "Today I'm wearing an ao dai"],
    ["to_forget", "quên", "", "to forget", "Verbs", "u6", "Đừng quên nhé", "", "Don't forget"],
    ["to_remember", "nhớ", "", "to remember, to miss", "Verbs", "u6", "Bạn có nhớ tôi không?", "", "Do you remember me?"],
    ["to_start", "bắt đầu", "", "to start, to begin", "Verbs", "u6", "Chúng ta bắt đầu nhé", "", "Let's start"],
    ["to_finish", "xong", "", "to finish, done", "Verbs", "u6", "Tôi làm xong rồi", "", "I've finished"],
    ["to_laugh", "cười", "", "to laugh, to smile", "Verbs", "u6", "Bọn trẻ đang cười", "", "The children are laughing"],
    ["ready", "sẵn sàng", "", "ready", "Common", "u8", "Tôi sẵn sàng rồi", "", "I'm ready"],
    ["busy", "bận", "", "busy", "Common", "u8", "Hôm nay tôi bận", "", "I'm busy today"],
    ["young", "trẻ", "", "young", "Common", "u8", "Dì tôi còn trẻ", "", "My aunt is still young"],
    ["clean", "sạch", "", "clean", "Common", "u8", "Phòng này sạch", "", "This room is clean"],
    ["early", "sớm", "", "early", "Time", "u8", "Mai đến sớm nhé", "", "Come early tomorrow"],
    ["late", "muộn", "", "late", "Time", "u8", "Muộn rồi", "", "It's late"],
  ],

  yo: [
    ["baby", "ọmọ ọwọ́", "", "baby", "Family", "u3", "Ọmọ ọwọ́ ń sùn", "", "The baby is sleeping"],
    ["husband", "ọkọ", "", "husband", "Family", "u3", "Olùkọ́ ni ọkọ mi", "", "My husband is a teacher"],
    ["wife", "ìyàwó", "", "wife", "Family", "u3", "Dókítà ni ìyàwó mi", "", "My wife is a doctor"],
    ["guest", "àlejò", "", "guest", "Family", "u3", "A ní àlejò lónìí", "", "We have a guest today"],
    ["neighbor", "aládùúgbò", "", "neighbour", "Family", "u3", "Aládùúgbò wa dára", "", "Our neighbour is good"],
    ["birthday", "ọjọ́ ìbí", "", "birthday", "Family", "u3", "Ẹ kú ọjọ́ ìbí", "", "Happy birthday"],
    ["wedding", "ìgbéyàwó", "", "wedding", "Family", "u3", "Ìgbéyàwó ẹ̀gbọ́n mi ni ọ̀la", "", "My sister's wedding is tomorrow"],
    ["gift", "ẹ̀bùn", "", "gift", "Family", "u3", "Ẹ̀bùn rẹ nìyí", "", "Here is your gift"],
    ["kitchen", "ilé ìdáná", "", "kitchen", "Places", "u7", "Màmá wà ní ilé ìdáná", "", "Mother is in the kitchen"],
    ["table", "tábìlì", "", "table", "Places", "u7", "Oúnjẹ wà lórí tábìlì", "", "The food is on the table"],
    ["bed", "ibùsùn", "", "bed", "Places", "u7", "Ibùsùn yìí rọ̀", "", "This bed is soft"],
    ["to_wash", "fọ", "", "to wash", "Verbs", "u6", "Fọ ọwọ́ rẹ", "", "Wash your hands"],
    ["to_wear", "wọ", "", "to wear, to put on", "Verbs", "u6", "Wọ aṣọ tuntun rẹ", "", "Wear your new clothes"],
    ["to_forget", "gbàgbé", "", "to forget", "Verbs", "u6", "Má gbàgbé o", "", "Don't forget"],
    ["to_remember", "rántí", "", "to remember", "Verbs", "u6", "Ṣé o rántí mi?", "", "Do you remember me?"],
    ["to_start", "bẹ̀rẹ̀", "", "to start, to begin", "Verbs", "u6", "Ẹ jẹ́ ká bẹ̀rẹ̀", "", "Let's start"],
    ["to_finish", "parí", "", "to finish", "Verbs", "u6", "Mo ti parí iṣẹ́ mi", "", "I have finished my work"],
    ["to_laugh", "rẹ́rìn-ín", "", "to laugh", "Verbs", "u6", "Àwọn ọmọdé ń rẹ́rìn-ín", "", "The children are laughing"],
    ["ready", "ṣetán", "", "ready", "Common", "u8", "Oúnjẹ ti ṣetán", "", "The food is ready"],
    ["busy", "ọwọ́ dí", "", "busy (lit. hands are full)", "Common", "u8", "Ọwọ́ mi dí lónìí", "", "I'm busy today"],
    ["young", "ọ̀dọ́", "", "young, youth", "Common", "u8", "Ọ̀dọ́ ni wọ́n", "", "They are young"],
    ["clean", "mọ́", "", "clean", "Common", "u8", "Yàrá yìí mọ́", "", "This room is clean"],
    ["early", "kùtùkùtù", "", "early (in the morning)", "Time", "u8", "Mo jí ní kùtùkùtù", "", "I woke up early"],
    ["late", "pẹ́", "", "late", "Time", "u8", "Mo ti pẹ́", "", "I'm late"],
  ],

  zh: [
    ["baby", "宝宝", "bǎobao", "baby", "Family", "u3", "宝宝在睡觉", "bǎobao zài shuìjiào", "The baby is sleeping"],
    ["husband", "丈夫", "zhàngfu", "husband", "Family", "u3", "我丈夫是老师", "wǒ zhàngfu shì lǎoshī", "My husband is a teacher"],
    ["wife", "妻子", "qīzi", "wife", "Family", "u3", "我妻子是医生", "wǒ qīzi shì yīshēng", "My wife is a doctor"],
    ["guest", "客人", "kèrén", "guest", "Family", "u3", "今天家里有客人", "jīntiān jiālǐ yǒu kèrén", "We have guests at home today"],
    ["neighbor", "邻居", "línjū", "neighbour", "Family", "u3", "我的邻居很好", "wǒ de línjū hěn hǎo", "My neighbour is very nice"],
    ["birthday", "生日", "shēngrì", "birthday", "Family", "u3", "生日快乐", "shēngrì kuàilè", "Happy birthday"],
    ["wedding", "婚礼", "hūnlǐ", "wedding", "Family", "u3", "姐姐的婚礼是明天", "jiějie de hūnlǐ shì míngtiān", "My sister's wedding is tomorrow"],
    ["gift", "礼物", "lǐwù", "gift, present", "Family", "u3", "这是给你的礼物", "zhè shì gěi nǐ de lǐwù", "This is a gift for you"],
    ["kitchen", "厨房", "chúfáng", "kitchen", "Places", "u7", "妈妈在厨房", "māma zài chúfáng", "Mom is in the kitchen"],
    ["table", "桌子", "zhuōzi", "table", "Places", "u7", "饭在桌子上", "fàn zài zhuōzi shang", "The food is on the table"],
    ["bed", "床", "chuáng", "bed", "Places", "u7", "这张床很舒服", "zhè zhāng chuáng hěn shūfu", "This bed is very comfortable"],
    ["to_wash", "洗", "xǐ", "to wash", "Verbs", "u6", "快去洗手", "kuài qù xǐ shǒu", "Go wash your hands"],
    ["to_wear", "穿", "chuān", "to wear", "Verbs", "u6", "今天穿新衣服", "jīntiān chuān xīn yīfu", "I'm wearing new clothes today"],
    ["to_forget", "忘", "wàng", "to forget", "Verbs", "u6", "别忘了", "bié wàng le", "Don't forget"],
    ["to_remember", "记得", "jìde", "to remember", "Verbs", "u6", "你记得我吗？", "nǐ jìde wǒ ma?", "Do you remember me?"],
    ["to_start", "开始", "kāishǐ", "to start, to begin", "Verbs", "u6", "我们开始吧", "wǒmen kāishǐ ba", "Let's start"],
    ["to_finish", "完成", "wánchéng", "to finish, to complete", "Verbs", "u6", "我完成了作业", "wǒ wánchéng le zuòyè", "I finished my homework"],
    ["to_laugh", "笑", "xiào", "to laugh, to smile", "Verbs", "u6", "孩子们在笑", "háizimen zài xiào", "The children are laughing"],
    ["ready", "准备好", "zhǔnbèi hǎo", "ready", "Common", "u10", "我准备好了", "wǒ zhǔnbèi hǎo le", "I'm ready"],
    ["busy", "忙", "máng", "busy", "Common", "u10", "我今天很忙", "wǒ jīntiān hěn máng", "I'm busy today"],
    ["young", "年轻", "niánqīng", "young", "Common", "u10", "阿姨很年轻", "āyí hěn niánqīng", "Auntie is very young"],
    ["clean", "干净", "gānjìng", "clean", "Common", "u10", "房间很干净", "fángjiān hěn gānjìng", "The room is clean"],
    ["early", "早", "zǎo", "early", "Time", "u8", "明天早点来", "míngtiān zǎo diǎn lái", "Come early tomorrow"],
    ["late", "晚", "wǎn", "late", "Time", "u8", "太晚了", "tài wǎn le", "It's too late"],
  ],
};

// Four meanings the packs already had the word for, under another gloss. The
// merge skips a lemma a pack already has, so these widen the existing word
// instead of adding a duplicate: Punjabi ਸਵੇਰੇ savere is "in the morning" and
// "early"; Urdu jaldi is "quickly" and "early"; Somali nin is "man" and
// "husband" (ninkayga, my husband). [conceptId, lemma, gloss, exN, exT, exE]
export const V109_EXTEND = {
  pa: [["early", "سویرے", "early", "کل سویرے آئیں", "kal savere aayin", "Come early tomorrow"]],
  ur: [["early", "جلدی", "early", "کل جلدی آنا", "kal jaldi aana", "Come early tomorrow"]],
  so: [["husband", "nin", "husband", "Ninkaygu waa macallin", "", "My husband is a teacher"]],
};

// Tagalog asawa was glossed "spouse (husband or wife)" — right, but the
// parenthesis is (deliberately) not read as a gloss, so the pack counted as
// teaching neither. Same meaning, said as glosses. [lemma, from, to]
export const V109_REGLOSS = {
  tl: [["asawa", "spouse (husband or wife)", "spouse, husband, wife"]],
};
