// =============================================================================
// v112-fill.mjs — talking with people.
//
// MEASURED across all 21 packs before writing: question, answer, language,
// people, teacher, to meet, to visit, to travel, to try, to show, to send, to
// feel, to use, important, different, same, lunch and dinner were taught by
// NO pack; together and sometimes by one. These are the words for asking
// something, making plans and saying how it went — "can I ask a question?",
// "let's meet tomorrow", "we're visiting grandmother", "try again", "lunch is
// ready" — conversation rather than vocabulary.
//
// 20 concepts, tier 3, each in the unit where the pack already keeps people,
// verbs, everyday words, time and food. Verbs follow each pack's own headword
// convention (infinitive, dictionary form, imperative root or 3rd person
// present, whichever the pack already uses), and every example contains its
// word so validate-word-truth can check it.
//
// Fields: [conceptId, lemma, translit, translation, category, unit,
//          exNative, exTranslit, exTranslation]
// =============================================================================

export const V112_FILL = {
  ur: [
    ["question", "سوال", "sawaal", "question", "Common", "u10", "میرا ایک سوال ہے", "mera ek sawaal hai", "I have a question"],
    ["answer", "جواب", "jawaab", "answer", "Common", "u10", "جواب کیا ہے؟", "jawaab kya hai?", "What is the answer?"],
    ["language", "زبان", "zabaan", "language", "Common", "u10", "اردو میری زبان ہے", "urdu meri zabaan hai", "Urdu is my language"],
    ["people", "لوگ", "log", "people", "People", "u2", "یہاں بہت لوگ ہیں", "yahan bohat log hain", "There are many people here"],
    ["teacher", "استاد", "ustaad", "teacher", "People", "u2", "میرے استاد بہت اچھے ہیں", "mere ustaad bohat achhe hain", "My teacher is very good"],
    ["to_meet", "ملنا", "milna", "to meet", "Verbs", "u6", "ہمیں کل ملنا ہے", "humein kal milna hai", "We have to meet tomorrow"],
    ["to_visit", "ملنے جانا", "milne jaana", "to visit", "Verbs", "u6", "ہم نانی سے ملنے جائیں گے", "hum nani se milne jaayenge", "We will go to visit grandmother"],
    ["to_travel", "سفر کرنا", "safar karna", "to travel", "Verbs", "u6", "مجھے سفر کرنا پسند ہے", "mujhe safar karna pasand hai", "I like to travel"],
    ["to_try", "کوشش کرنا", "koshish karna", "to try", "Verbs", "u6", "دوبارہ کوشش کرو", "dobara koshish karo", "Try again"],
    ["to_show", "دکھانا", "dikhana", "to show", "Verbs", "u6", "مجھے تصویر دکھاؤ", "mujhe tasveer dikhao", "Show me the picture"],
    ["to_send", "بھیجنا", "bhejna", "to send", "Verbs", "u6", "مجھے پیغام بھیجو", "mujhe paighaam bhejo", "Send me a message"],
    ["to_feel", "محسوس کرنا", "mehsoos karna", "to feel", "Verbs", "u6", "میں بہتر محسوس کر رہا ہوں", "main behtar mehsoos kar raha hoon", "I'm feeling better"],
    ["to_use", "استعمال کرنا", "istemaal karna", "to use", "Verbs", "u6", "یہ فون استعمال کرو", "yeh phone istemaal karo", "Use this phone"],
    ["important", "ضروری", "zaroori", "important, necessary", "Common", "u10", "یہ بہت ضروری ہے", "yeh bohat zaroori hai", "This is very important"],
    ["different", "مختلف", "mukhtalif", "different", "Common", "u10", "یہ رنگ مختلف ہے", "yeh rang mukhtalif hai", "This colour is different"],
    ["same", "ایک جیسا", "ek jaisa", "the same, alike", "Common", "u10", "دونوں ایک جیسے ہیں", "donon ek jaise hain", "Both are the same"],
    ["together", "ساتھ", "saath", "together, with", "Common", "u10", "ہم ساتھ چلیں گے", "hum saath chalenge", "We'll go together"],
    ["sometimes", "کبھی کبھی", "kabhi kabhi", "sometimes", "Time", "u8", "میں کبھی کبھی چائے پیتا ہوں", "main kabhi kabhi chai peeta hoon", "I sometimes drink tea"],
    ["lunch", "دوپہر کا کھانا", "dopahar ka khana", "lunch", "Food", "u5", "دوپہر کا کھانا تیار ہے", "dopahar ka khana tayyar hai", "Lunch is ready"],
    ["dinner", "رات کا کھانا", "raat ka khana", "dinner", "Food", "u5", "رات کا کھانا کب ہے؟", "raat ka khana kab hai?", "When is dinner?"],
  ],
  hi: [
    ["question", "सवाल", "sawaal", "question", "Common", "u10", "मेरा एक सवाल है", "mera ek sawaal hai", "I have a question"],
    ["answer", "जवाब", "jawaab", "answer", "Common", "u10", "जवाब क्या है?", "jawaab kya hai?", "What is the answer?"],
    ["language", "भाषा", "bhaasha", "language", "Common", "u10", "हिंदी मेरी भाषा है", "hindi meri bhaasha hai", "Hindi is my language"],
    ["people", "लोग", "log", "people", "People", "u2", "यहाँ बहुत लोग हैं", "yahaan bahut log hain", "There are many people here"],
    ["teacher", "शिक्षक", "shikshak", "teacher", "People", "u2", "मेरे शिक्षक बहुत अच्छे हैं", "mere shikshak bahut achchhe hain", "My teacher is very good"],
    ["to_meet", "मिलना", "milna", "to meet", "Verbs", "u6", "हमें कल मिलना है", "hamen kal milna hai", "We have to meet tomorrow"],
    ["to_visit", "मिलने जाना", "milne jaana", "to visit", "Verbs", "u6", "हम नानी से मिलने जाएँगे", "ham naani se milne jaayenge", "We will go to visit grandmother"],
    ["to_travel", "यात्रा करना", "yaatra karna", "to travel", "Verbs", "u6", "मुझे यात्रा करना पसंद है", "mujhe yaatra karna pasand hai", "I like to travel"],
    ["to_try", "कोशिश करना", "koshish karna", "to try", "Verbs", "u6", "फिर से कोशिश करो", "phir se koshish karo", "Try again"],
    ["to_show", "दिखाना", "dikhaana", "to show", "Verbs", "u6", "मुझे फ़ोटो दिखाओ", "mujhe photo dikhaao", "Show me the photo"],
    ["to_send", "भेजना", "bhejna", "to send", "Verbs", "u6", "मुझे संदेश भेजो", "mujhe sandesh bhejo", "Send me a message"],
    ["to_feel", "महसूस करना", "mahsoos karna", "to feel", "Verbs", "u6", "मैं बेहतर महसूस कर रहा हूँ", "main behtar mahsoos kar raha hoon", "I'm feeling better"],
    ["to_use", "इस्तेमाल करना", "istemaal karna", "to use", "Verbs", "u6", "यह फ़ोन इस्तेमाल करो", "yah phone istemaal karo", "Use this phone"],
    ["important", "ज़रूरी", "zaroori", "important, necessary", "Common", "u10", "यह बहुत ज़रूरी है", "yah bahut zaroori hai", "This is very important"],
    ["different", "अलग", "alag", "different", "Common", "u10", "यह रंग अलग है", "yah rang alag hai", "This colour is different"],
    ["same", "एक जैसा", "ek jaisa", "the same, alike", "Common", "u10", "दोनों एक जैसे हैं", "donon ek jaise hain", "Both are the same"],
    ["together", "साथ", "saath", "together, with", "Common", "u10", "हम साथ चलेंगे", "ham saath chalenge", "We'll go together"],
    ["sometimes", "कभी-कभी", "kabhi-kabhi", "sometimes", "Time", "u8", "मैं कभी-कभी चाय पीता हूँ", "main kabhi-kabhi chaay peeta hoon", "I sometimes drink tea"],
    ["lunch", "दोपहर का खाना", "dopahar ka khaana", "lunch", "Food", "u5", "दोपहर का खाना तैयार है", "dopahar ka khaana taiyaar hai", "Lunch is ready"],
    ["dinner", "रात का खाना", "raat ka khaana", "dinner", "Food", "u5", "रात का खाना कब है?", "raat ka khaana kab hai?", "When is dinner?"],
  ],
  pa: [
    ["question", "سوال", "savaal", "question", "Common", "u6", "میرا اک سوال اے", "mera ik savaal ae", "I have a question"],
    ["answer", "جواب", "javaab", "answer", "Common", "u6", "جواب کیہ اے؟", "javaab kee ae?", "What is the answer?"],
    ["language", "بولی", "boli", "language", "Common", "u6", "پنجابی ساڈی بولی اے", "panjabi saadi boli ae", "Punjabi is our language"],
    ["people", "لوک", "lok", "people", "People", "u2", "ایتھے بڑے لوک نیں", "ethe bade lok nen", "There are many people here"],
    ["teacher", "استاد", "ustaad", "teacher", "People", "u2", "میرا استاد بہت چنگا اے", "mera ustaad bahut changa ae", "My teacher is very good"],
    ["to_meet", "ملنا", "milna", "to meet", "Verbs", "u6", "کل ملنا اے", "kal milna ae", "We're meeting tomorrow"],
    ["to_visit", "ملن جانا", "milan jaana", "to visit", "Verbs", "u6", "اسیں نانی نوں ملن جاواں گے", "aseen naani nu milan jaavaan ge", "We'll go to visit grandmother"],
    ["to_travel", "سفر کرنا", "safar karna", "to travel", "Verbs", "u6", "مینوں سفر کرنا چنگا لگدا اے", "mainu safar karna changa lagda ae", "I like to travel"],
    ["to_try", "کوشش کرنا", "koshish karna", "to try", "Verbs", "u6", "فیر کوشش کرو", "pher koshish karo", "Try again"],
    ["to_show", "وکھانا", "vikhaana", "to show", "Verbs", "u6", "مینوں تصویر وکھاؤ", "mainu tasveer vikhaao", "Show me the picture"],
    ["to_send", "بھیجنا", "bhejna", "to send", "Verbs", "u6", "مینوں سنیہا بھیجو", "mainu suneha bhejo", "Send me a message"],
    ["to_feel", "محسوس کرنا", "mehsoos karna", "to feel", "Verbs", "u6", "میں چنگا محسوس کر رہیا واں", "main changa mehsoos kar rehya vaan", "I'm feeling good"],
    ["to_use", "ورتنا", "vartna", "to use", "Verbs", "u6", "ایہہ فون ورتو", "eh phone varto", "Use this phone"],
    ["important", "ضروری", "zaroori", "important, necessary", "Common", "u6", "ایہہ بہت ضروری اے", "eh bahut zaroori ae", "This is very important"],
    ["different", "وکھرا", "vakhra", "different", "Common", "u6", "ایہہ رنگ وکھرا اے", "eh rang vakhra ae", "This colour is different"],
    ["same", "اکو جیہا", "iko jeha", "the same, alike", "Common", "u6", "دوویں اکو جیہے نیں", "dovein iko jehe nen", "Both are the same"],
    ["together", "اکٹھے", "ikatthe", "together", "Common", "u6", "اسیں اکٹھے چلاں گے", "aseen ikatthe chalaan ge", "We'll go together"],
    ["sometimes", "کدی کدی", "kadi kadi", "sometimes", "Time", "u4", "میں کدی کدی چاہ پیندا واں", "main kadi kadi chaah peenda vaan", "I sometimes drink tea"],
    ["lunch", "دوپہر دی روٹی", "dupahar di roti", "lunch", "Food", "u5", "دوپہر دی روٹی تیار اے", "dupahar di roti tiyaar ae", "Lunch is ready"],
    ["dinner", "رات دی روٹی", "raat di roti", "dinner", "Food", "u5", "رات دی روٹی کدوں اے؟", "raat di roti kadon ae?", "When is dinner?"],
  ],
  bn: [
    ["question", "প্রশ্ন", "proshno", "question", "Common", "u10", "আমার একটা প্রশ্ন আছে", "amar ekta proshno achhe", "I have a question"],
    ["answer", "উত্তর", "uttor", "answer", "Common", "u10", "উত্তর কী?", "uttor ki?", "What is the answer?"],
    ["language", "ভাষা", "bhasha", "language", "Common", "u10", "বাংলা আমার ভাষা", "bangla amar bhasha", "Bengali is my language"],
    ["people", "মানুষ", "manush", "people, person", "People", "u2", "এখানে অনেক মানুষ", "ekhane onek manush", "There are many people here"],
    ["teacher", "শিক্ষক", "shikkhok", "teacher", "People", "u2", "আমার শিক্ষক খুব ভালো", "amar shikkhok khub bhalo", "My teacher is very good"],
    ["to_meet", "দেখা করা", "dekha kora", "to meet", "Verbs", "u6", "কাল দেখা করব", "kal dekha korbo", "We'll meet tomorrow"],
    ["to_visit", "বেড়াতে যাওয়া", "berate jaowa", "to visit", "Verbs", "u6", "আমরা দাদুর বাড়ি বেড়াতে যাব", "amra dadur bari berate jabo", "We'll go to visit grandfather's house"],
    ["to_travel", "ভ্রমণ করা", "bhromon kora", "to travel", "Verbs", "u6", "আমি ভ্রমণ করতে ভালোবাসি", "ami bhromon korte bhalobashi", "I love to travel"],
    ["to_try", "চেষ্টা করা", "chesta kora", "to try", "Verbs", "u6", "আবার চেষ্টা করো", "abar chesta koro", "Try again"],
    ["to_show", "দেখানো", "dekhano", "to show", "Verbs", "u6", "আমাকে ছবিটা দেখাও", "amake chobita dekhao", "Show me the picture"],
    ["to_send", "পাঠানো", "pathano", "to send", "Verbs", "u6", "আমাকে বার্তা পাঠাও", "amake barta pathao", "Send me a message"],
    ["to_feel", "অনুভব করা", "onubhob kora", "to feel", "Verbs", "u6", "আমি ভালো অনুভব করছি", "ami bhalo onubhob korchhi", "I'm feeling good"],
    ["to_use", "ব্যবহার করা", "byabohar kora", "to use", "Verbs", "u6", "এই ফোনটা ব্যবহার করো", "ei phonta byabohar koro", "Use this phone"],
    ["important", "জরুরি", "joruri", "important, urgent", "Common", "u10", "এটা খুব জরুরি", "eta khub joruri", "This is very important"],
    ["different", "আলাদা", "alada", "different", "Common", "u10", "এই রংটা আলাদা", "ei rongta alada", "This colour is different"],
    ["same", "একই", "eki", "the same", "Common", "u10", "দুটো একই রকম", "duto eki rokom", "Both are the same"],
    ["together", "একসাথে", "eksathe", "together", "Common", "u10", "আমরা একসাথে যাব", "amra eksathe jabo", "We'll go together"],
    ["sometimes", "মাঝে মাঝে", "majhe majhe", "sometimes", "Time", "u8", "আমি মাঝে মাঝে চা খাই", "ami majhe majhe cha khai", "I sometimes drink tea"],
    ["lunch", "দুপুরের খাবার", "dupurer khabar", "lunch", "Food", "u5", "দুপুরের খাবার তৈরি", "dupurer khabar toiri", "Lunch is ready"],
    ["dinner", "রাতের খাবার", "rater khabar", "dinner", "Food", "u5", "রাতের খাবার কখন?", "rater khabar kokhon?", "When is dinner?"],
  ],
  ar: [
    ["question", "سؤال", "su'aal", "question", "Common", "u10", "عندي سؤال", "indi su'aal", "I have a question"],
    ["answer", "جواب", "jawaab", "answer", "Common", "u10", "ما الجواب؟", "ma al-jawaab?", "What is the answer?"],
    ["language", "لغة", "lugha", "language", "Common", "u10", "العربية لغة جميلة", "al-arabiyya lugha jamila", "Arabic is a beautiful language"],
    ["people", "ناس", "naas", "people", "People", "u2", "هنا ناس كثيرون", "huna naas kathiroon", "There are many people here"],
    ["teacher", "معلم", "mu'allim", "teacher", "People", "u2", "المعلم في الصف", "al-mu'allim fi as-saff", "The teacher is in the classroom"],
    ["to_meet", "يقابل", "yuqaabil", "to meet", "Verbs", "u6", "هو يقابل صديقه", "huwa yuqaabil sadiqahu", "He meets his friend"],
    ["to_visit", "يزور", "yazoor", "to visit", "Verbs", "u6", "يزور جدته كل أسبوع", "yazoor jaddatahu kull usboo'", "He visits his grandmother every week"],
    ["to_travel", "يسافر", "yusaafir", "to travel", "Verbs", "u6", "يسافر إلى مصر غداً", "yusaafir ila misr ghadan", "He is travelling to Egypt tomorrow"],
    ["to_try", "يحاول", "yuhaawil", "to try", "Verbs", "u6", "يحاول مرة أخرى", "yuhaawil marra ukhra", "He tries again"],
    ["to_show", "يعرض", "ya'rid", "to show", "Verbs", "u6", "يعرض الصور على أمه", "ya'rid as-suwar ala ummihi", "He shows the photos to his mother"],
    ["to_send", "يرسل", "yursil", "to send", "Verbs", "u6", "يرسل رسالة لأخيه", "yursil risaala li-akhihi", "He sends a message to his brother"],
    ["to_feel", "يشعر", "yash'ur", "to feel", "Verbs", "u6", "يشعر بالتعب", "yash'ur bit-ta'ab", "He feels tired"],
    ["to_use", "يستخدم", "yastakhdim", "to use", "Verbs", "u6", "يستخدم الهاتف كثيراً", "yastakhdim al-haatif kathiran", "He uses the phone a lot"],
    ["important", "مهم", "muhimm", "important", "Common", "u10", "هذا مهم جداً", "haadha muhimm jiddan", "This is very important"],
    ["different", "مختلف", "mukhtalif", "different", "Common", "u10", "هذا اللون مختلف", "haadha al-lawn mukhtalif", "This colour is different"],
    ["same", "نفس", "nafs", "the same", "Common", "u10", "هذا نفس الشيء", "haadha nafs ash-shay'", "This is the same thing"],
    ["together", "معاً", "ma'an", "together", "Common", "u10", "نذهب معاً", "nadh-hab ma'an", "We go together"],
    ["sometimes", "أحياناً", "ahyaanan", "sometimes", "Time", "u8", "أشرب الشاي أحياناً", "ashrab ash-shaay ahyaanan", "I sometimes drink tea"],
    ["lunch", "غداء", "ghadaa'", "lunch", "Food", "u5", "الغداء جاهز", "al-ghadaa' jaahiz", "Lunch is ready"],
    ["dinner", "عشاء", "ashaa'", "dinner", "Food", "u5", "متى العشاء؟", "mata al-ashaa'?", "When is dinner?"],
  ],
  fa: [
    ["question", "سؤال", "so'aal", "question", "Common", "u7", "یک سؤال دارم", "yek so'aal daaram", "I have a question"],
    ["answer", "جواب", "javaab", "answer", "Common", "u7", "جواب چیست؟", "javaab chist?", "What is the answer?"],
    ["language", "زبان", "zabaan", "language", "Common", "u7", "فارسی زبان شیرینی است", "faarsi zabaan-e shirini ast", "Persian is a sweet language"],
    ["people", "مردم", "mardom", "people", "People", "u3", "مردم اینجا مهربان هستند", "mardom injaa mehrabaan hastand", "The people here are kind"],
    ["teacher", "معلم", "mo'allem", "teacher", "People", "u3", "معلم ما خیلی خوب است", "mo'allem-e maa kheyli khub ast", "Our teacher is very good"],
    ["to_meet", "ملاقات کردن", "molaaqaat kardan", "to meet", "Verbs", "u7", "فردا با او ملاقات می‌کنم", "fardaa baa u molaaqaat mikonam", "I'll meet him tomorrow"],
    ["to_visit", "دیدن کردن", "didan kardan", "to visit", "Verbs", "u7", "از تهران دیدن کردیم", "az tehraan didan kardim", "We visited Tehran"],
    ["to_travel", "سفر کردن", "safar kardan", "to travel", "Verbs", "u7", "دوست دارم سفر کنم", "dust daaram safar konam", "I'd like to travel"],
    ["to_try", "سعی کردن", "sa'y kardan", "to try", "Verbs", "u7", "دوباره سعی کن", "dobaare sa'y kon", "Try again"],
    ["to_show", "نشان دادن", "neshaan daadan", "to show", "Verbs", "u7", "عکس را به من نشان بده", "aks raa be man neshaan bede", "Show me the picture"],
    ["to_send", "فرستادن", "ferestaadan", "to send", "Verbs", "u7", "نامه را فرستادم", "naame raa ferestaadam", "I sent the letter"],
    ["to_feel", "احساس کردن", "ehsaas kardan", "to feel", "Verbs", "u7", "احساس کردم که هوا سرد است", "ehsaas kardam ke havaa sard ast", "I felt that the weather was cold"],
    ["to_use", "استفاده کردن", "estefaade kardan", "to use", "Verbs", "u7", "از این گوشی استفاده کن", "az in gushi estefaade kon", "Use this phone"],
    ["important", "مهم", "mohem", "important", "Common", "u7", "این خیلی مهم است", "in kheyli mohem ast", "This is very important"],
    ["different", "متفاوت", "motefaavet", "different", "Common", "u7", "این رنگ متفاوت است", "in rang motefaavet ast", "This colour is different"],
    ["same", "یکسان", "yeksaan", "the same", "Common", "u7", "هر دو یکسان هستند", "har do yeksaan hastand", "Both are the same"],
    ["together", "با هم", "baa ham", "together", "Common", "u7", "با هم می‌رویم", "baa ham miravim", "We'll go together"],
    ["sometimes", "گاهی", "gaahi", "sometimes", "Time", "u8", "گاهی چای می‌نوشم", "gaahi chaay minusham", "I sometimes drink tea"],
    ["lunch", "ناهار", "naahaar", "lunch", "Food", "u6", "ناهار آماده است", "naahaar aamaade ast", "Lunch is ready"],
    ["dinner", "شام", "shaam", "dinner", "Food", "u6", "شام کی است؟", "shaam key ast?", "When is dinner?"],
  ],
  ml: [
    ["question", "ചോദ്യം", "chodyam", "question", "Common", "u7", "എനിക്ക് ഒരു ചോദ്യം ഉണ്ട്", "enikku oru chodyam undu", "I have a question"],
    ["answer", "ഉത്തരം", "utharam", "answer", "Common", "u7", "ഉത്തരം എന്താണ്?", "utharam enthaanu?", "What is the answer?"],
    ["language", "ഭാഷ", "bhaasha", "language", "Common", "u7", "മലയാളം എന്റെ ഭാഷയാണ്", "malayaalam ente bhaashayaanu", "Malayalam is my language"],
    ["people", "ആളുകൾ", "aalukal", "people", "People", "u3", "ഇവിടെ ധാരാളം ആളുകൾ ഉണ്ട്", "ivide dhaaraalam aalukal undu", "There are many people here"],
    ["teacher", "അധ്യാപകൻ", "adhyaapakan", "teacher", "People", "u3", "എന്റെ അധ്യാപകൻ വളരെ നല്ലതാണ്", "ente adhyaapakan valare nallathaanu", "My teacher is very good"],
    ["to_meet", "കണ്ടുമുട്ടുക", "kandumuttuka", "to meet", "Verbs", "u7", "നാളെ കണ്ടുമുട്ടാം", "naale kandumuttaam", "Let's meet tomorrow"],
    ["to_visit", "സന്ദർശിക്കുക", "sandarshikkuka", "to visit", "Verbs", "u7", "ഞങ്ങൾ മുത്തശ്ശിയെ സന്ദർശിക്കും", "njangal muthashshiye sandarshikkum", "We will visit grandmother"],
    ["to_travel", "യാത്ര ചെയ്യുക", "yaathra cheyyuka", "to travel", "Verbs", "u7", "എനിക്ക് യാത്ര ചെയ്യാൻ ഇഷ്ടമാണ്", "enikku yaathra cheyyaan ishtamaanu", "I like to travel"],
    ["to_try", "ശ്രമിക്കുക", "shramikkuka", "to try", "Verbs", "u7", "വീണ്ടും ശ്രമിക്കൂ", "veendum shramikkoo", "Try again"],
    ["to_show", "കാണിക്കുക", "kaanikkuka", "to show", "Verbs", "u7", "ആ ഫോട്ടോ എന്നെ കാണിക്കൂ", "aa photo enne kaanikkoo", "Show me that photo"],
    ["to_send", "അയക്കുക", "ayakkuka", "to send", "Verbs", "u7", "എനിക്ക് ഒരു സന്ദേശം അയക്കൂ", "enikku oru sandesham ayakkoo", "Send me a message"],
    ["to_feel", "തോന്നുക", "thonnuka", "to feel", "Verbs", "u7", "എനിക്ക് ക്ഷീണം തോന്നുന്നു", "enikku ksheenam thonnunnu", "I feel tired"],
    ["to_use", "ഉപയോഗിക്കുക", "upayogikkuka", "to use", "Verbs", "u7", "ഈ ഫോൺ ഉപയോഗിക്കൂ", "ee phone upayogikkoo", "Use this phone"],
    ["important", "പ്രധാനം", "pradhaanam", "important", "Common", "u7", "ഇത് വളരെ പ്രധാനമാണ്", "ithu valare pradhaanamaanu", "This is very important"],
    ["different", "വ്യത്യസ്തം", "vyathyastham", "different", "Common", "u7", "ഈ നിറം വ്യത്യസ്തമാണ്", "ee niram vyathyasthamaanu", "This colour is different"],
    ["same", "ഒരേ", "ore", "the same", "Common", "u7", "രണ്ടും ഒരേ പോലെയാണ്", "randum ore poleyaanu", "Both are the same"],
    ["together", "ഒരുമിച്ച്", "orumichu", "together", "Common", "u7", "നമുക്ക് ഒരുമിച്ച് പോകാം", "namukku orumichu pokaam", "Let's go together"],
    ["sometimes", "ചിലപ്പോൾ", "chilappol", "sometimes", "Time", "u8", "ഞാൻ ചിലപ്പോൾ ചായ കുടിക്കും", "njaan chilappol chaaya kudikkum", "I sometimes drink tea"],
    ["lunch", "ഉച്ചഭക്ഷണം", "uchabhakshanam", "lunch", "Food", "u6", "ഉച്ചഭക്ഷണം തയ്യാറാണ്", "uchabhakshanam thayyaaraanu", "Lunch is ready"],
    ["dinner", "അത്താഴം", "athaazham", "dinner", "Food", "u6", "അത്താഴം എപ്പോഴാണ്?", "athaazham eppozhaanu?", "When is dinner?"],
  ],
  ta: [
    ["question", "கேள்வி", "kelvi", "question", "Common", "u7", "எனக்கு ஒரு கேள்வி இருக்கிறது", "enakku oru kelvi irukkiradhu", "I have a question"],
    ["answer", "பதில்", "badhil", "answer", "Common", "u7", "பதில் என்ன?", "badhil enna?", "What is the answer?"],
    ["language", "மொழி", "mozhi", "language", "Common", "u7", "தமிழ் என் மொழி", "tamizh en mozhi", "Tamil is my language"],
    ["people", "மக்கள்", "makkal", "people", "People", "u3", "இங்கே நிறைய மக்கள் இருக்கிறார்கள்", "inge niraiya makkal irukkiraargal", "There are many people here"],
    ["teacher", "ஆசிரியர்", "aasiriyar", "teacher", "People", "u3", "என் ஆசிரியர் மிகவும் நல்லவர்", "en aasiriyar migavum nallavar", "My teacher is very good"],
    ["to_meet", "சந்தி", "sandhi", "to meet", "Verbs", "u7", "நாளை சந்திப்போம்", "naalai sandhippom", "Let's meet tomorrow"],
    ["to_visit", "சென்று பார்", "sendru paar", "to visit (go and see)", "Verbs", "u7", "பாட்டியைச் சென்று பார்", "paattiyaich sendru paar", "Go and visit grandmother"],
    ["to_travel", "பயணம் செய்", "payanam sei", "to travel", "Verbs", "u7", "எனக்குப் பயணம் செய்வது பிடிக்கும்", "enakkup payanam seivadhu pidikkum", "I like travelling"],
    ["to_try", "முயற்சி செய்", "muyarchi sei", "to try", "Verbs", "u7", "மீண்டும் முயற்சி செய்", "meendum muyarchi sei", "Try again"],
    ["to_show", "காட்டு", "kaattu", "to show", "Verbs", "u7", "அந்தப் படத்தைக் காட்டு", "andhap padaththaik kaattu", "Show that picture"],
    ["to_send", "அனுப்பு", "anuppu", "to send", "Verbs", "u7", "எனக்கு ஒரு செய்தி அனுப்பு", "enakku oru seidhi anuppu", "Send me a message"],
    ["to_feel", "உணர்", "unar", "to feel", "Verbs", "u7", "நான் சோர்வாக உணர்கிறேன்", "naan sorvaaga unargiren", "I feel tired"],
    ["to_use", "பயன்படுத்து", "payanpaduththu", "to use", "Verbs", "u7", "இந்த போனைப் பயன்படுத்து", "indha phonaip payanpaduththu", "Use this phone"],
    ["important", "முக்கியம்", "mukkiyam", "important", "Common", "u7", "இது மிகவும் முக்கியம்", "idhu migavum mukkiyam", "This is very important"],
    ["different", "வேறு", "veru", "different, other", "Common", "u7", "இந்த நிறம் வேறு", "indha niram veru", "This colour is different"],
    ["same", "ஒரே", "ore", "the same", "Common", "u7", "இரண்டும் ஒரே மாதிரி", "irandum ore maadhiri", "Both are the same"],
    ["together", "சேர்ந்து", "serndhu", "together", "Common", "u7", "நாம் சேர்ந்து போவோம்", "naam serndhu povom", "Let's go together"],
    ["sometimes", "சில நேரங்களில்", "sila nerangalil", "sometimes", "Time", "u8", "நான் சில நேரங்களில் டீ குடிப்பேன்", "naan sila nerangalil tea kudippen", "I sometimes drink tea"],
    ["lunch", "மதிய உணவு", "madhiya unavu", "lunch", "Food", "u6", "மதிய உணவு தயார்", "madhiya unavu thayaar", "Lunch is ready"],
    ["dinner", "இரவு உணவு", "iravu unavu", "dinner", "Food", "u6", "இரவு உணவு எப்போது?", "iravu unavu eppodhu?", "When is dinner?"],
  ],
  ko: [
    ["question", "질문", "jilmun", "question", "Common", "u10", "질문이 있어요", "jilmuni isseoyo", "I have a question"],
    ["answer", "대답", "daedap", "answer", "Common", "u10", "대답해 주세요", "daedaphae juseyo", "Please answer"],
    ["language", "언어", "eoneo", "language", "Common", "u10", "한국어는 아름다운 언어예요", "hangugeoneun areumdaun eoneoyeyo", "Korean is a beautiful language"],
    ["people", "사람들", "saramdeul", "people", "People", "u2", "여기 사람들이 많아요", "yeogi saramdeuri manayo", "There are many people here"],
    ["teacher", "선생님", "seonsaengnim", "teacher", "People", "u2", "선생님이 정말 좋아요", "seonsaengnimi jeongmal joayo", "The teacher is really good"],
    ["to_meet", "만나다", "mannada", "to meet", "Verbs", "u6", "친구를 만나다가 시간을 잊었어요", "chingureul mannadaga siganeul ijeosseoyo", "I lost track of time meeting my friend"],
    ["to_visit", "방문하다", "bangmunhada", "to visit", "Verbs", "u6", "할머니 댁을 방문하고 싶어요", "halmeoni daegeul bangmunhago sipeoyo", "I want to visit grandmother's house"],
    ["to_travel", "여행하다", "yeohaenghada", "to travel", "Verbs", "u6", "여행하는 것을 좋아해요", "yeohaenghaneun geoseul joahaeyo", "I like travelling"],
    ["to_try", "시도하다", "sidohada", "to try", "Verbs", "u6", "다시 시도하세요", "dasi sidohaseyo", "Try again"],
    ["to_show", "보여주다", "boyeojuda", "to show", "Verbs", "u6", "사진을 보여주세요", "sajineul boyeojuseyo", "Please show me the photo"],
    ["to_send", "보내다", "bonaeda", "to send", "Verbs", "u6", "문자를 보내다가 실수했어요", "munjareul bonaedaga silsuhaesseoyo", "I made a mistake while sending a text"],
    ["to_feel", "느끼다", "neukkida", "to feel", "Verbs", "u6", "피곤함을 느끼다가 잠이 들었어요", "pigonhameul neukkidaga jami deureosseoyo", "I felt tired and fell asleep"],
    ["to_use", "사용하다", "sayonghada", "to use", "Verbs", "u6", "이 전화를 사용하세요", "i jeonhwareul sayonghaseyo", "Use this phone"],
    ["important", "중요하다", "jungyohada", "important", "Common", "u10", "건강이 중요하다", "geongangi jungyohada", "Health is important"],
    ["different", "다르다", "dareuda", "different", "Common", "u10", "우리는 서로 다르다", "urineun seoro dareuda", "We are different from each other"],
    ["same", "같다", "gatda", "the same", "Common", "u10", "맛이 같다", "masi gatda", "The taste is the same"],
    ["together", "같이", "gachi", "together", "Common", "u10", "같이 가요", "gachi gayo", "Let's go together"],
    ["sometimes", "가끔", "gakkeum", "sometimes", "Time", "u8", "가끔 차를 마셔요", "gakkeum chareul masyeoyo", "I sometimes drink tea"],
    ["lunch", "점심", "jeomsim", "lunch", "Food", "u5", "점심 먹었어요?", "jeomsim meogeosseoyo?", "Did you have lunch?"],
    ["dinner", "저녁", "jeonyeok", "dinner, evening", "Food", "u5", "저녁 먹었어요?", "jeonyeok meogeosseoyo?", "Did you have dinner?"],
  ],
  ja: [
    ["question", "質問", "shitsumon", "question", "Common", "u10", "質問があります", "shitsumon ga arimasu", "I have a question"],
    ["answer", "答え", "kotae", "answer", "Common", "u10", "答えは何ですか", "kotae wa nan desu ka", "What is the answer?"],
    ["language", "言語", "gengo", "language", "Common", "u10", "日本語は難しい言語です", "nihongo wa muzukashii gengo desu", "Japanese is a difficult language"],
    ["people", "人々", "hitobito", "people", "People", "u2", "ここに人々が集まります", "koko ni hitobito ga atsumarimasu", "People gather here"],
    ["teacher", "先生", "sensei", "teacher", "People", "u2", "先生はとても優しいです", "sensei wa totemo yasashii desu", "The teacher is very kind"],
    ["to_meet", "会う", "au", "to meet", "Verbs", "u6", "明日友達に会う", "ashita tomodachi ni au", "I'm meeting a friend tomorrow"],
    ["to_visit", "訪ねる", "tazuneru", "to visit", "Verbs", "u6", "祖母を訪ねる", "sobo wo tazuneru", "I visit my grandmother"],
    ["to_travel", "旅行する", "ryokou suru", "to travel", "Verbs", "u6", "旅行するのが好きです", "ryokou suru no ga suki desu", "I like to travel"],
    ["to_try", "やってみる", "yatte miru", "to try", "Verbs", "u6", "もう一度やってみる", "mou ichido yatte miru", "I'll try once more"],
    ["to_show", "見せる", "miseru", "to show", "Verbs", "u6", "写真を見せる", "shashin wo miseru", "I show the photo"],
    ["to_send", "送る", "okuru", "to send", "Verbs", "u6", "メッセージを送る", "messeeji wo okuru", "I send a message"],
    ["to_feel", "感じる", "kanjiru", "to feel", "Verbs", "u6", "寒さを感じる", "samusa wo kanjiru", "I feel the cold"],
    ["to_use", "使う", "tsukau", "to use", "Verbs", "u6", "この電話を使う", "kono denwa wo tsukau", "I use this phone"],
    ["important", "大切", "taisetsu", "important, precious", "Common", "u10", "家族は大切です", "kazoku wa taisetsu desu", "Family is important"],
    ["different", "違う", "chigau", "different, to differ", "Common", "u10", "色が違う", "iro ga chigau", "The colour is different"],
    ["same", "同じ", "onaji", "the same", "Common", "u10", "二つは同じです", "futatsu wa onaji desu", "The two are the same"],
    ["together", "一緒に", "issho ni", "together", "Common", "u10", "一緒に行きましょう", "issho ni ikimashou", "Let's go together"],
    ["sometimes", "時々", "tokidoki", "sometimes", "Time", "u8", "時々お茶を飲みます", "tokidoki ocha wo nomimasu", "I sometimes drink tea"],
    ["lunch", "昼ご飯", "hirugohan", "lunch", "Food", "u5", "昼ご飯の時間です", "hirugohan no jikan desu", "It's lunchtime"],
    ["dinner", "晩ご飯", "bangohan", "dinner", "Food", "u5", "晩ご飯は何ですか", "bangohan wa nan desu ka", "What's for dinner?"],
  ],
  zh: [
    ["question", "问题", "wèntí", "question, problem", "Common", "u10", "我有一个问题", "wǒ yǒu yí ge wèntí", "I have a question"],
    ["answer", "答案", "dá'àn", "answer", "Common", "u10", "答案是什么？", "dá'àn shì shénme?", "What is the answer?"],
    ["language", "语言", "yǔyán", "language", "Common", "u10", "中文是一种美丽的语言", "zhōngwén shì yì zhǒng měilì de yǔyán", "Chinese is a beautiful language"],
    ["people", "人们", "rénmen", "people", "People", "u2", "人们都很友好", "rénmen dōu hěn yǒuhǎo", "People are all very friendly"],
    ["teacher", "老师", "lǎoshī", "teacher", "People", "u2", "老师很好", "lǎoshī hěn hǎo", "The teacher is very good"],
    ["to_meet", "见面", "jiànmiàn", "to meet", "Verbs", "u6", "明天见面吧", "míngtiān jiànmiàn ba", "Let's meet tomorrow"],
    ["to_visit", "拜访", "bàifǎng", "to visit", "Verbs", "u6", "我们去拜访奶奶", "wǒmen qù bàifǎng nǎinai", "We're going to visit grandma"],
    ["to_travel", "旅行", "lǚxíng", "to travel", "Verbs", "u6", "我喜欢旅行", "wǒ xǐhuan lǚxíng", "I like to travel"],
    ["to_try", "试", "shì", "to try", "Verbs", "u6", "再试一次", "zài shì yí cì", "Try again"],
    ["to_show", "展示", "zhǎnshì", "to show", "Verbs", "u6", "请展示你的照片", "qǐng zhǎnshì nǐ de zhàopiàn", "Please show your photos"],
    ["to_send", "发", "fā", "to send", "Verbs", "u6", "给我发消息", "gěi wǒ fā xiāoxi", "Send me a message"],
    ["to_feel", "觉得", "juéde", "to feel, to think", "Verbs", "u6", "我觉得很累", "wǒ juéde hěn lèi", "I feel very tired"],
    ["to_use", "用", "yòng", "to use", "Verbs", "u6", "用这个手机", "yòng zhège shǒujī", "Use this phone"],
    ["important", "重要", "zhòngyào", "important", "Common", "u10", "这很重要", "zhè hěn zhòngyào", "This is very important"],
    ["different", "不同", "bùtóng", "different", "Common", "u10", "颜色不同", "yánsè bùtóng", "The colours are different"],
    ["same", "一样", "yíyàng", "the same", "Common", "u10", "两个一样", "liǎng ge yíyàng", "The two are the same"],
    ["together", "一起", "yìqǐ", "together", "Common", "u10", "我们一起吃饭吧", "wǒmen yìqǐ chīfàn ba", "Let's eat together"],
    ["sometimes", "有时候", "yǒushíhou", "sometimes", "Time", "u8", "我有时候喝茶", "wǒ yǒushíhou hē chá", "I sometimes drink tea"],
    ["lunch", "午饭", "wǔfàn", "lunch", "Food", "u5", "午饭好了", "wǔfàn hǎo le", "Lunch is ready"],
    ["dinner", "晚饭", "wǎnfàn", "dinner", "Food", "u5", "晚饭吃什么？", "wǎnfàn chī shénme?", "What's for dinner?"],
  ],
  tr: [
    ["question", "soru", "", "question", "Common", "u10", "Bir sorum var", "", "I have a question"],
    ["answer", "cevap", "", "answer", "Common", "u10", "Cevap ne?", "", "What's the answer?"],
    ["language", "dil", "", "language, tongue", "Common", "u10", "Türkçe güzel bir dil", "", "Turkish is a beautiful language"],
    ["people", "insanlar", "", "people", "People", "u4", "Burada çok insan var", "", "There are many people here"],
    ["teacher", "öğretmen", "", "teacher", "People", "u4", "Öğretmenim çok iyi", "", "My teacher is very good"],
    ["to_meet", "buluşmak", "", "to meet", "Verbs", "u6", "Yarın buluşalım", "", "Let's meet tomorrow"],
    ["to_visit", "ziyaret etmek", "", "to visit", "Verbs", "u6", "Anneannemi ziyaret etmek istiyorum", "", "I want to visit my grandmother"],
    ["to_travel", "seyahat etmek", "", "to travel", "Verbs", "u6", "Seyahat etmeyi seviyorum", "", "I love to travel"],
    ["to_try", "denemek", "", "to try", "Verbs", "u6", "Tekrar dene", "", "Try again"],
    ["to_show", "göstermek", "", "to show", "Verbs", "u6", "Fotoğrafı bana göster", "", "Show me the photo"],
    ["to_send", "göndermek", "", "to send", "Verbs", "u6", "Bana mesaj gönder", "", "Send me a message"],
    ["to_feel", "hissetmek", "", "to feel", "Verbs", "u6", "Kendimi yorgun hissediyorum", "", "I feel tired"],
    ["to_use", "kullanmak", "", "to use", "Verbs", "u6", "Bu telefonu kullan", "", "Use this phone"],
    ["important", "önemli", "", "important", "Adjectives", "u8", "Bu çok önemli", "", "This is very important"],
    ["different", "farklı", "", "different", "Adjectives", "u8", "Bu renk farklı", "", "This colour is different"],
    ["same", "aynı", "", "the same", "Adjectives", "u8", "İkisi de aynı", "", "Both are the same"],
    ["together", "birlikte", "", "together", "Common", "u10", "Birlikte gidelim", "", "Let's go together"],
    ["sometimes", "bazen", "", "sometimes", "Time", "u9", "Bazen çay içerim", "", "I sometimes drink tea"],
    ["lunch", "öğle yemeği", "", "lunch", "Food", "u5", "Öğle yemeği hazır", "", "Lunch is ready"],
    ["dinner", "akşam yemeği", "", "dinner", "Food", "u5", "Akşam yemeği ne zaman?", "", "When is dinner?"],
  ],
  so: [
    ["question", "su'aal", "", "question", "Common", "u7", "Su'aal baan qabaa", "", "I have a question"],
    ["answer", "jawaab", "", "answer", "Common", "u7", "Jawaabtu waa maxay?", "", "What is the answer?"],
    ["language", "luqad", "", "language", "Common", "u7", "Af-Soomaaligu waa luqad qurux badan", "", "Somali is a beautiful language"],
    ["people", "dad", "", "people", "People", "u3", "Halkan dad badan baa jooga", "", "There are many people here"],
    ["teacher", "macallin", "", "teacher", "People", "u3", "Macallinkaygu aad buu u fiican yahay", "", "My teacher is very good"],
    ["to_meet", "kulan", "", "to meet", "Verbs", "u7", "Berri aan kulanno", "", "Let's meet tomorrow"],
    ["to_visit", "booqo", "", "to visit", "Verbs", "u7", "Ayeeyo ayaan booqanaynaa", "", "We are visiting grandmother"],
    ["to_travel", "safar", "", "to travel, journey", "Verbs", "u7", "Waxaan jeclahay inaan safro", "", "I like to travel"],
    ["to_try", "isku day", "", "to try", "Verbs", "u7", "Mar kale isku day", "", "Try again"],
    ["to_show", "tus", "", "to show", "Verbs", "u7", "Sawirka i tus", "", "Show me the picture"],
    ["to_send", "dir", "", "to send", "Verbs", "u7", "Fariin ii dir", "", "Send me a message"],
    ["to_feel", "dareen", "", "to feel", "Verbs", "u7", "Waxaan dareemayaa daal", "", "I feel tired"],
    ["to_use", "isticmaal", "", "to use", "Verbs", "u7", "Telefoonkan isticmaal", "", "Use this phone"],
    ["important", "muhiim", "", "important", "Common", "u7", "Tani waa muhiim", "", "This is important"],
    ["different", "duwan", "", "different", "Common", "u7", "Labadan waa kala duwan yihiin", "", "These two are different"],
    ["same", "isku mid", "", "the same", "Common", "u7", "Labadu waa isku mid", "", "The two are the same"],
    ["together", "wada", "", "together", "Common", "u7", "Aan wada tagno", "", "Let's go together"],
    ["sometimes", "mararka qaarkood", "", "sometimes", "Time", "u8", "Mararka qaarkood shaah ayaan cabbaa", "", "I sometimes drink tea"],
    ["lunch", "qado", "", "lunch", "Food", "u6", "Qadadu waa diyaar", "", "Lunch is ready"],
    ["dinner", "casho", "", "dinner", "Food", "u6", "Goormaa cashadu tahay?", "", "When is dinner?"],
  ],
  yo: [
    ["question", "ìbéèrè", "", "question", "Common", "u8", "Mo ní ìbéèrè kan", "", "I have a question"],
    ["answer", "ìdáhùn", "", "answer", "Common", "u8", "Kí ni ìdáhùn?", "", "What is the answer?"],
    ["language", "èdè", "", "language", "Common", "u8", "Yorùbá ni èdè mi", "", "Yoruba is my language"],
    ["people", "àwọn ènìyàn", "", "people", "People", "u2", "Àwọn ènìyàn pọ̀ níbí", "", "There are many people here"],
    ["teacher", "olùkọ́", "", "teacher", "People", "u2", "Olùkọ́ mi dára gan-an", "", "My teacher is very good"],
    ["to_meet", "pàdé", "", "to meet", "Verbs", "u6", "Ẹ jẹ́ ká pàdé lọ́la", "", "Let's meet tomorrow"],
    ["to_visit", "ṣe àbẹ̀wò", "", "to visit", "Verbs", "u6", "A máa ṣe àbẹ̀wò sí ìyá àgbà", "", "We will visit grandmother"],
    ["to_travel", "rìnrìn àjò", "", "to travel", "Verbs", "u6", "Mo fẹ́ràn láti rìnrìn àjò", "", "I love to travel"],
    ["to_try", "gbìyànjú", "", "to try", "Verbs", "u6", "Gbìyànjú lẹ́ẹ̀kan sí i", "", "Try again"],
    ["to_show", "fi hàn", "", "to show", "Verbs", "u6", "Fi àwòrán náà hàn mí", "", "Show me the picture"],
    ["to_send", "fi ránṣẹ́", "", "to send", "Verbs", "u6", "Fi ránṣẹ́ sí mi", "", "Send it to me"],
    ["to_feel", "nímọ̀lára", "", "to feel", "Verbs", "u6", "Mo nímọ̀lára ìtura", "", "I feel relieved"],
    ["to_use", "lò", "", "to use", "Verbs", "u6", "Mo máa ń lò ó", "", "I use it often"],
    ["important", "pàtàkì", "", "important", "Common", "u8", "Èyí ṣe pàtàkì gan-an", "", "This is very important"],
    ["different", "yàtọ̀", "", "different", "Common", "u8", "Àwọ̀ yìí yàtọ̀", "", "This colour is different"],
    ["same", "bákan náà", "", "the same", "Common", "u8", "Méjèèjì jẹ́ bákan náà", "", "Both are the same"],
    ["together", "papọ̀", "", "together", "Common", "u8", "Ẹ jẹ́ ká lọ papọ̀", "", "Let's go together"],
    ["sometimes", "nígbà míì", "", "sometimes", "Time", "u8", "Nígbà míì mo máa ń mu tíì", "", "I sometimes drink tea"],
    ["lunch", "oúnjẹ ọ̀sán", "", "lunch", "Food", "u5", "Oúnjẹ ọ̀sán ti ṣetán", "", "Lunch is ready"],
    ["dinner", "oúnjẹ alẹ́", "", "dinner", "Food", "u5", "Ìgbà wo ni oúnjẹ alẹ́?", "", "When is dinner?"],
  ],
  tl: [
    ["question", "tanong", "", "question", "Common", "u7", "May tanong ako", "", "I have a question"],
    ["answer", "sagot", "", "answer", "Common", "u7", "Ano ang sagot?", "", "What is the answer?"],
    ["language", "wika", "", "language", "Common", "u7", "Tagalog ang wika ko", "", "Tagalog is my language"],
    ["people", "mga tao", "", "people", "People", "u3", "Mababait ang mga tao dito", "", "The people here are kind"],
    ["teacher", "guro", "", "teacher", "People", "u3", "Mabait ang guro namin", "", "Our teacher is kind"],
    ["to_meet", "magkita", "", "to meet", "Verbs", "u7", "Magkita tayo bukas", "", "Let's meet tomorrow"],
    ["to_visit", "dumalaw", "", "to visit", "Verbs", "u7", "Gusto kong dumalaw kay Lola", "", "I want to visit Grandma"],
    ["to_travel", "maglakbay", "", "to travel", "Verbs", "u7", "Gusto kong maglakbay", "", "I want to travel"],
    ["to_try", "subukan", "", "to try", "Verbs", "u7", "Subukan mo ulit", "", "Try again"],
    ["to_show", "ipakita", "", "to show", "Verbs", "u7", "Ipakita mo sa akin ang litrato", "", "Show me the photo"],
    ["to_send", "magpadala", "", "to send", "Verbs", "u7", "Magpadala ka ng mensahe", "", "Send a message"],
    ["to_feel", "pakiramdam", "", "feeling, to feel", "Verbs", "u7", "Masama ang pakiramdam ko", "", "I don't feel well"],
    ["to_use", "gamitin", "", "to use", "Verbs", "u7", "Gamitin mo ang teleponong ito", "", "Use this phone"],
    ["important", "mahalaga", "", "important", "Common", "u7", "Mahalaga ito", "", "This is important"],
    ["different", "iba", "", "different, other", "Common", "u7", "Iba ang kulay na ito", "", "This colour is different"],
    ["same", "pareho", "", "the same", "Common", "u7", "Pareho silang dalawa", "", "They're both the same"],
    ["together", "magkasama", "", "together", "Common", "u7", "Magkasama tayong pupunta", "", "We'll go together"],
    ["sometimes", "minsan", "", "sometimes", "Time", "u8", "Minsan umiinom ako ng tsaa", "", "I sometimes drink tea"],
    ["lunch", "tanghalian", "", "lunch", "Food", "u6", "Handa na ang tanghalian", "", "Lunch is ready"],
    ["dinner", "hapunan", "", "dinner", "Food", "u6", "Anong oras ang hapunan?", "", "What time is dinner?"],
  ],
  vi: [
    ["question", "câu hỏi", "", "question", "Common", "u8", "Tôi có một câu hỏi", "", "I have a question"],
    ["answer", "câu trả lời", "", "answer", "Common", "u8", "Câu trả lời là gì?", "", "What is the answer?"],
    ["language", "ngôn ngữ", "", "language", "Common", "u8", "Tiếng Việt là một ngôn ngữ đẹp", "", "Vietnamese is a beautiful language"],
    ["people", "mọi người", "", "people, everyone", "People", "u2", "Mọi người ở đây rất thân thiện", "", "People here are very friendly"],
    ["teacher", "giáo viên", "", "teacher", "People", "u2", "Giáo viên của tôi rất tốt", "", "My teacher is very good"],
    ["to_meet", "gặp", "", "to meet", "Verbs", "u6", "Mai gặp nhé", "", "Let's meet tomorrow"],
    ["to_visit", "thăm", "", "to visit", "Verbs", "u6", "Chúng tôi đi thăm bà", "", "We're going to visit grandma"],
    ["to_travel", "du lịch", "", "to travel", "Verbs", "u6", "Tôi thích đi du lịch", "", "I like to travel"],
    ["to_try", "thử", "", "to try", "Verbs", "u6", "Thử lại đi", "", "Try again"],
    ["to_show", "cho xem", "", "to show", "Verbs", "u6", "Cho tôi xem ảnh", "", "Show me the photo"],
    ["to_send", "gửi", "", "to send", "Verbs", "u6", "Gửi tin nhắn cho tôi", "", "Send me a message"],
    ["to_feel", "cảm thấy", "", "to feel", "Verbs", "u6", "Tôi cảm thấy mệt", "", "I feel tired"],
    ["to_use", "dùng", "", "to use", "Verbs", "u6", "Dùng điện thoại này đi", "", "Use this phone"],
    ["important", "quan trọng", "", "important", "Common", "u8", "Cái này rất quan trọng", "", "This is very important"],
    ["different", "khác", "", "different, other", "Common", "u8", "Màu này khác", "", "This colour is different"],
    ["same", "giống nhau", "", "the same, alike", "Common", "u8", "Hai cái giống nhau", "", "The two are the same"],
    ["together", "cùng nhau", "", "together", "Common", "u8", "Chúng ta đi cùng nhau nhé", "", "Let's go together"],
    ["sometimes", "thỉnh thoảng", "", "sometimes", "Time", "u8", "Thỉnh thoảng tôi uống trà", "", "I sometimes drink tea"],
    ["lunch", "bữa trưa", "", "lunch", "Food", "u5", "Bữa trưa xong rồi", "", "Lunch is ready"],
    ["dinner", "bữa tối", "", "dinner", "Food", "u5", "Mấy giờ ăn bữa tối?", "", "What time is dinner?"],
  ],
  pcm: [
    ["question", "question", "", "question", "Common", "u6", "I get one question", "", "I have a question"],
    ["answer", "answer", "", "answer", "Common", "u6", "Wetin be the answer?", "", "What is the answer?"],
    ["language", "language", "", "language", "Common", "u6", "Pidgin na sweet language", "", "Pidgin is a lovely language"],
    ["people", "people", "", "people", "People", "u2", "People plenty for here", "", "There are many people here"],
    ["teacher", "teacher", "", "teacher", "People", "u2", "My teacher sabi book well well", "", "My teacher really knows her stuff"],
    ["to_meet", "meet", "", "to meet", "Verbs", "u6", "Make we meet tomorrow", "", "Let's meet tomorrow"],
    ["to_visit", "visit", "", "to visit", "Verbs", "u6", "We go visit Mama for village", "", "We'll visit Mama in the village"],
    ["to_travel", "travel", "", "to travel", "Verbs", "u6", "I wan travel go Lagos", "", "I want to travel to Lagos"],
    ["to_try", "try", "", "to try", "Verbs", "u6", "Try am again", "", "Try it again"],
    ["to_show", "show", "", "to show", "Verbs", "u6", "Show me the foto", "", "Show me the photo"],
    ["to_send", "send", "", "to send", "Verbs", "u6", "Send me message", "", "Send me a message"],
    ["to_feel", "feel", "", "to feel", "Verbs", "u6", "I dey feel cold", "", "I'm feeling cold"],
    ["to_use", "use", "", "to use", "Verbs", "u6", "Make you use dis phone", "", "Use this phone"],
    ["important", "important", "", "important", "Common", "u6", "Dis one important well well", "", "This is very important"],
    ["different", "different", "", "different", "Common", "u6", "Dis colour different", "", "This colour is different"],
    ["same", "same", "", "the same", "Common", "u6", "Both of dem na the same", "", "They're both the same"],
    ["together", "together", "", "together", "Common", "u6", "Make we go together", "", "Let's go together"],
    ["sometimes", "sometimes", "", "sometimes", "Time", "u4", "Sometimes I dey drink tea", "", "I sometimes drink tea"],
    ["lunch", "lunch", "", "lunch", "Food", "u5", "Lunch don ready", "", "Lunch is ready"],
    ["dinner", "dinner", "", "dinner", "Food", "u5", "When dinner go ready?", "", "When will dinner be ready?"],
  ],
  id: [
    ["question", "pertanyaan", "", "question", "Common", "u6", "Saya punya pertanyaan", "", "I have a question"],
    ["answer", "jawaban", "", "answer", "Common", "u6", "Apa jawabannya?", "", "What's the answer?"],
    ["language", "bahasa", "", "language", "Common", "u6", "Bahasa Indonesia mudah", "", "The Indonesian language is easy"],
    ["people", "orang-orang", "", "people", "People", "u2", "Orang-orang di sini ramah", "", "The people here are friendly"],
    ["teacher", "guru", "", "teacher", "People", "u2", "Guru saya baik sekali", "", "My teacher is very kind"],
    ["to_meet", "bertemu", "", "to meet", "Verbs", "u6", "Kita bertemu besok", "", "We'll meet tomorrow"],
    ["to_visit", "mengunjungi", "", "to visit", "Verbs", "u6", "Kami mengunjungi nenek", "", "We are visiting grandma"],
    ["to_travel", "bepergian", "", "to travel", "Verbs", "u6", "Saya suka bepergian", "", "I like to travel"],
    ["to_try", "mencoba", "", "to try", "Verbs", "u6", "Saya mau mencoba lagi", "", "I want to try again"],
    ["to_show", "menunjukkan", "", "to show", "Verbs", "u6", "Dia menunjukkan fotonya", "", "She shows her photo"],
    ["to_send", "mengirim", "", "to send", "Verbs", "u6", "Saya mengirim pesan", "", "I'm sending a message"],
    ["to_feel", "merasa", "", "to feel", "Verbs", "u6", "Saya merasa lelah", "", "I feel tired"],
    ["to_use", "menggunakan", "", "to use", "Verbs", "u6", "Saya menggunakan telepon ini", "", "I use this phone"],
    ["important", "penting", "", "important", "Common", "u6", "Ini sangat penting", "", "This is very important"],
    ["different", "berbeda", "", "different", "Common", "u6", "Warnanya berbeda", "", "The colour is different"],
    ["same", "sama", "", "the same", "Common", "u6", "Keduanya sama", "", "Both are the same"],
    ["together", "bersama", "", "together", "Common", "u6", "Ayo pergi bersama", "", "Let's go together"],
    ["sometimes", "kadang-kadang", "", "sometimes", "Time", "u5", "Kadang-kadang saya minum teh", "", "I sometimes drink tea"],
    ["lunch", "makan siang", "", "lunch", "Food", "u5", "Makan siang sudah siap", "", "Lunch is ready"],
    ["dinner", "makan malam", "", "dinner", "Food", "u5", "Kapan makan malam?", "", "When is dinner?"],
  ],
  de: [
    ["question", "die Frage", "", "question", "Common", "u13", "Die Frage ist einfach", "", "The question is easy"],
    ["answer", "die Antwort", "", "answer", "Common", "u13", "Die Antwort ist richtig", "", "The answer is right"],
    ["language", "die Sprache", "", "language", "Common", "u13", "Die Sprache ist schön", "", "The language is beautiful"],
    ["people", "die Leute", "", "people", "People", "u2", "Die Leute hier sind nett", "", "The people here are nice"],
    ["teacher", "der Lehrer", "", "teacher", "People", "u2", "Der Lehrer ist sehr gut", "", "The teacher is very good"],
    ["to_meet", "treffen", "", "to meet", "Verbs", "u6", "Wir treffen uns morgen", "", "We're meeting tomorrow"],
    ["to_visit", "besuchen", "", "to visit", "Verbs", "u6", "Wir besuchen Oma", "", "We're visiting Grandma"],
    ["to_travel", "reisen", "", "to travel", "Verbs", "u6", "Ich reise gern", "", "I like to travel"],
    ["to_try", "versuchen", "", "to try", "Verbs", "u6", "Versuch es noch einmal", "", "Try again"],
    ["to_show", "zeigen", "", "to show", "Verbs", "u6", "Zeig mir das Foto", "", "Show me the photo"],
    ["to_send", "schicken", "", "to send", "Verbs", "u6", "Schick mir eine Nachricht", "", "Send me a message"],
    ["to_feel", "fühlen", "", "to feel", "Verbs", "u6", "Ich fühle mich müde", "", "I feel tired"],
    ["to_use", "benutzen", "", "to use", "Verbs", "u6", "Benutz dieses Handy", "", "Use this phone"],
    ["important", "wichtig", "", "important", "Common", "u13", "Das ist sehr wichtig", "", "This is very important"],
    ["different", "anders", "", "different", "Common", "u13", "Diese Farbe ist anders", "", "This colour is different"],
    ["same", "gleich", "", "the same", "Common", "u13", "Beide sind gleich", "", "Both are the same"],
    ["together", "zusammen", "", "together", "Common", "u13", "Lass uns zusammen gehen", "", "Let's go together"],
    ["sometimes", "manchmal", "", "sometimes", "Time", "u8", "Manchmal trinke ich Tee", "", "I sometimes drink tea"],
    ["lunch", "das Mittagessen", "", "lunch", "Food", "u5", "Das Mittagessen ist fertig", "", "Lunch is ready"],
    ["dinner", "das Abendessen", "", "dinner", "Food", "u5", "Das Abendessen ist um sieben", "", "Dinner is at seven"],
  ],
  es: [
    ["question", "la pregunta", "", "question", "Common", "u13", "La pregunta es fácil", "", "The question is easy"],
    ["answer", "la respuesta", "", "answer", "Common", "u13", "La respuesta es correcta", "", "The answer is correct"],
    ["language", "el idioma", "", "language", "Common", "u13", "El idioma es bonito", "", "The language is beautiful"],
    ["people", "la gente", "", "people", "People", "u2", "La gente aquí es amable", "", "The people here are kind"],
    ["teacher", "el maestro", "", "teacher", "People", "u2", "El maestro es muy bueno", "", "The teacher is very good"],
    ["to_meet", "encontrarse", "", "to meet", "Verbs", "u6", "Nos encontramos mañana", "", "We're meeting tomorrow"],
    ["to_visit", "visitar", "", "to visit", "Verbs", "u6", "Vamos a visitar a la abuela", "", "We're going to visit Grandma"],
    ["to_travel", "viajar", "", "to travel", "Verbs", "u6", "Me gusta viajar", "", "I like to travel"],
    ["to_try", "intentar", "", "to try", "Verbs", "u6", "Voy a intentar otra vez", "", "I'll try again"],
    ["to_show", "mostrar", "", "to show", "Verbs", "u6", "Quiero mostrar la foto", "", "I want to show the photo"],
    ["to_send", "enviar", "", "to send", "Verbs", "u6", "Voy a enviar un mensaje", "", "I'm going to send a message"],
    ["to_feel", "sentir", "", "to feel", "Verbs", "u6", "Puedo sentir el frío", "", "I can feel the cold"],
    ["to_use", "usar", "", "to use", "Verbs", "u6", "Puedes usar este teléfono", "", "You can use this phone"],
    ["important", "importante", "", "important", "Common", "u13", "Esto es muy importante", "", "This is very important"],
    ["different", "diferente", "", "different", "Common", "u13", "Este color es diferente", "", "This colour is different"],
    ["same", "igual", "", "the same", "Common", "u13", "Los dos son iguales", "", "Both are the same"],
    ["together", "juntos", "", "together", "Common", "u13", "Vamos juntos", "", "Let's go together"],
    ["sometimes", "a veces", "", "sometimes", "Time", "u8", "A veces tomo té", "", "I sometimes drink tea"],
    ["lunch", "el almuerzo", "", "lunch", "Food", "u5", "El almuerzo está listo", "", "Lunch is ready"],
    ["dinner", "la cena", "", "dinner", "Food", "u5", "La cena es a las ocho", "", "Dinner is at eight"],
  ],
  fr: [
    ["question", "la question", "", "question", "Common", "u13", "La question est simple", "", "The question is simple"],
    ["answer", "la réponse", "", "answer", "Common", "u13", "La réponse est juste", "", "The answer is right"],
    ["language", "la langue", "", "language, tongue", "Common", "u13", "La langue française est belle", "", "The French language is beautiful"],
    ["people", "les gens", "", "people", "People", "u2", "Les gens sont gentils ici", "", "People are kind here"],
    ["teacher", "le professeur", "", "teacher", "People", "u2", "Le professeur est très bon", "", "The teacher is very good"],
    ["to_meet", "rencontrer", "", "to meet", "Verbs", "u6", "On peut se rencontrer demain", "", "We can meet tomorrow"],
    ["to_visit", "rendre visite", "", "to visit (someone)", "Verbs", "u6", "Nous allons rendre visite à mamie", "", "We're going to visit Grandma"],
    ["to_travel", "voyager", "", "to travel", "Verbs", "u6", "J'aime voyager", "", "I like to travel"],
    ["to_try", "essayer", "", "to try", "Verbs", "u6", "Je vais essayer encore", "", "I'll try again"],
    ["to_show", "montrer", "", "to show", "Verbs", "u6", "Je veux te montrer la photo", "", "I want to show you the photo"],
    ["to_send", "envoyer", "", "to send", "Verbs", "u6", "Je vais envoyer un message", "", "I'm going to send a message"],
    ["to_feel", "sentir", "", "to feel", "Verbs", "u6", "Je me sens fatigué", "", "I feel tired"],
    ["to_use", "utiliser", "", "to use", "Verbs", "u6", "Tu peux utiliser ce téléphone", "", "You can use this phone"],
    ["important", "important", "", "important", "Common", "u13", "C'est très important", "", "It's very important"],
    ["different", "différent", "", "different", "Common", "u13", "Cette couleur est différente", "", "This colour is different"],
    ["same", "pareil", "", "the same", "Common", "u13", "Les deux sont pareils", "", "Both are the same"],
    ["together", "ensemble", "", "together", "Common", "u13", "Allons-y ensemble", "", "Let's go together"],
    ["sometimes", "parfois", "", "sometimes", "Time", "u8", "Parfois je bois du thé", "", "I sometimes drink tea"],
    ["lunch", "le déjeuner", "", "lunch", "Food", "u5", "Le déjeuner est prêt", "", "Lunch is ready"],
    ["dinner", "le dîner", "", "dinner", "Food", "u5", "Le dîner est à huit heures", "", "Dinner is at eight"],
  ],
};
export const V112_EXTEND = {};
