// =============================================================================
// AUDIO — three-tier system, transparent to UI.
// =============================================================================
// Priority order:
//   1. Pre-generated MP3 file at /audio/{langCode}/{wordId}.mp3 (BEST)
//      Generated by scripts/generate-audio.js using Google Cloud TTS.
//      These are the "real" audio files we serve to every user identically.
//
//   2. Browser SpeechSynthesis (fallback for words without MP3 yet)
//      Device-dependent quality. May be silent on some devices.
//
//   3. Silent (last resort) — UI hides audio button via hasAudioFor()
//
// The UI calls speak(text, langCode, options) with optional `audioId` to use
// a pre-generated file. If the file doesn't exist, we fall back automatically.
// =============================================================================

let voicesLoaded = false;
let voicesCache = [];
let mp3AvailabilityCache = new Map(); // 'langCode/wordId' -> true|false (cached HEAD requests)
let activeAudio = null;

function ensureVoices() {
  if (typeof window === "undefined" || !window.speechSynthesis) return;
  voicesCache = window.speechSynthesis.getVoices();
  if (voicesCache.length > 0) voicesLoaded = true;
  else {
    window.speechSynthesis.onvoiceschanged = () => {
      voicesCache = window.speechSynthesis.getVoices();
      voicesLoaded = true;
    };
  }
}

if (typeof window !== "undefined") ensureVoices();

function bestVoice(langCode) {
  if (!voicesCache.length) return null;
  let v = voicesCache.find((x) => x.lang === langCode);
  if (v) return v;
  const lang2 = langCode.split("-")[0];
  v = voicesCache.find((x) => x.lang.startsWith(lang2));
  return v || null;
}

/** Build the URL where the pre-generated MP3 should live. */
function mp3Url(langCode, audioId) {
  // Strip region: "ur-PK" -> "ur" for folder naming
  const lang = (langCode || "").split("-")[0];
  return `/audio/${lang}/${audioId}.mp3`;
}

/** Try to play a pre-generated MP3. Resolves true on success, false otherwise. */
async function tryPlayMp3(langCode, audioId) {
  if (!audioId) return false;
  const url = mp3Url(langCode, audioId);

  // Check cache first
  const cacheKey = `${langCode}/${audioId}`;
  if (mp3AvailabilityCache.get(cacheKey) === false) return false;

  return new Promise((resolve) => {
    const audio = new Audio(url);
    activeAudio = audio;
    let settled = false;

    audio.addEventListener("canplaythrough", () => {
      if (settled) return;
      audio.play()
        .then(() => {
          mp3AvailabilityCache.set(cacheKey, true);
          settled = true;
        })
        .catch(() => {
          if (!settled) { settled = true; resolve(false); }
        });
    }, { once: true });

    audio.addEventListener("ended", () => { if (!settled) { settled = true; resolve(true); } });
    audio.addEventListener("error", () => {
      if (settled) return;
      mp3AvailabilityCache.set(cacheKey, false);
      settled = true;
      resolve(false);
    });

    // Set a timeout so we don't hang forever
    setTimeout(() => {
      if (!settled) { settled = true; resolve(false); }
    }, 3000);

    audio.load();
  });
}

/** Speak using browser TTS. Resolves when speech ends. */
function speakWithBrowser(text, langCode, { rate = 0.85, pitch = 1 } = {}) {
  return new Promise((resolve) => {
    if (typeof window === "undefined" || !window.speechSynthesis) return resolve(false);
    try {
      window.speechSynthesis.cancel();
      const u = new SpeechSynthesisUtterance(text);
      u.lang = langCode;
      u.rate = rate;
      u.pitch = pitch;
      const v = bestVoice(langCode);
      if (!v) return resolve(false); // no voice for this language
      u.voice = v;
      u.onend = () => resolve(true);
      u.onerror = () => resolve(false);
      window.speechSynthesis.speak(u);
    } catch {
      resolve(false);
    }
  });
}

/**
 * Speak a phrase. Tries MP3 first, browser TTS second.
 * @param {string} text - native text to speak (used for browser TTS fallback)
 * @param {string} langCode - BCP-47 like "ur-PK", "es-ES"
 * @param {object} opts
 * @param {string} opts.audioId - if provided, attempts to play pre-generated MP3 first
 */
export async function speak(text, langCode, opts = {}) {
  const { audioId, rate = 0.85, pitch = 1 } = opts;

  // Stop any currently playing audio
  stopSpeaking();

  // Tier 1: pre-generated MP3
  if (audioId) {
    const ok = await tryPlayMp3(langCode, audioId);
    if (ok) return true;
  }

  // Tier 2: browser TTS
  const ok = await speakWithBrowser(text, langCode, { rate, pitch });
  return ok;
}

/**
 * Synchronous-ish check: is audio available for this word right now?
 * Used by the UI to hide the audio button if both MP3 and browser TTS would fail.
 * Returns true optimistically — actual playback may still fail.
 */
export function hasAudioFor(langCode, audioId) {
  // If we have a cached "false" for the MP3, fall back to browser TTS check
  if (audioId) {
    const cacheKey = `${langCode}/${audioId}`;
    if (mp3AvailabilityCache.get(cacheKey) === true) return true;
  }
  // Check browser TTS availability
  if (!voicesLoaded) return true; // optimistic: assume yes until we know
  return !!bestVoice(langCode);
}

/** Legacy alias — older code paths may still use this name. */
export function hasVoiceFor(langCode) {
  return hasAudioFor(langCode);
}

export function stopSpeaking() {
  if (activeAudio) {
    try { activeAudio.pause(); activeAudio.currentTime = 0; } catch {}
    activeAudio = null;
  }
  if (typeof window !== "undefined" && window.speechSynthesis) {
    window.speechSynthesis.cancel();
  }
}
