import { writeFileSync, mkdirSync } from "node:fs";
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const URL_ = "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Fraunces:opsz,wght@9..144,600;9..144,700;9..144,800&family=Noto+Naskh+Arabic:wght@400;600;700&family=Noto+Nastaliq+Urdu:wght@400;700&display=swap";
// Only the subsets this app actually renders. Shipping cyrillic/greek/vietnamese
// would triple the payload for scripts no course uses.
const KEEP = new Set(["latin", "latin-ext", "arabic"]);
mkdirSync("public/fonts", { recursive: true });
const css = await (await fetch(URL_, { headers: { "User-Agent": UA } })).text();
const blocks = css.split(/(?=\/\* )/).filter(Boolean);
let out = [], n = 0, skipped = 0;
for (const b of blocks) {
  const subset = b.match(/^\/\* ([a-z0-9-]+) \*\//)?.[1];
  const url = b.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!subset || !url) continue;
  if (!KEEP.has(subset)) { skipped++; continue; }
  const fam = b.match(/font-family: '([^']+)'/)[1];
  const wt = b.match(/font-weight: ([^;]+);/)[1].trim();
  const name = `${fam.replace(/\s+/g, "")}-${wt.replace(/\s+/g, "_")}-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(`public/fonts/${name}`, buf);
  n++;
  out.push(b.replace(/url\(https:[^)]+\.woff2\)/, `url(/fonts/${name})`).replace(/^\/\* .+ \*\/\n/, ""));
}
writeFileSync("public/fonts/fonts.css",
  "/* Self-hosted (v77). Generated by scripts/fetch-fonts.mjs — do not hand-edit.\n" +
  "   Loading these from fonts.googleapis.com sent every visitor's IP address to\n" +
  "   Google on page load, with no consent and no way to decline. A German court\n" +
  "   (LG München I, 3 O 17493/20) awarded damages for exactly that. Self-hosting\n" +
  "   removes the transfer entirely, which is simpler than justifying it. */\n\n" +
  out.join("\n"));
console.log(`saved ${n} font files, skipped ${skipped} unused subsets`);
